// Code generated by tools/codegen.py. DO NOT EDIT.
package frontend

const (
	SYM_MAML_ALLOC = "maml_alloc"
	SYM_MAML_CORO_DESTROY_HELPER = "maml_coro_destroy_helper"
	SYM_MAML_CORO_DONE_HELPER = "maml_coro_done_helper"
	SYM_MAML_CORO_RESUME_HELPER = "maml_coro_resume_helper"
	SYM_MAML_FREE = "maml_free"
	SYM_MAML_MAP_CREATE = "maml_map_create"
	SYM_MAML_MAP_DELETE = "maml_map_delete"
	SYM_MAML_MAP_GET = "maml_map_get"
	SYM_MAML_MAP_LEN = "maml_map_len"
	SYM_MAML_MAP_PUT = "maml_map_put"
	SYM_MAML_RELEASE = "maml_release"
	SYM_MAML_RETAIN = "maml_retain"
	SYM_MAML_RUN_EXECUTOR = "maml_run_executor"
	SYM_MAML_SPAWN_TASK = "maml_spawn_task"
	SYM_MAML_STR_EQ = "maml_str_eq"
	SYM_MAML_STR_HASH = "maml_str_hash"
	SYM_MAML_VEC_CREATE = "maml_vec_create"
	SYM_MAML_VEC_GET = "maml_vec_get"
	SYM_MAML_VEC_GROW = "maml_vec_grow"
	SYM_MAML_VEC_LEN = "maml_vec_len"
	SYM_MAML_VEC_PUSH = "maml_vec_push"
	SYM_MAML_VEC_SET = "maml_vec_set"
	SYM_PUTS = "puts"
)
