// Code generated by tools/gen_spec.go. DO NOT EDIT.
#pragma once

#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Type.h>
#include "CodegenContext.hpp"

namespace maml {
namespace rt {

// ============================================================================
// Field Index Enums (Symbolic access to struct members)
// ============================================================================
namespace String {
    enum class Field : unsigned {
        PTR,
        LEN,
        IS_OWNED
    };
}
namespace Vector {
    enum class Field : unsigned {
        BUFFER,
        CAP,
        LEN,
        ELEM_SIZE
    };
}
namespace View {
    enum class Field : unsigned {
        DATA_PTR,
        LEN
    };
}
namespace Map {
    enum class Field : unsigned {
        ENTRIES,
        COUNT,
        TOMBSTONE_COUNT,
        CAP,
        VAL_SIZE,
        IS_STRING_KEY
    };
}
namespace Ref {
    enum class Field : unsigned {
        PTR,
        REFCOUNT
    };
}

// ============================================================================
// Struct Builder Functions (Create correct LLVM struct types)
// ============================================================================
inline llvm::StructType* getStringType(llvm::LLVMContext &C) {
    return llvm::StructType::get(C, {llvm::PointerType::getUnqual(C), llvm::Type::getInt32Ty(C), llvm::Type::getInt1Ty(C)
    });
}
inline llvm::StructType* getVectorType(llvm::LLVMContext &C) {
    return llvm::StructType::get(C, {llvm::PointerType::getUnqual(C), llvm::Type::getInt32Ty(C), llvm::Type::getInt32Ty(C), llvm::Type::getInt32Ty(C)
    });
}
inline llvm::StructType* getViewType(llvm::LLVMContext &C) {
    return llvm::StructType::get(C, {llvm::PointerType::getUnqual(C), llvm::Type::getInt32Ty(C)
    });
}
inline llvm::StructType* getMapType(llvm::LLVMContext &C) {
    return llvm::StructType::get(C, {llvm::PointerType::getUnqual(C), llvm::Type::getInt32Ty(C), llvm::Type::getInt32Ty(C), llvm::Type::getInt32Ty(C), llvm::Type::getInt32Ty(C), llvm::Type::getInt1Ty(C)
    });
}
inline llvm::StructType* getRefType(llvm::LLVMContext &C) {
    return llvm::StructType::get(C, {llvm::PointerType::getUnqual(C), llvm::PointerType::getUnqual(C)
    });
}

// ============================================================================
// Runtime Function Signatures
// ============================================================================
inline void declareRuntimeFunctions(CodegenContext &ctx) {
    auto &M = ctx.Module;
    M->getOrInsertFunction("maml_alloc",
        llvm::FunctionType::get(llvm::PointerType::getUnqual(ctx.Context), {llvm::Type::getInt64Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_free",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_realloc",
        llvm::FunctionType::get(llvm::PointerType::getUnqual(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt64Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_calloc",
        llvm::FunctionType::get(llvm::PointerType::getUnqual(ctx.Context), {llvm::Type::getInt64Ty(ctx.Context), llvm::Type::getInt64Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_vec_push",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_vec_get",
        llvm::FunctionType::get(llvm::PointerType::getUnqual(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_vec_set",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context), llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_vec_len",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_vec_clone",
        llvm::FunctionType::get(rt::getVectorType(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_vec_free",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_map_put",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context), llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context), llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_map_get",
        llvm::FunctionType::get(llvm::PointerType::getUnqual(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context), llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_map_delete",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context), llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_map_len",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_map_clone",
        llvm::FunctionType::get(rt::getMapType(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_map_free",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_str_hash",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_str_eq",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context), llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_str_clone",
        llvm::FunctionType::get(llvm::PointerType::getUnqual(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_str_len",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {rt::getStringType(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_coro_runtime_init",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {
        }, false));
    M->getOrInsertFunction("maml_coro_resume_helper",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_coro_done_helper",
        llvm::FunctionType::get(llvm::Type::getInt1Ty(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_coro_destroy_helper",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_spawn_task",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_run_executor",
        llvm::FunctionType::get(llvm::PointerType::getUnqual(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_task_await",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context), llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_task_release",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_yield_now",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::PointerType::getUnqual(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_print",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {rt::getStringType(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_file_open",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {rt::getStringType(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_file_close",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_file_read_str",
        llvm::FunctionType::get(rt::getStringType(ctx.Context), {llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_file_write_str",
        llvm::FunctionType::get(llvm::Type::getVoidTy(ctx.Context), {llvm::Type::getInt32Ty(ctx.Context), rt::getStringType(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_socket",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {llvm::Type::getInt32Ty(ctx.Context), llvm::Type::getInt32Ty(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_bind",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {llvm::Type::getInt32Ty(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_listen",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {llvm::Type::getInt32Ty(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_accept",
        llvm::FunctionType::get(llvm::Type::getInt32Ty(ctx.Context), {llvm::Type::getInt32Ty(ctx.Context)
        }, false));
    M->getOrInsertFunction("maml_socket_read",
        llvm::FunctionType::get(rt::getStringType(ctx.Context), {llvm::Type::getInt32Ty(ctx.Context), llvm::Type::getInt32Ty(ctx.Context)
        }, false));
}

} // namespace rt
} // namespace maml