// Code generated by gen_cpp_mir.go. DO NOT EDIT.
#pragma once

#include "types_generated.hpp"
#include <string>
#include <vector>
#include <variant>
#include <stdexcept>
#include <nlohmann/json.hpp>

namespace mir {

// ============================================================================
// 1. Forward Declarations & Struct Definitions
// ============================================================================
struct Value;
struct Instruction;
struct Terminator;
struct BoolConstant {
    std::shared_ptr<maml::Type> type;
    bool value;
};
struct IntConstant {
    std::shared_ptr<maml::Type> type;
    int64_t value;
};
struct Register {
    std::string name;
    std::shared_ptr<maml::Type> type;
};
struct StringConstant {
    std::shared_ptr<maml::Type> type;
    std::string value;
};

using ValueVariant = std::variant<BoolConstant, IntConstant, Register, StringConstant
>;

struct Value {
    ValueVariant inner;
};
struct ArrayInitInst {
    std::string dst;
    int32_t index;
    Value value;
};
struct AssignInst {
    std::string dst;
    Value r_value;
};
struct BinaryOpInst {
    std::string dst;
    Value left;
    std::string operator_;
    Value right;
    std::shared_ptr<maml::Type> type;
};
struct CallInst {
    std::vector<Value> arguments;
    std::string dst;
    Value function;
    std::shared_ptr<maml::Type> type;
};
struct CastInst {
    std::string dst;
    Value src;
    std::shared_ptr<maml::Type> type;
};
struct CopyInst {
    std::string dst;
    std::string src;
};
struct CoroPrologueInst {
};
struct DropInst {
    std::string src;
};
struct FieldAddrInst {
    std::string dst;
    int32_t field_index;
    std::string field_name;
    int32_t field_offset;
    Value object;
    std::shared_ptr<maml::Type> type;
    std::vector<std::shared_ptr<maml::Type>> variant_layout;
};
struct IndexAddrInst {
    std::string dst;
    Value index;
    Value source;
    std::shared_ptr<maml::Type> source_type;
    std::shared_ptr<maml::Type> type;
};
struct LoadPtrInst {
    std::string dst;
    Value ptr;
    std::shared_ptr<maml::Type> type;
};
struct MoveInst {
    std::string dst;
    std::string src;
};
struct SliceInst {
    std::shared_ptr<maml::Type> container_type;
    std::string dst;
    Value high;
    Value left;
    Value low;
    std::shared_ptr<maml::Type> result_type;
};
struct StoreInst {
    std::string dst_ptr;
    std::shared_ptr<maml::Type> type;
    Value value;
};
struct StructInitInst {
    std::string dst;
    int32_t field_index;
    std::string field_name;
    int32_t field_offset;
    Value value;
    std::vector<std::shared_ptr<maml::Type>> variant_layout;
};
struct TempDeclInst {
    std::string name;
    std::shared_ptr<maml::Type> type;
};
struct UnaryOpInst {
    std::string dst;
    Value operand;
    std::string operator_;
    std::shared_ptr<maml::Type> type;
};
struct VariantDiscriminantInst {
    std::string dst;
    Value object;
    std::shared_ptr<maml::Type> type;
};
struct VariantInitInst {
    int32_t discriminant;
    std::string dst;
    std::vector<Value> payloads;
    std::shared_ptr<maml::Type> type;
    std::string variant_name;
};
struct VariantReadInst {
    std::string dst;
    Value object;
    int32_t payload_index;
    std::shared_ptr<maml::Type> type;
    std::string variant_name;
};

using InstVariant = std::variant<ArrayInitInst, AssignInst, BinaryOpInst, CallInst, CastInst, CopyInst, CoroPrologueInst, DropInst, FieldAddrInst, IndexAddrInst, LoadPtrInst, MoveInst, SliceInst, StoreInst, StructInitInst, TempDeclInst, UnaryOpInst, VariantDiscriminantInst, VariantInitInst, VariantReadInst
>;

struct Instruction {
    InstVariant inner;
};
struct BranchTerminator {
    Value condition;
    std::string false_target;
    std::string true_target;
};
struct CoroSuspendTerminator {
    std::string cleanup_block;
    std::string resume_block;
    std::string suspend_block;
};
struct CoroYieldTerminator {
};
struct JumpTerminator {
    std::string target;
};
struct ReturnTerminator {
    Value value;
};
struct UnreachableTerminator {
};

using TermVariant = std::variant<BranchTerminator, CoroSuspendTerminator, CoroYieldTerminator, JumpTerminator, ReturnTerminator, UnreachableTerminator
>;

struct Terminator {
    TermVariant inner;
};

// Top-Level Graph Structures
struct BasicBlock {
    std::string id;
    std::vector<Instruction> instructions;
    Terminator terminator;
};

struct ExportParam {
    std::string name;
    std::shared_ptr<maml::Type> type;
};

struct Function {
    std::string name;
    std::shared_ptr<maml::Type> return_type;
    std::vector<ExportParam> params;
    bool is_async;
    bool is_extern;
    std::string entry_block;
    std::vector<BasicBlock> blocks;
};

struct Program {
    std::vector<Function> functions;
};

// ============================================================================
// 2. Forward Declarations of Parsers
// ============================================================================
void from_json(const nlohmann::json& j, BoolConstant& t);
void from_json(const nlohmann::json& j, IntConstant& t);
void from_json(const nlohmann::json& j, Register& t);
void from_json(const nlohmann::json& j, StringConstant& t);
void from_json(const nlohmann::json& j, ArrayInitInst& t);
void from_json(const nlohmann::json& j, AssignInst& t);
void from_json(const nlohmann::json& j, BinaryOpInst& t);
void from_json(const nlohmann::json& j, CallInst& t);
void from_json(const nlohmann::json& j, CastInst& t);
void from_json(const nlohmann::json& j, CopyInst& t);
void from_json(const nlohmann::json& j, CoroPrologueInst& t);
void from_json(const nlohmann::json& j, DropInst& t);
void from_json(const nlohmann::json& j, FieldAddrInst& t);
void from_json(const nlohmann::json& j, IndexAddrInst& t);
void from_json(const nlohmann::json& j, LoadPtrInst& t);
void from_json(const nlohmann::json& j, MoveInst& t);
void from_json(const nlohmann::json& j, SliceInst& t);
void from_json(const nlohmann::json& j, StoreInst& t);
void from_json(const nlohmann::json& j, StructInitInst& t);
void from_json(const nlohmann::json& j, TempDeclInst& t);
void from_json(const nlohmann::json& j, UnaryOpInst& t);
void from_json(const nlohmann::json& j, VariantDiscriminantInst& t);
void from_json(const nlohmann::json& j, VariantInitInst& t);
void from_json(const nlohmann::json& j, VariantReadInst& t);
void from_json(const nlohmann::json& j, BranchTerminator& t);
void from_json(const nlohmann::json& j, CoroSuspendTerminator& t);
void from_json(const nlohmann::json& j, CoroYieldTerminator& t);
void from_json(const nlohmann::json& j, JumpTerminator& t);
void from_json(const nlohmann::json& j, ReturnTerminator& t);
void from_json(const nlohmann::json& j, UnreachableTerminator& t);

void from_json(const nlohmann::json& j, Value& v);
void from_json(const nlohmann::json& j, Instruction& inst);
void from_json(const nlohmann::json& j, Terminator& term);
void from_json(const nlohmann::json& j, BasicBlock& t);
void from_json(const nlohmann::json& j, ExportParam& t);
void from_json(const nlohmann::json& j, Function& t);
void from_json(const nlohmann::json& j, Program& t);

// ============================================================================
// 3. Parser Implementations (100% Compiler Safe, No Macros)
// ============================================================================
inline void from_json(const nlohmann::json& j, BoolConstant& t) {
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.value);
    }
}
inline void from_json(const nlohmann::json& j, IntConstant& t) {
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.value);
    }
}
inline void from_json(const nlohmann::json& j, Register& t) {
    if (j.contains("name") && !j.at("name").is_null()) {
        j.at("name").get_to(t.name);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, StringConstant& t) {
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.value);
    }
}
inline void from_json(const nlohmann::json& j, ArrayInitInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("index") && !j.at("index").is_null()) {
        j.at("index").get_to(t.index);
    }
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.value);
    }
}
inline void from_json(const nlohmann::json& j, AssignInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.r_value);
    }
}
inline void from_json(const nlohmann::json& j, BinaryOpInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("left") && !j.at("left").is_null()) {
        j.at("left").get_to(t.left);
    }
    if (j.contains("operator") && !j.at("operator").is_null()) {
        j.at("operator").get_to(t.operator_);
    }
    if (j.contains("right") && !j.at("right").is_null()) {
        j.at("right").get_to(t.right);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, CallInst& t) {
    if (j.contains("arguments") && !j.at("arguments").is_null()) {
        j.at("arguments").get_to(t.arguments);
    }
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("function") && !j.at("function").is_null()) {
        j.at("function").get_to(t.function);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, CastInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("src") && !j.at("src").is_null()) {
        j.at("src").get_to(t.src);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, CopyInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("src") && !j.at("src").is_null()) {
        j.at("src").get_to(t.src);
    }
}
inline void from_json(const nlohmann::json& j, CoroPrologueInst& t) {
}
inline void from_json(const nlohmann::json& j, DropInst& t) {
    if (j.contains("src") && !j.at("src").is_null()) {
        j.at("src").get_to(t.src);
    }
}
inline void from_json(const nlohmann::json& j, FieldAddrInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("field_index") && !j.at("field_index").is_null()) {
        j.at("field_index").get_to(t.field_index);
    }
    if (j.contains("field_name") && !j.at("field_name").is_null()) {
        j.at("field_name").get_to(t.field_name);
    }
    if (j.contains("field_offset") && !j.at("field_offset").is_null()) {
        j.at("field_offset").get_to(t.field_offset);
    }
    if (j.contains("object") && !j.at("object").is_null()) {
        j.at("object").get_to(t.object);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
    if (j.contains("variant_layout") && !j.at("variant_layout").is_null()) {
        j.at("variant_layout").get_to(t.variant_layout);
    }
}
inline void from_json(const nlohmann::json& j, IndexAddrInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("index") && !j.at("index").is_null()) {
        j.at("index").get_to(t.index);
    }
    if (j.contains("source") && !j.at("source").is_null()) {
        j.at("source").get_to(t.source);
    }
    if (j.contains("source_type") && !j.at("source_type").is_null()) {
        j.at("source_type").get_to(t.source_type);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, LoadPtrInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("ptr") && !j.at("ptr").is_null()) {
        j.at("ptr").get_to(t.ptr);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, MoveInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("src") && !j.at("src").is_null()) {
        j.at("src").get_to(t.src);
    }
}
inline void from_json(const nlohmann::json& j, SliceInst& t) {
    if (j.contains("container_type") && !j.at("container_type").is_null()) {
        j.at("container_type").get_to(t.container_type);
    }
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("high") && !j.at("high").is_null()) {
        j.at("high").get_to(t.high);
    }
    if (j.contains("left") && !j.at("left").is_null()) {
        j.at("left").get_to(t.left);
    }
    if (j.contains("low") && !j.at("low").is_null()) {
        j.at("low").get_to(t.low);
    }
    if (j.contains("result_type") && !j.at("result_type").is_null()) {
        j.at("result_type").get_to(t.result_type);
    }
}
inline void from_json(const nlohmann::json& j, StoreInst& t) {
    if (j.contains("dst_ptr") && !j.at("dst_ptr").is_null()) {
        j.at("dst_ptr").get_to(t.dst_ptr);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.value);
    }
}
inline void from_json(const nlohmann::json& j, StructInitInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("field_index") && !j.at("field_index").is_null()) {
        j.at("field_index").get_to(t.field_index);
    }
    if (j.contains("field_name") && !j.at("field_name").is_null()) {
        j.at("field_name").get_to(t.field_name);
    }
    if (j.contains("field_offset") && !j.at("field_offset").is_null()) {
        j.at("field_offset").get_to(t.field_offset);
    }
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.value);
    }
    if (j.contains("variant_layout") && !j.at("variant_layout").is_null()) {
        j.at("variant_layout").get_to(t.variant_layout);
    }
}
inline void from_json(const nlohmann::json& j, TempDeclInst& t) {
    if (j.contains("name") && !j.at("name").is_null()) {
        j.at("name").get_to(t.name);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, UnaryOpInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("operand") && !j.at("operand").is_null()) {
        j.at("operand").get_to(t.operand);
    }
    if (j.contains("operator") && !j.at("operator").is_null()) {
        j.at("operator").get_to(t.operator_);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, VariantDiscriminantInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("object") && !j.at("object").is_null()) {
        j.at("object").get_to(t.object);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, VariantInitInst& t) {
    if (j.contains("discriminant") && !j.at("discriminant").is_null()) {
        j.at("discriminant").get_to(t.discriminant);
    }
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("payloads") && !j.at("payloads").is_null()) {
        j.at("payloads").get_to(t.payloads);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
    if (j.contains("variant_name") && !j.at("variant_name").is_null()) {
        j.at("variant_name").get_to(t.variant_name);
    }
}
inline void from_json(const nlohmann::json& j, VariantReadInst& t) {
    if (j.contains("dst") && !j.at("dst").is_null()) {
        j.at("dst").get_to(t.dst);
    }
    if (j.contains("object") && !j.at("object").is_null()) {
        j.at("object").get_to(t.object);
    }
    if (j.contains("payload_index") && !j.at("payload_index").is_null()) {
        j.at("payload_index").get_to(t.payload_index);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
    if (j.contains("variant_name") && !j.at("variant_name").is_null()) {
        j.at("variant_name").get_to(t.variant_name);
    }
}
inline void from_json(const nlohmann::json& j, BranchTerminator& t) {
    if (j.contains("condition") && !j.at("condition").is_null()) {
        j.at("condition").get_to(t.condition);
    }
    if (j.contains("false_target") && !j.at("false_target").is_null()) {
        j.at("false_target").get_to(t.false_target);
    }
    if (j.contains("true_target") && !j.at("true_target").is_null()) {
        j.at("true_target").get_to(t.true_target);
    }
}
inline void from_json(const nlohmann::json& j, CoroSuspendTerminator& t) {
    if (j.contains("cleanup_block") && !j.at("cleanup_block").is_null()) {
        j.at("cleanup_block").get_to(t.cleanup_block);
    }
    if (j.contains("resume_block") && !j.at("resume_block").is_null()) {
        j.at("resume_block").get_to(t.resume_block);
    }
    if (j.contains("suspend_block") && !j.at("suspend_block").is_null()) {
        j.at("suspend_block").get_to(t.suspend_block);
    }
}
inline void from_json(const nlohmann::json& j, CoroYieldTerminator& t) {
}
inline void from_json(const nlohmann::json& j, JumpTerminator& t) {
    if (j.contains("target") && !j.at("target").is_null()) {
        j.at("target").get_to(t.target);
    }
}
inline void from_json(const nlohmann::json& j, ReturnTerminator& t) {
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.value);
    }
}
inline void from_json(const nlohmann::json& j, UnreachableTerminator& t) {
}

// Top-Level Implementations
inline void from_json(const nlohmann::json& j, BasicBlock& t) {
    if (j.contains("id")) j.at("id").get_to(t.id);
    if (j.contains("instructions")) j.at("instructions").get_to(t.instructions);
    if (j.contains("terminator")) j.at("terminator").get_to(t.terminator);
}

inline void from_json(const nlohmann::json& j, ExportParam& t) {
    if (j.contains("name")) j.at("name").get_to(t.name);
    if (j.contains("type")) j.at("type").get_to(t.type);
}

inline void from_json(const nlohmann::json& j, Function& t) {
    if (j.contains("name")) j.at("name").get_to(t.name);
    if (j.contains("return_type")) j.at("return_type").get_to(t.return_type);
    if (j.contains("params")) j.at("params").get_to(t.params);
    if (j.contains("is_async")) j.at("is_async").get_to(t.is_async);
    if (j.contains("is_extern")) j.at("is_extern").get_to(t.is_extern);
    if (j.contains("entry_block")) j.at("entry_block").get_to(t.entry_block);
    if (j.contains("blocks")) j.at("blocks").get_to(t.blocks);
}

inline void from_json(const nlohmann::json& j, Program& t) {
    if (j.contains("functions")) j.at("functions").get_to(t.functions);
}

// Polymorphic Dispatchers
inline void from_json(const nlohmann::json& j, Value& v) {
    if (j.is_null()) return;
    auto op = j.at("op").get<std::string>();
    if (op == "const_bool") { v.inner = j.get<BoolConstant>(); return; }
    if (op == "const_int") { v.inner = j.get<IntConstant>(); return; }
    if (op == "ident") { v.inner = j.get<Register>(); return; }
    if (op == "const_string") { v.inner = j.get<StringConstant>(); return; }
    throw std::runtime_error("Unknown Value op: " + op);
}

inline void from_json(const nlohmann::json& j, Instruction& inst) {
    auto op = j.at("op").get<std::string>();
    if (op == "array_init") { inst.inner = j.get<ArrayInitInst>(); return; }
    if (op == "assign") { inst.inner = j.get<AssignInst>(); return; }
    if (op == "binary_op") { inst.inner = j.get<BinaryOpInst>(); return; }
    if (op == "call_inst") { inst.inner = j.get<CallInst>(); return; }
    if (op == "cast") { inst.inner = j.get<CastInst>(); return; }
    if (op == "copy") { inst.inner = j.get<CopyInst>(); return; }
    if (op == "coro_prologue") { inst.inner = j.get<CoroPrologueInst>(); return; }
    if (op == "drop") { inst.inner = j.get<DropInst>(); return; }
    if (op == "field_addr") { inst.inner = j.get<FieldAddrInst>(); return; }
    if (op == "index_addr") { inst.inner = j.get<IndexAddrInst>(); return; }
    if (op == "load_ptr") { inst.inner = j.get<LoadPtrInst>(); return; }
    if (op == "move") { inst.inner = j.get<MoveInst>(); return; }
    if (op == "slice_read") { inst.inner = j.get<SliceInst>(); return; }
    if (op == "store") { inst.inner = j.get<StoreInst>(); return; }
    if (op == "struct_init") { inst.inner = j.get<StructInitInst>(); return; }
    if (op == "temp_decl") { inst.inner = j.get<TempDeclInst>(); return; }
    if (op == "unary_op") { inst.inner = j.get<UnaryOpInst>(); return; }
    if (op == "variant_discriminant") { inst.inner = j.get<VariantDiscriminantInst>(); return; }
    if (op == "variant_init") { inst.inner = j.get<VariantInitInst>(); return; }
    if (op == "variant_read") { inst.inner = j.get<VariantReadInst>(); return; }
    throw std::runtime_error("Unknown Instruction op: " + op);
}

inline void from_json(const nlohmann::json& j, Terminator& term) {
    if (j.is_null()) return;
    auto op = j.at("op").get<std::string>();
    if (op == "cond_br") { term.inner = j.get<BranchTerminator>(); return; }
    if (op == "coro_suspend") { term.inner = j.get<CoroSuspendTerminator>(); return; }
    if (op == "coro_yield") { term.inner = j.get<CoroYieldTerminator>(); return; }
    if (op == "br") { term.inner = j.get<JumpTerminator>(); return; }
    if (op == "ret") { term.inner = j.get<ReturnTerminator>(); return; }
    if (op == "unreachable") { term.inner = j.get<UnreachableTerminator>(); return; }
    throw std::runtime_error("Unknown Terminator op: " + op);
}

} // namespace mir