// Code generated by gen_types.go. DO NOT EDIT.
#pragma once

#include <string>
#include <vector>
#include <variant>
#include <stdexcept>
#include <memory>
#include <unordered_map>
#include <functional>
#include <nlohmann/json.hpp>

namespace maml {

struct Type;
struct StructField {
    std::string name;
    std::shared_ptr<maml::Type> type;
};
struct SumVariant {
    std::string name;
    int32_t discriminant;
    std::vector<std::shared_ptr<maml::Type>> tuple_types;
    std::vector<maml::StructField> fields;
};
struct I8Type {};
struct I16Type {};
struct I32Type {};
struct I64Type {};
struct I128Type {};
struct U8Type {};
struct U16Type {};
struct U32Type {};
struct U64Type {};
struct U128Type {};
struct F32Type {};
struct F64Type {};
struct BoolType {};
struct CharType {};
struct UnitType {};
struct StringType {};
struct AnyType {};
struct UnknownType {};
struct PtrType {};
struct StructType {
    std::string name;
    std::vector<maml::StructField> fields;
    bool is_repr_c;
};
struct SumType {
    std::string base_name;
    std::vector<maml::SumVariant> variants;
    std::vector<std::shared_ptr<maml::Type>> type_args;
};
struct FunctionType {
    std::vector<std::shared_ptr<maml::Type>> params;
    std::vector<std::string> caps;
    std::shared_ptr<maml::Type> return_type;
};
struct ArrayType {
    std::shared_ptr<maml::Type> base;
    int32_t size;
};
struct ViewType {
    std::shared_ptr<maml::Type> base;
    bool is_mut;
};
struct VectorType {
    std::shared_ptr<maml::Type> base;
};
struct MapType {
    std::shared_ptr<maml::Type> key;
    std::shared_ptr<maml::Type> value;
};
struct FutureType {
    std::shared_ptr<maml::Type> base;
};
struct RefType {
    std::shared_ptr<maml::Type> base;
};
struct WeakRefType {
    std::shared_ptr<maml::Type> base;
};
struct SenderType {
    std::shared_ptr<maml::Type> base;
};
struct ReceiverType {
    std::shared_ptr<maml::Type> base;
};

using TypeVariant = std::variant<I8Type, I16Type, I32Type, I64Type, I128Type, U8Type, U16Type, U32Type, U64Type, U128Type, F32Type, F64Type, BoolType, CharType, UnitType, StringType, AnyType, UnknownType, PtrType, StructType, SumType, FunctionType, ArrayType, ViewType, VectorType, MapType, FutureType, RefType, WeakRefType, SenderType, ReceiverType
>;

struct Type {
    TypeVariant inner;
};

// ============================================================================
// Forward Declarations of JSON Parsers
// ============================================================================
inline void from_json(const nlohmann::json& j, Type& v);

inline void from_json(const nlohmann::json& j, std::shared_ptr<Type>& p) {
    if (j.is_null()) {
        p = nullptr;
    } else {
        p = std::make_shared<Type>();
        from_json(j, *p);
    }
}
inline void from_json(const nlohmann::json& j, StructField& t);
inline void from_json(const nlohmann::json& j, SumVariant& t);
inline void from_json(const nlohmann::json& j, StructType& t);
inline void from_json(const nlohmann::json& j, SumType& t);
inline void from_json(const nlohmann::json& j, FunctionType& t);
inline void from_json(const nlohmann::json& j, ArrayType& t);
inline void from_json(const nlohmann::json& j, ViewType& t);
inline void from_json(const nlohmann::json& j, VectorType& t);
inline void from_json(const nlohmann::json& j, MapType& t);
inline void from_json(const nlohmann::json& j, FutureType& t);
inline void from_json(const nlohmann::json& j, RefType& t);
inline void from_json(const nlohmann::json& j, WeakRefType& t);
inline void from_json(const nlohmann::json& j, SenderType& t);
inline void from_json(const nlohmann::json& j, ReceiverType& t);

// ============================================================================
// Implementations
// ============================================================================
inline void from_json(const nlohmann::json& j, StructField& t) {
    if (j.contains("name") && !j.at("name").is_null()) {
        j.at("name").get_to(t.name);
    }
    if (j.contains("type") && !j.at("type").is_null()) {
        j.at("type").get_to(t.type);
    }
}
inline void from_json(const nlohmann::json& j, SumVariant& t) {
    if (j.contains("name") && !j.at("name").is_null()) {
        j.at("name").get_to(t.name);
    }
    if (j.contains("discriminant") && !j.at("discriminant").is_null()) {
        j.at("discriminant").get_to(t.discriminant);
    }
    if (j.contains("tuple_types") && !j.at("tuple_types").is_null()) {
        j.at("tuple_types").get_to(t.tuple_types);
    }
    if (j.contains("fields") && !j.at("fields").is_null()) {
        j.at("fields").get_to(t.fields);
    }
}
inline void from_json(const nlohmann::json& j, StructType& t) {
    if (j.contains("name") && !j.at("name").is_null()) {
        j.at("name").get_to(t.name);
    }
    if (j.contains("fields") && !j.at("fields").is_null()) {
        j.at("fields").get_to(t.fields);
    }
    if (j.contains("is_repr_c") && !j.at("is_repr_c").is_null()) {
        j.at("is_repr_c").get_to(t.is_repr_c);
    }
}
inline void from_json(const nlohmann::json& j, SumType& t) {
    if (j.contains("base_name") && !j.at("base_name").is_null()) {
        j.at("base_name").get_to(t.base_name);
    }
    if (j.contains("variants") && !j.at("variants").is_null()) {
        j.at("variants").get_to(t.variants);
    }
    if (j.contains("type_args") && !j.at("type_args").is_null()) {
        j.at("type_args").get_to(t.type_args);
    }
}
inline void from_json(const nlohmann::json& j, FunctionType& t) {
    if (j.contains("params") && !j.at("params").is_null()) {
        j.at("params").get_to(t.params);
    }
    if (j.contains("caps") && !j.at("caps").is_null()) {
        j.at("caps").get_to(t.caps);
    }
    if (j.contains("return_type") && !j.at("return_type").is_null()) {
        j.at("return_type").get_to(t.return_type);
    }
}
inline void from_json(const nlohmann::json& j, ArrayType& t) {
    if (j.contains("base") && !j.at("base").is_null()) {
        j.at("base").get_to(t.base);
    }
    if (j.contains("size") && !j.at("size").is_null()) {
        j.at("size").get_to(t.size);
    }
}
inline void from_json(const nlohmann::json& j, ViewType& t) {
    if (j.contains("base") && !j.at("base").is_null()) {
        j.at("base").get_to(t.base);
    }
    if (j.contains("is_mut") && !j.at("is_mut").is_null()) {
        j.at("is_mut").get_to(t.is_mut);
    }
}
inline void from_json(const nlohmann::json& j, VectorType& t) {
    if (j.contains("base") && !j.at("base").is_null()) {
        j.at("base").get_to(t.base);
    }
}
inline void from_json(const nlohmann::json& j, MapType& t) {
    if (j.contains("key") && !j.at("key").is_null()) {
        j.at("key").get_to(t.key);
    }
    if (j.contains("value") && !j.at("value").is_null()) {
        j.at("value").get_to(t.value);
    }
}
inline void from_json(const nlohmann::json& j, FutureType& t) {
    if (j.contains("base") && !j.at("base").is_null()) {
        j.at("base").get_to(t.base);
    }
}
inline void from_json(const nlohmann::json& j, RefType& t) {
    if (j.contains("base") && !j.at("base").is_null()) {
        j.at("base").get_to(t.base);
    }
}
inline void from_json(const nlohmann::json& j, WeakRefType& t) {
    if (j.contains("base") && !j.at("base").is_null()) {
        j.at("base").get_to(t.base);
    }
}
inline void from_json(const nlohmann::json& j, SenderType& t) {
    if (j.contains("base") && !j.at("base").is_null()) {
        j.at("base").get_to(t.base);
    }
}
inline void from_json(const nlohmann::json& j, ReceiverType& t) {
    if (j.contains("base") && !j.at("base").is_null()) {
        j.at("base").get_to(t.base);
    }
}

inline void from_json(const nlohmann::json& j, Type& v) {
    if (j.is_string()) {
        auto kind = j.get<std::string>();
        static const std::unordered_map<std::string, std::function<void(Type&)>> primMap = {
            {"i8", [](Type& val) { val.inner = I8Type{}; }},
            {"i16", [](Type& val) { val.inner = I16Type{}; }},
            {"i32", [](Type& val) { val.inner = I32Type{}; }},
            {"i64", [](Type& val) { val.inner = I64Type{}; }},
            {"i128", [](Type& val) { val.inner = I128Type{}; }},
            {"u8", [](Type& val) { val.inner = U8Type{}; }},
            {"u16", [](Type& val) { val.inner = U16Type{}; }},
            {"u32", [](Type& val) { val.inner = U32Type{}; }},
            {"u64", [](Type& val) { val.inner = U64Type{}; }},
            {"u128", [](Type& val) { val.inner = U128Type{}; }},
            {"f32", [](Type& val) { val.inner = F32Type{}; }},
            {"f64", [](Type& val) { val.inner = F64Type{}; }},
            {"i1", [](Type& val) { val.inner = BoolType{}; }},
            {"char", [](Type& val) { val.inner = CharType{}; }},
            {"void", [](Type& val) { val.inner = UnitType{}; }},
            {"string", [](Type& val) { val.inner = StringType{}; }},
            {"any", [](Type& val) { val.inner = AnyType{}; }},
            {"unknown", [](Type& val) { val.inner = UnknownType{}; }},
            {"ptr", [](Type& val) { val.inner = PtrType{}; }},
        };
        auto it = primMap.find(kind);
        if (it != primMap.end()) {
            it->second(v);
            return;
        }
        throw std::runtime_error("Unknown primitive type string: " + kind);
    }
    
    if (j.is_object() && j.contains("kind")) {
        auto kind = j.at("kind").get<std::string>();
        static const std::unordered_map<std::string, std::function<void(const nlohmann::json&, Type&)>> compMap = {
            {"struct", [](const nlohmann::json& json, Type& val) { val.inner = json.get<StructType>(); }},
            {"sum_type", [](const nlohmann::json& json, Type& val) { val.inner = json.get<SumType>(); }},
            {"function", [](const nlohmann::json& json, Type& val) { val.inner = json.get<FunctionType>(); }},
            {"array", [](const nlohmann::json& json, Type& val) { val.inner = json.get<ArrayType>(); }},
            {"view", [](const nlohmann::json& json, Type& val) { val.inner = json.get<ViewType>(); }},
            {"vector", [](const nlohmann::json& json, Type& val) { val.inner = json.get<VectorType>(); }},
            {"map", [](const nlohmann::json& json, Type& val) { val.inner = json.get<MapType>(); }},
            {"future", [](const nlohmann::json& json, Type& val) { val.inner = json.get<FutureType>(); }},
            {"ref", [](const nlohmann::json& json, Type& val) { val.inner = json.get<RefType>(); }},
            {"weak_ref", [](const nlohmann::json& json, Type& val) { val.inner = json.get<WeakRefType>(); }},
            {"sender", [](const nlohmann::json& json, Type& val) { val.inner = json.get<SenderType>(); }},
            {"receiver", [](const nlohmann::json& json, Type& val) { val.inner = json.get<ReceiverType>(); }},
        };
        auto it = compMap.find(kind);
        if (it != compMap.end()) {
            it->second(j, v);
            return;
        }
        throw std::runtime_error("Unknown composite type kind: " + kind);
    }
    
    throw std::runtime_error("Malformed type specification.");
}

} // namespace maml