// Code generated by tools/gen_runtime.go. DO NOT EDIT.
package types

const (
	SYM_ALLOC               = "maml_alloc"
	SYM_FREE                = "maml_free"
	SYM_RETAIN              = "maml_retain"
	SYM_RELEASE             = "maml_release"
	SYM_VEC_CREATE          = "maml_vec_create"
	SYM_VEC_PUSH            = "maml_vec_push"
	SYM_VEC_SET             = "maml_vec_set"
	SYM_VEC_GET             = "maml_vec_get"
	SYM_VEC_LEN             = "maml_vec_len"
	SYM_MAP_CREATE          = "maml_map_create"
	SYM_MAP_PUT             = "maml_map_put"
	SYM_MAP_GET             = "maml_map_get"
	SYM_MAP_DELETE          = "maml_map_delete"
	SYM_MAP_LEN             = "maml_map_len"
	SYM_STR_HASH            = "maml_str_hash"
	SYM_STR_EQ              = "maml_str_eq"
	SYM_CORO_RESUME_HELPER  = "maml_coro_resume_helper"
	SYM_CORO_DONE_HELPER    = "maml_coro_done_helper"
	SYM_CORO_DESTROY_HELPER = "maml_coro_destroy_helper"
	SYM_SPAWN_TASK          = "maml_spawn_task"
	SYM_RUN_EXECUTOR        = "maml_run_executor"
	SYM_PRINT               = "maml_print"
)

var RuntimeABI = map[string]*FunctionType{
	"maml_alloc": {
		Params: []Type{IntType{}},
		Return: AnyType{},
	},
	"maml_free": {
		Params: []Type{AnyType{}},
		Return: UnitType{},
	},
	"maml_retain": {
		Params: []Type{AnyType{}},
		Return: UnitType{},
	},
	"maml_release": {
		Params: []Type{AnyType{}},
		Return: UnitType{},
	},
	"maml_vec_create": {
		Params: []Type{IntType{}, AnyType{}, AnyType{}},
		Return: AnyType{},
	},
	"maml_vec_push": {
		Params: []Type{AnyType{}, AnyType{}},
		Return: UnitType{},
	},
	"maml_vec_set": {
		Params: []Type{AnyType{}, IntType{}, AnyType{}},
		Return: UnitType{},
	},
	"maml_vec_get": {
		Params: []Type{AnyType{}, IntType{}},
		Return: AnyType{},
	},
	"maml_vec_len": {
		Params: []Type{AnyType{}},
		Return: IntType{},
	},
	"maml_map_create": {
		Params: []Type{IntType{}, IntType{}, AnyType{}, AnyType{}, AnyType{}, AnyType{}},
		Return: AnyType{},
	},
	"maml_map_put": {
		Params: []Type{AnyType{}, IntType{}, AnyType{}, IntType{}, IntType{}, AnyType{}},
		Return: UnitType{},
	},
	"maml_map_get": {
		Params: []Type{AnyType{}, IntType{}, AnyType{}, IntType{}},
		Return: AnyType{},
	},
	"maml_map_delete": {
		Params: []Type{AnyType{}, IntType{}, AnyType{}, IntType{}, IntType{}},
		Return: UnitType{},
	},
	"maml_map_len": {
		Params: []Type{AnyType{}},
		Return: IntType{},
	},
	"maml_str_hash": {
		Params: []Type{AnyType{}, IntType{}},
		Return: IntType{},
	},
	"maml_str_eq": {
		Params: []Type{AnyType{}, IntType{}, AnyType{}, IntType{}},
		Return: IntType{},
	},
	"maml_coro_resume_helper": {
		Params: []Type{AnyType{}},
		Return: UnitType{},
	},
	"maml_coro_done_helper": {
		Params: []Type{AnyType{}},
		Return: BoolType{},
	},
	"maml_coro_destroy_helper": {
		Params: []Type{AnyType{}},
		Return: UnitType{},
	},
	"maml_spawn_task": {
		Params: []Type{AnyType{}},
		Return: UnitType{},
	},
	"maml_run_executor": {
		Params: []Type{},
		Return: UnitType{},
	},
	"maml_print": {
		Params: []Type{AnyType{}, IntType{}},
		Return: UnitType{},
	},
}
