// Code generated by gen_types.go. DO NOT EDIT.
package types

type Type interface {
	isType()
	IsReferenceType() bool
	IsNeedsARC() bool
	String() string
	Equals(Type) bool
}

// --- Primitives ---
type IntType struct{}

func (t IntType) isType()               {}
func (t IntType) IsReferenceType() bool { return false }
func (t IntType) IsNeedsARC() bool      { return false }
func (t IntType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(IntType)
	return ok
}

type BoolType struct{}

func (t BoolType) isType()               {}
func (t BoolType) IsReferenceType() bool { return false }
func (t BoolType) IsNeedsARC() bool      { return false }
func (t BoolType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(BoolType)
	return ok
}

type UnitType struct{}

func (t UnitType) isType()               {}
func (t UnitType) IsReferenceType() bool { return false }
func (t UnitType) IsNeedsARC() bool      { return false }
func (t UnitType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(UnitType)
	return ok
}

type StringType struct{}

func (t StringType) isType()               {}
func (t StringType) IsReferenceType() bool { return true }
func (t StringType) IsNeedsARC() bool      { return true }
func (t StringType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(StringType)
	return ok
}

type AnyType struct{}

func (t AnyType) isType()               {}
func (t AnyType) IsReferenceType() bool { return true }
func (t AnyType) IsNeedsARC() bool      { return false }
func (t AnyType) Equals(other Type) bool {
	return true
}

type UnknownType struct{}

func (t UnknownType) isType()               {}
func (t UnknownType) IsReferenceType() bool { return false }
func (t UnknownType) IsNeedsARC() bool      { return false }
func (t UnknownType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(UnknownType)
	return ok
}

type PtrType struct{}

func (t PtrType) isType()               {}
func (t PtrType) IsReferenceType() bool { return true }
func (t PtrType) IsNeedsARC() bool      { return false }
func (t PtrType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(PtrType)
	return ok
}

// --- Composites ---
type StructType struct {
	Name    string
	Fields  []StructField
	IsReprC bool
}

func (t *StructType) isType()               {}
func (t *StructType) IsReferenceType() bool { return false }
func (t *StructType) IsNeedsARC() bool {
	for _, f := range t.Fields {
		if f.Type != nil && f.Type.IsNeedsARC() {
			return true
		}
	}
	return false

}
func (t *StructType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*StructType)
	if !ok {
		return false
	}
	if t.Name != o.Name {
		return false
	}
	return true
}

type SumType struct {
	BaseName string
	Variants []SumVariant
	TypeArgs []Type
}

func (t *SumType) isType()               {}
func (t *SumType) IsReferenceType() bool { return false }
func (t *SumType) IsNeedsARC() bool {
	return false
}
func (t *SumType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*SumType)
	if !ok {
		return false
	}
	if t.BaseName != o.BaseName {
		return false
	}
	return true
}

// --- Containers ---
type ArrayType struct {
	Base Type
	Size int
}

func (t *ArrayType) isType()               {}
func (t *ArrayType) IsReferenceType() bool { return true }
func (t *ArrayType) IsNeedsARC() bool {
	return t.Base != nil && t.Base.IsNeedsARC()
}
func (t *ArrayType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*ArrayType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	if t.Size != o.Size {
		return false
	}
	return true
}

type ViewType struct {
	Base Type
}

func (t *ViewType) isType()               {}
func (t *ViewType) IsReferenceType() bool { return true }
func (t *ViewType) IsNeedsARC() bool {
	return false
}
func (t *ViewType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*ViewType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

type VectorType struct {
	Base Type
}

func (t *VectorType) isType()               {}
func (t *VectorType) IsReferenceType() bool { return true }
func (t *VectorType) IsNeedsARC() bool {
	return true
}
func (t *VectorType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*VectorType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

type MapType struct {
	Key   Type
	Value Type
}

func (t *MapType) isType()               {}
func (t *MapType) IsReferenceType() bool { return true }
func (t *MapType) IsNeedsARC() bool {
	return true
}
func (t *MapType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*MapType)
	if !ok {
		return false
	}
	if t.Key != nil && o.Key != nil {
		if !t.Key.Equals(o.Key) {
			return false
		}
	} else if t.Key != o.Key {
		return false
	}
	if t.Value != nil && o.Value != nil {
		if !t.Value.Equals(o.Value) {
			return false
		}
	} else if t.Value != o.Value {
		return false
	}
	return true
}

type FutureType struct {
	Base Type
}

func (t *FutureType) isType()               {}
func (t *FutureType) IsReferenceType() bool { return true }
func (t *FutureType) IsNeedsARC() bool {
	return true
}
func (t *FutureType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*FutureType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

// --- Helpers ---
type StructField struct {
	Name string
	Type Type
}
type SumVariant struct {
	Name         string
	Discriminant int
	TupleTypes   []Type
	Fields       []StructField
}
