// Code generated by gen_types.go. DO NOT EDIT.
package types

import (
	"fmt"
	"strings"
)

type Type interface {
	isType()
	String() string
	MangledName() string
	Equals(Type) bool
}

// ============================================================================
// Primitives
// ============================================================================
type I8Type struct{}

func (t I8Type) isType()             {}
func (t I8Type) String() string      { return "i8" }
func (t I8Type) MangledName() string { return "i8" }
func (t I8Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(I8Type)
	return ok
}

type I16Type struct{}

func (t I16Type) isType()             {}
func (t I16Type) String() string      { return "i16" }
func (t I16Type) MangledName() string { return "i16" }
func (t I16Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(I16Type)
	return ok
}

type I32Type struct{}

func (t I32Type) isType()             {}
func (t I32Type) String() string      { return "i32" }
func (t I32Type) MangledName() string { return "i32" }
func (t I32Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(I32Type)
	return ok
}

type I64Type struct{}

func (t I64Type) isType()             {}
func (t I64Type) String() string      { return "i64" }
func (t I64Type) MangledName() string { return "i64" }
func (t I64Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(I64Type)
	return ok
}

type I128Type struct{}

func (t I128Type) isType()             {}
func (t I128Type) String() string      { return "i128" }
func (t I128Type) MangledName() string { return "i128" }
func (t I128Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(I128Type)
	return ok
}

type U8Type struct{}

func (t U8Type) isType()             {}
func (t U8Type) String() string      { return "u8" }
func (t U8Type) MangledName() string { return "u8" }
func (t U8Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(U8Type)
	return ok
}

type U16Type struct{}

func (t U16Type) isType()             {}
func (t U16Type) String() string      { return "u16" }
func (t U16Type) MangledName() string { return "u16" }
func (t U16Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(U16Type)
	return ok
}

type U32Type struct{}

func (t U32Type) isType()             {}
func (t U32Type) String() string      { return "u32" }
func (t U32Type) MangledName() string { return "u32" }
func (t U32Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(U32Type)
	return ok
}

type U64Type struct{}

func (t U64Type) isType()             {}
func (t U64Type) String() string      { return "u64" }
func (t U64Type) MangledName() string { return "u64" }
func (t U64Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(U64Type)
	return ok
}

type U128Type struct{}

func (t U128Type) isType()             {}
func (t U128Type) String() string      { return "u128" }
func (t U128Type) MangledName() string { return "u128" }
func (t U128Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(U128Type)
	return ok
}

type F32Type struct{}

func (t F32Type) isType()             {}
func (t F32Type) String() string      { return "f32" }
func (t F32Type) MangledName() string { return "f32" }
func (t F32Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(F32Type)
	return ok
}

type F64Type struct{}

func (t F64Type) isType()             {}
func (t F64Type) String() string      { return "f64" }
func (t F64Type) MangledName() string { return "f64" }
func (t F64Type) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(F64Type)
	return ok
}

type BoolType struct{}

func (t BoolType) isType()             {}
func (t BoolType) String() string      { return "bool" }
func (t BoolType) MangledName() string { return "bool" }
func (t BoolType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(BoolType)
	return ok
}

type CharType struct{}

func (t CharType) isType()             {}
func (t CharType) String() string      { return "char" }
func (t CharType) MangledName() string { return "char" }
func (t CharType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(CharType)
	return ok
}

type UnitType struct{}

func (t UnitType) isType()             {}
func (t UnitType) String() string      { return "unit" }
func (t UnitType) MangledName() string { return "unit" }
func (t UnitType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(UnitType)
	return ok
}

type StringType struct{}

func (t StringType) isType()             {}
func (t StringType) String() string      { return "string" }
func (t StringType) MangledName() string { return "string" }
func (t StringType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(StringType)
	return ok
}

type AnyType struct{}

func (t AnyType) isType()             {}
func (t AnyType) String() string      { return "any" }
func (t AnyType) MangledName() string { return "any" }
func (t AnyType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(AnyType)
	return ok
}

type UnknownType struct{}

func (t UnknownType) isType()             {}
func (t UnknownType) String() string      { return "unknown" }
func (t UnknownType) MangledName() string { return "unknown" }
func (t UnknownType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(UnknownType)
	return ok
}

type PtrType struct{}

func (t PtrType) isType()             {}
func (t PtrType) String() string      { return "ptr" }
func (t PtrType) MangledName() string { return "ptr" }
func (t PtrType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	_, ok := other.(PtrType)
	return ok
}

// ============================================================================
// Composites
// ============================================================================
type StructType struct {
	Name    string
	Fields  []StructField
	IsReprC bool
}

func (t *StructType) isType() {}

type SumType struct {
	BaseName string
	Variants []SumVariant
	TypeArgs []Type
}

func (t *SumType) isType() {}

type FunctionType struct {
	Params     []Type
	Caps       []Cap
	ReturnType Type
}

func (t *FunctionType) isType() {}

// Custom Equality Overrides for Composites
func (t *StructType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*StructType)
	return ok && t.Name == o.Name
}
func (t *SumType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*SumType)
	return ok && t.BaseName == o.BaseName
}
func (t *FunctionType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*FunctionType)
	if !ok || len(t.Params) != len(o.Params) || !t.ReturnType.Equals(o.ReturnType) {
		return false
	}
	for i := range t.Params {
		if !t.Params[i].Equals(o.Params[i]) {
			return false
		}
	}
	return true
}

// Custom String Formatting for Composites
func (t *StructType) String() string      { return t.Name }
func (t *StructType) MangledName() string { return t.Name }
func (t *SumType) String() string {
	if len(t.TypeArgs) == 0 {
		return t.BaseName
	}
	args := make([]string, len(t.TypeArgs))
	for i, a := range t.TypeArgs {
		args[i] = a.String()
	}
	return fmt.Sprintf("%s<%s>", t.BaseName, strings.Join(args, ", "))
}
func (t *SumType) MangledName() string {
	if len(t.TypeArgs) == 0 {
		return t.BaseName
	}
	args := make([]string, len(t.TypeArgs))
	for i, a := range t.TypeArgs {
		args[i] = a.MangledName()
	}
	return fmt.Sprintf("%s_%s", t.BaseName, strings.Join(args, "_"))
}
func (t *FunctionType) String() string {
	var params []string
	for _, p := range t.Params {
		params = append(params, p.String())
	}
	return "fn(" + strings.Join(params, ", ") + ") " + t.ReturnType.String()
}
func (t *FunctionType) MangledName() string {
	params := make([]string, len(t.Params))
	for i, p := range t.Params {
		params[i] = p.MangledName()
	}
	return fmt.Sprintf("fn_%s_%s", strings.Join(params, "_"), t.ReturnType.MangledName())
}

// ============================================================================
// Containers
// ============================================================================
type ArrayType struct {
	Base Type
	Size int
}

func (t *ArrayType) isType() {}
func (t *ArrayType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*ArrayType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	if t.Size != o.Size {
		return false
	}
	return true
}

func (t *ArrayType) String() string {
	return fmt.Sprintf("[%d]%s", t.Size, t.Base.String())
}

func (t *ArrayType) MangledName() string {
	return fmt.Sprintf("array_%d_%s", t.Size, t.Base.MangledName())
}

type ViewType struct {
	Base  Type
	IsMut bool
}

func (t *ViewType) isType() {}
func (t *ViewType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*ViewType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	if t.IsMut != o.IsMut {
		return false
	}
	return true
}

func (t *ViewType) String() string {
	if t.IsMut {
		return fmt.Sprintf("[]%smut", t.Base.String())
	}
	return fmt.Sprintf("[]%s", t.Base.String())
}

func (t *ViewType) MangledName() string {
	if t.IsMut {
		return fmt.Sprintf("view_%s_mut", t.Base.MangledName())
	}
	return fmt.Sprintf("view_%s", t.Base.MangledName())
}

type VectorType struct {
	Base Type
}

func (t *VectorType) isType() {}
func (t *VectorType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*VectorType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

func (t *VectorType) String() string {
	return fmt.Sprintf("Vector<%s>", t.Base.String())
}

func (t *VectorType) MangledName() string {
	return fmt.Sprintf("Vector_%s", t.Base.MangledName())
}

type MapType struct {
	Key   Type
	Value Type
}

func (t *MapType) isType() {}
func (t *MapType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*MapType)
	if !ok {
		return false
	}
	if t.Key != nil && o.Key != nil {
		if !t.Key.Equals(o.Key) {
			return false
		}
	} else if t.Key != o.Key {
		return false
	}
	if t.Value != nil && o.Value != nil {
		if !t.Value.Equals(o.Value) {
			return false
		}
	} else if t.Value != o.Value {
		return false
	}
	return true
}

func (t *MapType) String() string {
	return fmt.Sprintf("Map<%s, %s>", t.Key.String(), t.Value.String())
}

func (t *MapType) MangledName() string {
	return fmt.Sprintf("Map_%s_%s", t.Key.MangledName(), t.Value.MangledName())
}

type FutureType struct {
	Base Type
}

func (t *FutureType) isType() {}
func (t *FutureType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*FutureType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

func (t *FutureType) String() string {
	return fmt.Sprintf("Future<%s>", t.Base.String())
}

func (t *FutureType) MangledName() string {
	return fmt.Sprintf("Future_%s", t.Base.MangledName())
}

type RefType struct {
	Base Type
}

func (t *RefType) isType() {}
func (t *RefType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*RefType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

func (t *RefType) String() string {
	return fmt.Sprintf("Ref<%s>", t.Base.String())
}

func (t *RefType) MangledName() string {
	return fmt.Sprintf("Ref_%s", t.Base.MangledName())
}

type WeakRefType struct {
	Base Type
}

func (t *WeakRefType) isType() {}
func (t *WeakRefType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*WeakRefType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

func (t *WeakRefType) String() string {
	return fmt.Sprintf("WeakRef<%s>", t.Base.String())
}

func (t *WeakRefType) MangledName() string {
	return fmt.Sprintf("WeakRef_%s", t.Base.MangledName())
}

type SenderType struct {
	Base Type
}

func (t *SenderType) isType() {}
func (t *SenderType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*SenderType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

func (t *SenderType) String() string {
	return fmt.Sprintf("Sender<%s>", t.Base.String())
}

func (t *SenderType) MangledName() string {
	return fmt.Sprintf("Sender_%s", t.Base.MangledName())
}

type ReceiverType struct {
	Base Type
}

func (t *ReceiverType) isType() {}
func (t *ReceiverType) Equals(other Type) bool {
	if _, ok := other.(AnyType); ok {
		return true
	}
	o, ok := other.(*ReceiverType)
	if !ok {
		return false
	}
	if t.Base != nil && o.Base != nil {
		if !t.Base.Equals(o.Base) {
			return false
		}
	} else if t.Base != o.Base {
		return false
	}
	return true
}

func (t *ReceiverType) String() string {
	return fmt.Sprintf("Receiver<%s>", t.Base.String())
}

func (t *ReceiverType) MangledName() string {
	return fmt.Sprintf("Receiver_%s", t.Base.MangledName())
}

// ============================================================================
// Helpers & Metadata Extractors
// ============================================================================
type StructField struct {
	Name string
	Type Type
}
type SumVariant struct {
	Name         string
	Discriminant int
	TupleTypes   []Type
	Fields       []StructField
}

func IsIntegerType(t Type) bool {
	switch t.(type) {
	case I8Type:
		return true
	case I16Type:
		return true
	case I32Type:
		return true
	case I64Type:
		return true
	case I128Type:
		return true
	case U8Type:
		return true
	case U16Type:
		return true
	case U32Type:
		return true
	case U64Type:
		return true
	case U128Type:
		return true
	default:
		return false
	}
}

func CanRepresentInt(value int64, t Type) bool {
	switch t.(type) {
	case I8Type:
		return value >= -128 && value <= 127
	case I16Type:
		return value >= -32768 && value <= 32767
	case I32Type:
		return value >= -2147483648 && value <= 2147483647
	case I64Type:
		return true
	case I128Type:
		return true
	case U8Type:
		return value >= 0 && value <= 255
	case U16Type:
		return value >= 0 && value <= 65535
	case U32Type:
		return value >= 0 && value <= 4294967295
	case U64Type:
		return value >= 0
	case U128Type:
		return value >= 0
	default:
		return false
	}
}
