//go:build ignore

package main

import (
	"bytes"
	_ "embed"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

//go:embed runtime_schema.yaml
var schemaData []byte

//go:embed runtime_go.tmpl
var goTemplateStr string

//go:embed runtime_cpp.tmpl
var cppTemplateStr string

//go:embed runtime_zig.tmpl
var zigTemplateStr string

type TypeAlias struct {
	Alias   string `yaml:"alias"`
	GoType  string `yaml:"go_type"`
	CppType string `yaml:"cpp_type"`
	ZigType string `yaml:"zig_type"`
}

type FunctionDef struct {
	Symbol string   `yaml:"symbol"`
	Args   []string `yaml:"args"`
	Return string   `yaml:"return"`
}

type Schema struct {
	Types     []TypeAlias   `yaml:"types"`
	Functions []FunctionDef `yaml:"functions"`
}

type TemplateContext struct {
	Functions []FunctionContext
}

type FunctionContext struct {
	Symbol    string
	ConstName string
	ReturnGo  string
	ReturnCpp string
	ReturnZig string
	ArgsGo    []string
	ArgsCpp   []string
	ArgsZig   []string
}

func main() {
	goOut := flag.String("goOut", "frontend/types/", "output directory for runtime_generated.go")
	cppOut := flag.String("cppOut", "backend/include/", "output directory for autogen_runtime.inc")
	zigOut := flag.String("zigOut", "runtime/src/", "output directory for abi_assertions.zig")
	flag.Parse()

	var schema Schema
	if err := yaml.Unmarshal(schemaData, &schema); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to parse YAML: %v\n", err)
		os.Exit(1)
	}

	typeMap := make(map[string]TypeAlias)
	for _, t := range schema.Types {
		typeMap[t.Alias] = t
	}

	ctx := buildContext(schema, typeMap)

	// 1. Generate Go
	executeTemplate("Go Frontend", goTemplateStr, path.Join(*goOut, "runtime_generated.go"), ctx, true)

	// 2. Generate C++
	executeTemplate("C++ Backend (.inc)", cppTemplateStr, path.Join(*cppOut, "autogen_runtime.inc"), ctx, false)
	generateCppConstants(ctx, path.Join(*cppOut, "RuntimeConstants.h"))

	// 3. Generate Zig
	executeTemplate("Zig Assertions", zigTemplateStr, path.Join(*zigOut, "abi_assertions.zig"), ctx, false)

	fmt.Println("✅ Successfully generated unified Runtime ABI via templates.")
}

func buildContext(schema Schema, tm map[string]TypeAlias) TemplateContext {
	var ctx TemplateContext
	for _, fn := range schema.Functions {
		fCtx := FunctionContext{
			Symbol:    fn.Symbol,
			ConstName: "SYM_" + strings.ToUpper(strings.ReplaceAll(fn.Symbol, "maml_", "")),
			ReturnGo:  tm[fn.Return].GoType,
			ReturnCpp: tm[fn.Return].CppType,
			ReturnZig: tm[fn.Return].ZigType,
		}
		for _, arg := range fn.Args {
			fCtx.ArgsGo = append(fCtx.ArgsGo, tm[arg].GoType)
			fCtx.ArgsCpp = append(fCtx.ArgsCpp, tm[arg].CppType)
			fCtx.ArgsZig = append(fCtx.ArgsZig, tm[arg].ZigType)
		}
		ctx.Functions = append(ctx.Functions, fCtx)
	}
	return ctx
}

func executeTemplate(name, tmplStr, outPath string, data TemplateContext, formatGo bool) {
	tmpl := template.Must(template.New(name).Funcs(template.FuncMap{
		"join": strings.Join,
	}).Parse(tmplStr))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		fmt.Fprintf(os.Stderr, "Template Execution Error (%s): %v\n", name, err)
		os.Exit(1)
	}

	outData := buf.Bytes()
	if formatGo {
		formatted, err := format.Source(outData)
		if err != nil {
			os.WriteFile(outPath+".debug", outData, 0644)
			fmt.Fprintf(os.Stderr, "Go Format Error: %v\n", err)
			os.Exit(1)
		}
		outData = formatted
	}

	os.MkdirAll(filepath.Dir(outPath), 0755)
	if err := os.WriteFile(outPath, outData, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Write Error (%s): %v\n", name, err)
		os.Exit(1)
	}
}

func generateCppConstants(ctx TemplateContext, outPath string) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/gen_runtime.go. DO NOT EDIT.\n")
	buf.WriteString("#pragma once\n\nnamespace maml {\nnamespace rt {\n\n")
	for _, fn := range ctx.Functions {
		buf.WriteString(fmt.Sprintf("constexpr const char* %s = \"%s\";\n", strings.ToUpper(strings.ReplaceAll(fn.Symbol, "maml_", "")), fn.Symbol))
	}
	buf.WriteString("\n} // namespace rt\n} // namespace maml\n")
	os.WriteFile(outPath, buf.Bytes(), 0644)
}
