// Code generated by tools/gen_spec.go. DO NOT EDIT.
package mir

import (
	"github.com/mattcarp12/maml/frontend/types"
)

// ============================================================================
// Data Layout Constants (For AST/MIR Type Checking)
// ============================================================================
const (
	STRING_SIZE            = 16
	STRING_ALIGN           = 8
	STRING_PTR_OFFSET      = 0
	STRING_LEN_OFFSET      = 8
	STRING_IS_OWNED_OFFSET = 12
)
const (
	VECTOR_SIZE             = 24
	VECTOR_ALIGN            = 8
	VECTOR_BUFFER_OFFSET    = 0
	VECTOR_CAP_OFFSET       = 8
	VECTOR_LEN_OFFSET       = 12
	VECTOR_ELEM_SIZE_OFFSET = 16
)
const (
	VIEW_SIZE            = 16
	VIEW_ALIGN           = 8
	VIEW_DATA_PTR_OFFSET = 0
	VIEW_LEN_OFFSET      = 8
)
const (
	MAP_SIZE                   = 32
	MAP_ALIGN                  = 8
	MAP_ENTRIES_OFFSET         = 0
	MAP_COUNT_OFFSET           = 8
	MAP_TOMBSTONE_COUNT_OFFSET = 12
	MAP_CAP_OFFSET             = 16
	MAP_VAL_SIZE_OFFSET        = 20
	MAP_IS_STRING_KEY_OFFSET   = 24
)
const (
	REF_SIZE            = 16
	REF_ALIGN           = 8
	REF_PTR_OFFSET      = 0
	REF_REFCOUNT_OFFSET = 8
)

// ============================================================================
// Runtime Function Symbols
// ============================================================================
const (
	SYM_ALLOC               = "maml_alloc"
	SYM_FREE                = "maml_free"
	SYM_REALLOC             = "maml_realloc"
	SYM_CALLOC              = "maml_calloc"
	SYM_VEC_PUSH            = "maml_vec_push"
	SYM_VEC_GET             = "maml_vec_get"
	SYM_VEC_SET             = "maml_vec_set"
	SYM_VEC_LEN             = "maml_vec_len"
	SYM_VEC_CLONE           = "maml_vec_clone"
	SYM_VEC_FREE            = "maml_vec_free"
	SYM_MAP_PUT             = "maml_map_put"
	SYM_MAP_GET             = "maml_map_get"
	SYM_MAP_DELETE          = "maml_map_delete"
	SYM_MAP_LEN             = "maml_map_len"
	SYM_MAP_CLONE           = "maml_map_clone"
	SYM_MAP_FREE            = "maml_map_free"
	SYM_STR_HASH            = "maml_str_hash"
	SYM_STR_EQ              = "maml_str_eq"
	SYM_STR_CLONE           = "maml_str_clone"
	SYM_STR_LEN             = "maml_str_len"
	SYM_CORO_RUNTIME_INIT   = "maml_coro_runtime_init"
	SYM_CORO_RESUME_HELPER  = "maml_coro_resume_helper"
	SYM_CORO_DONE_HELPER    = "maml_coro_done_helper"
	SYM_CORO_DESTROY_HELPER = "maml_coro_destroy_helper"
	SYM_SPAWN_TASK          = "maml_spawn_task"
	SYM_RUN_EXECUTOR        = "maml_run_executor"
	SYM_TASK_AWAIT          = "maml_task_await"
	SYM_TASK_RELEASE        = "maml_task_release"
	SYM_YIELD_NOW           = "maml_yield_now"
	SYM_PRINT               = "maml_print"
	SYM_FILE_OPEN           = "maml_file_open"
	SYM_FILE_CLOSE          = "maml_file_close"
	SYM_FILE_READ_STR       = "maml_file_read_str"
	SYM_FILE_WRITE_STR      = "maml_file_write_str"
	SYM_SOCKET              = "maml_socket"
	SYM_BIND                = "maml_bind"
	SYM_LISTEN              = "maml_listen"
	SYM_ACCEPT              = "maml_accept"
	SYM_SOCKET_READ         = "maml_socket_read"
)

// ============================================================================
// Runtime Function Emitters
// ============================================================================

// EmitMamlAlloc constructs a MIR call to the runtime function maml_alloc.
func (b *Builder) EmitMamlAlloc(size Value) Value {
	return b.emitRuntimeCall(SYM_ALLOC, types.PtrType{}, size)
}

// EmitMamlFree constructs a MIR call to the runtime function maml_free.
func (b *Builder) EmitMamlFree(ptr Value) Value {
	return b.emitRuntimeCall(SYM_FREE, types.UnitType{}, ptr)
}

// EmitMamlRealloc constructs a MIR call to the runtime function maml_realloc.
func (b *Builder) EmitMamlRealloc(ptr Value, size Value) Value {
	return b.emitRuntimeCall(SYM_REALLOC, types.PtrType{}, ptr, size)
}

// EmitMamlCalloc constructs a MIR call to the runtime function maml_calloc.
func (b *Builder) EmitMamlCalloc(nmemb Value, size Value) Value {
	return b.emitRuntimeCall(SYM_CALLOC, types.PtrType{}, nmemb, size)
}

// EmitMamlVecPush constructs a MIR call to the runtime function maml_vec_push.
func (b *Builder) EmitMamlVecPush(vec Value, element Value) Value {
	return b.emitRuntimeCall(SYM_VEC_PUSH, types.UnitType{}, vec, element)
}

// EmitMamlVecGet constructs a MIR call to the runtime function maml_vec_get.
func (b *Builder) EmitMamlVecGet(vec Value, index Value) Value {
	return b.emitRuntimeCall(SYM_VEC_GET, types.PtrType{}, vec, index)
}

// EmitMamlVecSet constructs a MIR call to the runtime function maml_vec_set.
func (b *Builder) EmitMamlVecSet(vec Value, index Value, element Value) Value {
	return b.emitRuntimeCall(SYM_VEC_SET, types.UnitType{}, vec, index, element)
}

// EmitMamlVecLen constructs a MIR call to the runtime function maml_vec_len.
func (b *Builder) EmitMamlVecLen(vec Value) Value {
	return b.emitRuntimeCall(SYM_VEC_LEN, types.U32Type{}, vec)
}

// EmitMamlVecClone constructs a MIR call to the runtime function maml_vec_clone.
func (b *Builder) EmitMamlVecClone(vec Value) Value {
	return b.emitRuntimeCall(SYM_VEC_CLONE, &types.VectorType{}, vec)
}

// EmitMamlVecFree constructs a MIR call to the runtime function maml_vec_free.
func (b *Builder) EmitMamlVecFree(vec Value) Value {
	return b.emitRuntimeCall(SYM_VEC_FREE, types.UnitType{}, vec)
}

// EmitMamlMapPut constructs a MIR call to the runtime function maml_map_put.
func (b *Builder) EmitMamlMapPut(m Value, key_hash Value, key_ptr Value, key_len Value, val_ptr Value) Value {
	return b.emitRuntimeCall(SYM_MAP_PUT, types.UnitType{}, m, key_hash, key_ptr, key_len, val_ptr)
}

// EmitMamlMapGet constructs a MIR call to the runtime function maml_map_get.
func (b *Builder) EmitMamlMapGet(m Value, key_hash Value, key_ptr Value, key_len Value) Value {
	return b.emitRuntimeCall(SYM_MAP_GET, types.PtrType{}, m, key_hash, key_ptr, key_len)
}

// EmitMamlMapDelete constructs a MIR call to the runtime function maml_map_delete.
func (b *Builder) EmitMamlMapDelete(m Value, key_hash Value, key_ptr Value, key_len Value) Value {
	return b.emitRuntimeCall(SYM_MAP_DELETE, types.UnitType{}, m, key_hash, key_ptr, key_len)
}

// EmitMamlMapLen constructs a MIR call to the runtime function maml_map_len.
func (b *Builder) EmitMamlMapLen(m Value) Value {
	return b.emitRuntimeCall(SYM_MAP_LEN, types.U32Type{}, m)
}

// EmitMamlMapClone constructs a MIR call to the runtime function maml_map_clone.
func (b *Builder) EmitMamlMapClone(m Value) Value {
	return b.emitRuntimeCall(SYM_MAP_CLONE, &types.MapType{}, m)
}

// EmitMamlMapFree constructs a MIR call to the runtime function maml_map_free.
func (b *Builder) EmitMamlMapFree(m Value) Value {
	return b.emitRuntimeCall(SYM_MAP_FREE, types.UnitType{}, m)
}

// EmitMamlStrHash constructs a MIR call to the runtime function maml_str_hash.
func (b *Builder) EmitMamlStrHash(str_ptr Value, len Value) Value {
	return b.emitRuntimeCall(SYM_STR_HASH, types.U32Type{}, str_ptr, len)
}

// EmitMamlStrEq constructs a MIR call to the runtime function maml_str_eq.
func (b *Builder) EmitMamlStrEq(a_ptr Value, a_len Value, b_ptr Value, b_len Value) Value {
	return b.emitRuntimeCall(SYM_STR_EQ, types.I32Type{}, a_ptr, a_len, b_ptr, b_len)
}

// EmitMamlStrClone constructs a MIR call to the runtime function maml_str_clone.
func (b *Builder) EmitMamlStrClone(str_ptr Value, len Value) Value {
	return b.emitRuntimeCall(SYM_STR_CLONE, types.PtrType{}, str_ptr, len)
}

// EmitMamlStrLen constructs a MIR call to the runtime function maml_str_len.
func (b *Builder) EmitMamlStrLen(str Value) Value {
	return b.emitRuntimeCall(SYM_STR_LEN, types.U32Type{}, str)
}

// EmitMamlCoroRuntimeInit constructs a MIR call to the runtime function maml_coro_runtime_init.
func (b *Builder) EmitMamlCoroRuntimeInit() Value {
	return b.emitRuntimeCall(SYM_CORO_RUNTIME_INIT, types.UnitType{})
}

// EmitMamlCoroResumeHelper constructs a MIR call to the runtime function maml_coro_resume_helper.
func (b *Builder) EmitMamlCoroResumeHelper(task Value) Value {
	return b.emitRuntimeCall(SYM_CORO_RESUME_HELPER, types.UnitType{}, task)
}

// EmitMamlCoroDoneHelper constructs a MIR call to the runtime function maml_coro_done_helper.
func (b *Builder) EmitMamlCoroDoneHelper(task Value) Value {
	return b.emitRuntimeCall(SYM_CORO_DONE_HELPER, types.BoolType{}, task)
}

// EmitMamlCoroDestroyHelper constructs a MIR call to the runtime function maml_coro_destroy_helper.
func (b *Builder) EmitMamlCoroDestroyHelper(task Value) Value {
	return b.emitRuntimeCall(SYM_CORO_DESTROY_HELPER, types.UnitType{}, task)
}

// EmitMamlSpawnTask constructs a MIR call to the runtime function maml_spawn_task.
func (b *Builder) EmitMamlSpawnTask(task Value) Value {
	return b.emitRuntimeCall(SYM_SPAWN_TASK, types.UnitType{}, task)
}

// EmitMamlRunExecutor constructs a MIR call to the runtime function maml_run_executor.
func (b *Builder) EmitMamlRunExecutor(task Value) Value {
	return b.emitRuntimeCall(SYM_RUN_EXECUTOR, types.PtrType{}, task)
}

// EmitMamlTaskAwait constructs a MIR call to the runtime function maml_task_await.
func (b *Builder) EmitMamlTaskAwait(current_task Value, target_task Value) Value {
	return b.emitRuntimeCall(SYM_TASK_AWAIT, types.UnitType{}, current_task, target_task)
}

// EmitMamlTaskRelease constructs a MIR call to the runtime function maml_task_release.
func (b *Builder) EmitMamlTaskRelease(task Value) Value {
	return b.emitRuntimeCall(SYM_TASK_RELEASE, types.UnitType{}, task)
}

// EmitMamlYieldNow constructs a MIR call to the runtime function maml_yield_now.
func (b *Builder) EmitMamlYieldNow(task Value) Value {
	return b.emitRuntimeCall(SYM_YIELD_NOW, types.UnitType{}, task)
}

// EmitMamlPrint constructs a MIR call to the runtime function maml_print.
func (b *Builder) EmitMamlPrint(msg Value) Value {
	return b.emitRuntimeCall(SYM_PRINT, types.UnitType{}, msg)
}

// EmitMamlFileOpen constructs a MIR call to the runtime function maml_file_open.
func (b *Builder) EmitMamlFileOpen(filename Value) Value {
	return b.emitRuntimeCall(SYM_FILE_OPEN, types.I32Type{}, filename)
}

// EmitMamlFileClose constructs a MIR call to the runtime function maml_file_close.
func (b *Builder) EmitMamlFileClose(fd Value) Value {
	return b.emitRuntimeCall(SYM_FILE_CLOSE, types.UnitType{}, fd)
}

// EmitMamlFileReadStr constructs a MIR call to the runtime function maml_file_read_str.
func (b *Builder) EmitMamlFileReadStr(fd Value) Value {
	return b.emitRuntimeCall(SYM_FILE_READ_STR, &types.StringType{}, fd)
}

// EmitMamlFileWriteStr constructs a MIR call to the runtime function maml_file_write_str.
func (b *Builder) EmitMamlFileWriteStr(fd Value, msg Value) Value {
	return b.emitRuntimeCall(SYM_FILE_WRITE_STR, types.UnitType{}, fd, msg)
}

// EmitMamlSocket constructs a MIR call to the runtime function maml_socket.
func (b *Builder) EmitMamlSocket(domain Value, typ Value, protocol Value) Value {
	return b.emitRuntimeCall(SYM_SOCKET, types.I32Type{}, domain, typ, protocol)
}

// EmitMamlBind constructs a MIR call to the runtime function maml_bind.
func (b *Builder) EmitMamlBind(fd Value, port Value) Value {
	return b.emitRuntimeCall(SYM_BIND, types.I32Type{}, fd, port)
}

// EmitMamlListen constructs a MIR call to the runtime function maml_listen.
func (b *Builder) EmitMamlListen(fd Value, backlog Value) Value {
	return b.emitRuntimeCall(SYM_LISTEN, types.I32Type{}, fd, backlog)
}

// EmitMamlAccept constructs a MIR call to the runtime function maml_accept.
func (b *Builder) EmitMamlAccept(fd Value) Value {
	return b.emitRuntimeCall(SYM_ACCEPT, types.I32Type{}, fd)
}

// EmitMamlSocketRead constructs a MIR call to the runtime function maml_socket_read.
func (b *Builder) EmitMamlSocketRead(fd Value, max_bytes Value) Value {
	return b.emitRuntimeCall(SYM_SOCKET_READ, &types.StringType{}, fd, max_bytes)
}
