// Code generated by tools/gen_spec.go. DO NOT EDIT.
package mir

import (
	"github.com/mattcarp12/maml/frontend/types"
)

// ============================================================================
// Data Layout Constants (For AST/MIR Type Checking)
// ============================================================================
const (
	STRING_SIZE            = 16
	STRING_ALIGN           = 8
	STRING_PTR_OFFSET      = 0
	STRING_LEN_OFFSET      = 8
	STRING_IS_OWNED_OFFSET = 12
)
const (
	VECTOR_SIZE             = 24
	VECTOR_ALIGN            = 8
	VECTOR_BUFFER_OFFSET    = 0
	VECTOR_CAP_OFFSET       = 8
	VECTOR_LEN_OFFSET       = 12
	VECTOR_ELEM_SIZE_OFFSET = 16
)
const (
	VIEW_SIZE            = 16
	VIEW_ALIGN           = 8
	VIEW_DATA_PTR_OFFSET = 0
	VIEW_LEN_OFFSET      = 8
)
const (
	MAP_SIZE                   = 32
	MAP_ALIGN                  = 8
	MAP_ENTRIES_OFFSET         = 0
	MAP_COUNT_OFFSET           = 8
	MAP_TOMBSTONE_COUNT_OFFSET = 12
	MAP_CAP_OFFSET             = 16
	MAP_VAL_SIZE_OFFSET        = 20
	MAP_IS_STRING_KEY_OFFSET   = 24
)
const (
	FUTURE_SIZE         = 16
	FUTURE_ALIGN        = 8
	FUTURE_STATE_OFFSET = 0
	FUTURE_READY_OFFSET = 8
)
const (
	REF_SIZE            = 16
	REF_ALIGN           = 8
	REF_PTR_OFFSET      = 0
	REF_REFCOUNT_OFFSET = 8
)

// ============================================================================
// Runtime Function Symbols
// ============================================================================
const (
	SYM_ALLOC               = "maml_alloc"
	SYM_FREE                = "maml_free"
	SYM_VEC_GROW            = "maml_vec_grow"
	SYM_VEC_CREATE          = "maml_vec_create"
	SYM_VEC_PUSH            = "maml_vec_push"
	SYM_VEC_GET             = "maml_vec_get"
	SYM_VEC_SET             = "maml_vec_set"
	SYM_VEC_LEN             = "maml_vec_len"
	SYM_VEC_CLONE           = "maml_vec_clone"
	SYM_VEC_FREE            = "maml_vec_free"
	SYM_MAP_CREATE          = "maml_map_create"
	SYM_MAP_PUT             = "maml_map_put"
	SYM_MAP_GET             = "maml_map_get"
	SYM_MAP_DELETE          = "maml_map_delete"
	SYM_MAP_LEN             = "maml_map_len"
	SYM_MAP_CLONE           = "maml_map_clone"
	SYM_MAP_FREE            = "maml_map_free"
	SYM_STR_HASH            = "maml_str_hash"
	SYM_STR_EQ              = "maml_str_eq"
	SYM_STR_CLONE           = "maml_str_clone"
	SYM_CORO_RUNTIME_INIT   = "maml_coro_runtime_init"
	SYM_CORO_RESUME_HELPER  = "maml_coro_resume_helper"
	SYM_CORO_DONE_HELPER    = "maml_coro_done_helper"
	SYM_CORO_DESTROY_HELPER = "maml_coro_destroy_helper"
	SYM_SPAWN_TASK          = "maml_spawn_task"
	SYM_RUN_EXECUTOR        = "maml_run_executor"
	SYM_TASK_AWAIT          = "maml_task_await"
	SYM_TASK_RELEASE        = "maml_task_release"
	SYM_TASK_GET_RESULT     = "maml_task_get_result"
	SYM_YIELD_NOW           = "maml_yield_now"
	SYM_PRINT               = "maml_print"
)

// ============================================================================
// Runtime Function Typing
// ============================================================================
var RuntimeABI = map[string]*types.FunctionType{
	"maml_alloc": {
		Params: []types.Type{
			types.U64Type{},
		},
		Return: types.PtrType{},
	},
	"maml_free": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_vec_grow": {
		Params: []types.Type{
			types.PtrType{},
			types.PtrType{},
			types.U32Type{},
		},
		Return: types.PtrType{},
	},
	"maml_vec_create": {
		Params: []types.Type{
			types.U32Type{},
		},
		Return: types.PtrType{},
	},
	"maml_vec_push": {
		Params: []types.Type{
			types.PtrType{},
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_vec_get": {
		Params: []types.Type{
			types.PtrType{},
			types.U32Type{},
		},
		Return: types.PtrType{},
	},
	"maml_vec_set": {
		Params: []types.Type{
			types.PtrType{},
			types.U32Type{},
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_vec_len": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.U32Type{},
	},
	"maml_vec_clone": {
		Params: []types.Type{
			types.PtrType{},
			types.U64Type{},
		},
		Return: types.PtrType{},
	},
	"maml_vec_free": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_map_create": {
		Params: []types.Type{
			types.U32Type{},
			types.BoolType{},
		},
		Return: types.PtrType{},
	},
	"maml_map_put": {
		Params: []types.Type{
			types.PtrType{},
			types.U32Type{},
			types.PtrType{},
			types.U32Type{},
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_map_get": {
		Params: []types.Type{
			types.PtrType{},
			types.U32Type{},
			types.PtrType{},
			types.U32Type{},
		},
		Return: types.PtrType{},
	},
	"maml_map_delete": {
		Params: []types.Type{
			types.PtrType{},
			types.U32Type{},
			types.PtrType{},
			types.U32Type{},
		},
		Return: types.UnitType{},
	},
	"maml_map_len": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.U32Type{},
	},
	"maml_map_clone": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.PtrType{},
	},
	"maml_map_free": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_str_hash": {
		Params: []types.Type{
			types.PtrType{},
			types.U32Type{},
		},
		Return: types.U32Type{},
	},
	"maml_str_eq": {
		Params: []types.Type{
			types.PtrType{},
			types.U32Type{},
			types.PtrType{},
			types.U32Type{},
		},
		Return: types.I32Type{},
	},
	"maml_str_clone": {
		Params: []types.Type{
			types.PtrType{},
			types.U32Type{},
		},
		Return: types.PtrType{},
	},
	"maml_coro_runtime_init": {
		Params: []types.Type{},
		Return: types.UnitType{},
	},
	"maml_coro_resume_helper": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_coro_done_helper": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.BoolType{},
	},
	"maml_coro_destroy_helper": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_spawn_task": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_run_executor": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.PtrType{},
	},
	"maml_task_await": {
		Params: []types.Type{
			types.PtrType{},
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_task_release": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_task_get_result": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_yield_now": {
		Params: []types.Type{
			types.PtrType{},
		},
		Return: types.UnitType{},
	},
	"maml_print": {
		Params: []types.Type{
			types.PtrType{},
			types.I32Type{},
		},
		Return: types.UnitType{},
	},
}

// ============================================================================
// Runtime Function Emitters
// ============================================================================

// EmitMamlAlloc constructs a MIR call to the runtime function maml_alloc.
func (b *Builder) EmitMamlAlloc(size Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_ALLOC, Type: types.UnknownType{}},
		Arguments: []Value{
			size,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlFree constructs a MIR call to the runtime function maml_free.
func (b *Builder) EmitMamlFree(ptr Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_FREE, Type: types.UnknownType{}},
		Arguments: []Value{
			ptr,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlVecGrow constructs a MIR call to the runtime function maml_vec_grow.
func (b *Builder) EmitMamlVecGrow(buffer Value, cap Value, elem_size Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_VEC_GROW, Type: types.UnknownType{}},
		Arguments: []Value{
			buffer,
			cap,
			elem_size,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlVecCreate constructs a MIR call to the runtime function maml_vec_create.
func (b *Builder) EmitMamlVecCreate(elem_size Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_VEC_CREATE, Type: types.UnknownType{}},
		Arguments: []Value{
			elem_size,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlVecPush constructs a MIR call to the runtime function maml_vec_push.
func (b *Builder) EmitMamlVecPush(vec Value, element Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_VEC_PUSH, Type: types.UnknownType{}},
		Arguments: []Value{
			vec,
			element,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlVecGet constructs a MIR call to the runtime function maml_vec_get.
func (b *Builder) EmitMamlVecGet(vec Value, index Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_VEC_GET, Type: types.UnknownType{}},
		Arguments: []Value{
			vec,
			index,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlVecSet constructs a MIR call to the runtime function maml_vec_set.
func (b *Builder) EmitMamlVecSet(vec Value, index Value, element Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_VEC_SET, Type: types.UnknownType{}},
		Arguments: []Value{
			vec,
			index,
			element,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlVecLen constructs a MIR call to the runtime function maml_vec_len.
func (b *Builder) EmitMamlVecLen(vec Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.U32Type{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_VEC_LEN, Type: types.UnknownType{}},
		Arguments: []Value{
			vec,
		},
		Type: types.U32Type{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.U32Type{}}
}

// EmitMamlVecClone constructs a MIR call to the runtime function maml_vec_clone.
func (b *Builder) EmitMamlVecClone(vec Value, elem_size Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_VEC_CLONE, Type: types.UnknownType{}},
		Arguments: []Value{
			vec,
			elem_size,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlVecFree constructs a MIR call to the runtime function maml_vec_free.
func (b *Builder) EmitMamlVecFree(vec Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_VEC_FREE, Type: types.UnknownType{}},
		Arguments: []Value{
			vec,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlMapCreate constructs a MIR call to the runtime function maml_map_create.
func (b *Builder) EmitMamlMapCreate(val_size Value, is_string_key Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_MAP_CREATE, Type: types.UnknownType{}},
		Arguments: []Value{
			val_size,
			is_string_key,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlMapPut constructs a MIR call to the runtime function maml_map_put.
func (b *Builder) EmitMamlMapPut(m Value, key_hash Value, key_ptr Value, key_len Value, val_ptr Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_MAP_PUT, Type: types.UnknownType{}},
		Arguments: []Value{
			m,
			key_hash,
			key_ptr,
			key_len,
			val_ptr,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlMapGet constructs a MIR call to the runtime function maml_map_get.
func (b *Builder) EmitMamlMapGet(m Value, key_hash Value, key_ptr Value, key_len Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_MAP_GET, Type: types.UnknownType{}},
		Arguments: []Value{
			m,
			key_hash,
			key_ptr,
			key_len,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlMapDelete constructs a MIR call to the runtime function maml_map_delete.
func (b *Builder) EmitMamlMapDelete(m Value, key_hash Value, key_ptr Value, key_len Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_MAP_DELETE, Type: types.UnknownType{}},
		Arguments: []Value{
			m,
			key_hash,
			key_ptr,
			key_len,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlMapLen constructs a MIR call to the runtime function maml_map_len.
func (b *Builder) EmitMamlMapLen(m Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.U32Type{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_MAP_LEN, Type: types.UnknownType{}},
		Arguments: []Value{
			m,
		},
		Type: types.U32Type{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.U32Type{}}
}

// EmitMamlMapClone constructs a MIR call to the runtime function maml_map_clone.
func (b *Builder) EmitMamlMapClone(m Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_MAP_CLONE, Type: types.UnknownType{}},
		Arguments: []Value{
			m,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlMapFree constructs a MIR call to the runtime function maml_map_free.
func (b *Builder) EmitMamlMapFree(m Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_MAP_FREE, Type: types.UnknownType{}},
		Arguments: []Value{
			m,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlStrHash constructs a MIR call to the runtime function maml_str_hash.
func (b *Builder) EmitMamlStrHash(str_ptr Value, len Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.U32Type{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_STR_HASH, Type: types.UnknownType{}},
		Arguments: []Value{
			str_ptr,
			len,
		},
		Type: types.U32Type{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.U32Type{}}
}

// EmitMamlStrEq constructs a MIR call to the runtime function maml_str_eq.
func (b *Builder) EmitMamlStrEq(a_ptr Value, a_len Value, b_ptr Value, b_len Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.I32Type{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_STR_EQ, Type: types.UnknownType{}},
		Arguments: []Value{
			a_ptr,
			a_len,
			b_ptr,
			b_len,
		},
		Type: types.I32Type{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.I32Type{}}
}

// EmitMamlStrClone constructs a MIR call to the runtime function maml_str_clone.
func (b *Builder) EmitMamlStrClone(str_ptr Value, len Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_STR_CLONE, Type: types.UnknownType{}},
		Arguments: []Value{
			str_ptr,
			len,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlCoroRuntimeInit constructs a MIR call to the runtime function maml_coro_runtime_init.
func (b *Builder) EmitMamlCoroRuntimeInit() Value {
	dst := ""

	call := &CallInst{
		Dst:       dst,
		Function:  &Register{Name: SYM_CORO_RUNTIME_INIT, Type: types.UnknownType{}},
		Arguments: []Value{},
		Type:      types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlCoroResumeHelper constructs a MIR call to the runtime function maml_coro_resume_helper.
func (b *Builder) EmitMamlCoroResumeHelper(task Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_CORO_RESUME_HELPER, Type: types.UnknownType{}},
		Arguments: []Value{
			task,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlCoroDoneHelper constructs a MIR call to the runtime function maml_coro_done_helper.
func (b *Builder) EmitMamlCoroDoneHelper(task Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.BoolType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_CORO_DONE_HELPER, Type: types.UnknownType{}},
		Arguments: []Value{
			task,
		},
		Type: types.BoolType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.BoolType{}}
}

// EmitMamlCoroDestroyHelper constructs a MIR call to the runtime function maml_coro_destroy_helper.
func (b *Builder) EmitMamlCoroDestroyHelper(task Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_CORO_DESTROY_HELPER, Type: types.UnknownType{}},
		Arguments: []Value{
			task,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlSpawnTask constructs a MIR call to the runtime function maml_spawn_task.
func (b *Builder) EmitMamlSpawnTask(task Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_SPAWN_TASK, Type: types.UnknownType{}},
		Arguments: []Value{
			task,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlRunExecutor constructs a MIR call to the runtime function maml_run_executor.
func (b *Builder) EmitMamlRunExecutor(task Value) Value {
	// Create destination temp for return value
	dst := b.newTemp()
	b.locals[dst] = types.PtrType{}

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_RUN_EXECUTOR, Type: types.UnknownType{}},
		Arguments: []Value{
			task,
		},
		Type: types.PtrType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}
}

// EmitMamlTaskAwait constructs a MIR call to the runtime function maml_task_await.
func (b *Builder) EmitMamlTaskAwait(current_task Value, target_task Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_TASK_AWAIT, Type: types.UnknownType{}},
		Arguments: []Value{
			current_task,
			target_task,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlTaskRelease constructs a MIR call to the runtime function maml_task_release.
func (b *Builder) EmitMamlTaskRelease(task Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_TASK_RELEASE, Type: types.UnknownType{}},
		Arguments: []Value{
			task,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlTaskGetResult constructs a MIR call to the runtime function maml_task_get_result.
func (b *Builder) EmitMamlTaskGetResult(task Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_TASK_GET_RESULT, Type: types.UnknownType{}},
		Arguments: []Value{
			task,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlYieldNow constructs a MIR call to the runtime function maml_yield_now.
func (b *Builder) EmitMamlYieldNow(task Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_YIELD_NOW, Type: types.UnknownType{}},
		Arguments: []Value{
			task,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}

// EmitMamlPrint constructs a MIR call to the runtime function maml_print.
func (b *Builder) EmitMamlPrint(msg_ptr Value, msg_len Value) Value {
	dst := ""

	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: SYM_PRINT, Type: types.UnknownType{}},
		Arguments: []Value{
			msg_ptr,
			msg_len,
		},
		Type: types.UnitType{},
	}
	b.current.Statements = append(b.current.Statements, call)
	return nil
}
