// Code generated by gen_mir.go. DO NOT EDIT.
package mir

import (
	"github.com/mattcarp12/maml/frontend/types"
)

// ============================================================================
// Core Interfaces
// ============================================================================

type Instruction interface {
	isInstruction()
}

type Terminator interface {
	isTerminator()
}

type Value interface {
	isValue()
}

// ============================================================================
// Nodes (Instructions, Terminators, Values)
// ============================================================================
type ArrayInitInst struct {
	Dst   string
	Index int
	Value Value
}

func (*ArrayInitInst) isInstruction() {}

type AssignInst struct {
	Dst    string
	RValue Value
}

func (*AssignInst) isInstruction() {}

type BinaryOpInst struct {
	Dst      string
	Left     Value
	Operator string
	Right    Value
	Type     types.Type
}

func (*BinaryOpInst) isInstruction() {}

type BoolConstant struct {
	Type  types.Type
	Value bool
}

func (*BoolConstant) isValue() {}

type BranchTerminator struct {
	Condition   Value
	FalseTarget BlockID
	TrueTarget  BlockID
}

func (*BranchTerminator) isTerminator() {}

type CallInst struct {
	Arguments []MIRCallArg
	Dst       string
	Function  Value
	Type      types.Type
}

func (*CallInst) isInstruction() {}

type CastInst struct {
	Dst  string
	Src  Value
	Type types.Type
}

func (*CastInst) isInstruction() {}

type CopyInst struct {
	Dst string
	Src string
}

func (*CopyInst) isInstruction() {}

type CoroPrologueInst struct {
}

func (*CoroPrologueInst) isInstruction() {}

type CoroSuspendTerminator struct {
	CleanupBlock BlockID
	ResumeBlock  BlockID
	SuspendBlock BlockID
}

func (*CoroSuspendTerminator) isTerminator() {}

type FieldReadInst struct {
	Dst           string
	FieldIndex    int
	FieldName     string
	FieldOffset   int
	Object        Value
	Type          types.Type
	VariantLayout []types.Type
}

func (*FieldReadInst) isInstruction() {}

type FreezeInst struct {
	Dst  string
	Path []string
	Root Value
	Type types.Type
}

func (*FreezeInst) isInstruction() {}

type IndexAssignInst struct {
	Index      Value
	Target     string
	TargetType types.Type
	Value      Value
}

func (*IndexAssignInst) isInstruction() {}

type IndexReadInst struct {
	Dst        string
	Index      Value
	Source     Value
	SourceType types.Type
	Type       types.Type
}

func (*IndexReadInst) isInstruction() {}

type IntConstant struct {
	Type  types.Type
	Value int64
}

func (*IntConstant) isValue() {}

type JumpTerminator struct {
	Target BlockID
}

func (*JumpTerminator) isTerminator() {}

type KeepAliveInst struct {
	Src string
}

func (*KeepAliveInst) isInstruction() {}

type LoadPtrInst struct {
	Dst  string
	Ptr  Value
	Type types.Type
}

func (*LoadPtrInst) isInstruction() {}

type MoveInst struct {
	Dst string
	Src string
}

func (*MoveInst) isInstruction() {}

type MutBorrowInst struct {
	Dst string
	Src string
}

func (*MutBorrowInst) isInstruction() {}

type OwnInst struct {
	Dst  string
	Path []string
	Root Value
	Type types.Type
}

func (*OwnInst) isInstruction() {}

type RefAllocInst struct {
	Dst  string
	Type types.Type
}

func (*RefAllocInst) isInstruction() {}

type RefDecInst struct {
	Src string
}

func (*RefDecInst) isInstruction() {}

type RefIncInst struct {
	Src string
}

func (*RefIncInst) isInstruction() {}

type Register struct {
	Name string
	Type types.Type
}

func (*Register) isValue() {}

type ReturnTerminator struct {
	Value Value
}

func (*ReturnTerminator) isTerminator() {}

type SliceInst struct {
	ContainerType types.Type
	Dst           string
	High          Value
	Left          Value
	Low           Value
	ResultType    types.Type
}

func (*SliceInst) isInstruction() {}

type StoreInst struct {
	DstPtr string
	Type   types.Type
	Value  Value
}

func (*StoreInst) isInstruction() {}

type StringConstant struct {
	Type  types.Type
	Value string
}

func (*StringConstant) isValue() {}

type StructInitInst struct {
	Dst           string
	FieldIndex    int
	FieldName     string
	FieldOffset   int
	Value         Value
	VariantLayout []types.Type
}

func (*StructInitInst) isInstruction() {}

type TempDeclInst struct {
	Name string
	Type types.Type
}

func (*TempDeclInst) isInstruction() {}

type UnaryOpInst struct {
	Dst      string
	Operand  Value
	Operator string
	Type     types.Type
}

func (*UnaryOpInst) isInstruction() {}

type UnreachableTerminator struct {
}

func (*UnreachableTerminator) isTerminator() {}

type VariantDiscriminantInst struct {
	Dst    string
	Object Value
	Type   types.Type
}

func (*VariantDiscriminantInst) isInstruction() {}

type VariantInitInst struct {
	Discriminant int
	Dst          string
	Payloads     []Value
	Type         types.Type
	VariantName  string
}

func (*VariantInitInst) isInstruction() {}

type VariantReadInst struct {
	Dst          string
	Object       Value
	PayloadIndex int
	Type         types.Type
	VariantName  string
}

func (*VariantReadInst) isInstruction() {}

// ============================================================================
// Helpers
// ============================================================================
type MIRCallArg struct {
	Argument Value
	Mut      bool
}
