// Code generated by gen_mir.go. DO NOT EDIT.
package mir

import (
	"github.com/mattcarp12/maml/frontend/types"
)

// ============================================================================
// Core Interfaces
// ============================================================================

type Instruction interface {
	isInstruction()
}

type Terminator interface {
	isTerminator()
}

type Value interface {
	isValue()
}

// ============================================================================
// Nodes (Instructions, Terminators, Values)
// ============================================================================
type AddressOfInst struct {
	Dst string
	Src string
}

func (*AddressOfInst) isInstruction() {}

type AssignInst struct {
	Dst    string
	RValue Value
}

func (*AssignInst) isInstruction() {}

type BinaryOpInst struct {
	Dst      string
	Left     Value
	Operator string
	Right    Value
	Type     types.Type
}

func (*BinaryOpInst) isInstruction() {}

type BitcastPtrInst struct {
	Dst  string
	Src  Value
	Type types.Type
}

func (*BitcastPtrInst) isInstruction() {}

type BoolConstant struct {
	Type  types.Type
	Value bool
}

func (*BoolConstant) isValue() {}

type BorrowInst struct {
	Dst   string
	IsMut bool
	Src   string
}

func (*BorrowInst) isInstruction() {}

type BranchTerminator struct {
	Condition   Value
	FalseTarget BlockID
	TrueTarget  BlockID
}

func (*BranchTerminator) isTerminator() {}

type CallInst struct {
	Arguments []Value
	Dst       string
	Function  Value
	Type      types.Type
}

func (*CallInst) isInstruction() {}

type CastInst struct {
	Dst  string
	Src  Value
	Type types.Type
}

func (*CastInst) isInstruction() {}

type CopyInst struct {
	Dst string
	Src string
}

func (*CopyInst) isInstruction() {}

type CoroPrologueInst struct {
}

func (*CoroPrologueInst) isInstruction() {}

type CoroSuspendTerminator struct {
	CleanupBlock BlockID
	ResumeBlock  BlockID
	SuspendBlock BlockID
}

func (*CoroSuspendTerminator) isTerminator() {}

type CoroYieldTerminator struct {
}

func (*CoroYieldTerminator) isTerminator() {}

type FieldAddrInst struct {
	Dst           string
	FieldIndex    int
	FieldName     string
	FieldType     types.Type
	Object        Value
	ObjectType    types.Type
	VariantLayout []types.Type
}

func (*FieldAddrInst) isInstruction() {}

type IndexAddrInst struct {
	Dst        string
	Index      Value
	Source     Value
	SourceType types.Type
	Type       types.Type
}

func (*IndexAddrInst) isInstruction() {}

type IntConstant struct {
	Type  types.Type
	Value int64
}

func (*IntConstant) isValue() {}

type JumpTerminator struct {
	Target BlockID
}

func (*JumpTerminator) isTerminator() {}

type KeepAliveInst struct {
	Src string
}

func (*KeepAliveInst) isInstruction() {}

type LoadPtrInst struct {
	Dst  string
	Ptr  Value
	Type types.Type
}

func (*LoadPtrInst) isInstruction() {}

type MoveInst struct {
	Dst string
	Src string
}

func (*MoveInst) isInstruction() {}

type Register struct {
	Name string
	Type types.Type
}

func (*Register) isValue() {}

type ReturnTerminator struct {
	Value Value
}

func (*ReturnTerminator) isTerminator() {}

type StoreInst struct {
	DstPtr string
	Type   types.Type
	Value  Value
}

func (*StoreInst) isInstruction() {}

type StringConstant struct {
	Type  types.Type
	Value string
}

func (*StringConstant) isValue() {}

type UnaryOpInst struct {
	Dst      string
	Operand  Value
	Operator string
	Type     types.Type
}

func (*UnaryOpInst) isInstruction() {}

type UnreachableTerminator struct {
}

func (*UnreachableTerminator) isTerminator() {}

// ============================================================================
// Generic Mapper & Dispatcher
// ============================================================================

type Mapper[R any] interface {
	MapAddressOfInst(n *AddressOfInst) R
	MapAssignInst(n *AssignInst) R
	MapBinaryOpInst(n *BinaryOpInst) R
	MapBitcastPtrInst(n *BitcastPtrInst) R
	MapBoolConstant(n *BoolConstant) R
	MapBorrowInst(n *BorrowInst) R
	MapBranchTerminator(n *BranchTerminator) R
	MapCallInst(n *CallInst) R
	MapCastInst(n *CastInst) R
	MapCopyInst(n *CopyInst) R
	MapCoroPrologueInst(n *CoroPrologueInst) R
	MapCoroSuspendTerminator(n *CoroSuspendTerminator) R
	MapCoroYieldTerminator(n *CoroYieldTerminator) R
	MapFieldAddrInst(n *FieldAddrInst) R
	MapIndexAddrInst(n *IndexAddrInst) R
	MapIntConstant(n *IntConstant) R
	MapJumpTerminator(n *JumpTerminator) R
	MapKeepAliveInst(n *KeepAliveInst) R
	MapLoadPtrInst(n *LoadPtrInst) R
	MapMoveInst(n *MoveInst) R
	MapRegister(n *Register) R
	MapReturnTerminator(n *ReturnTerminator) R
	MapStoreInst(n *StoreInst) R
	MapStringConstant(n *StringConstant) R
	MapUnaryOpInst(n *UnaryOpInst) R
	MapUnreachableTerminator(n *UnreachableTerminator) R
}

func MapNode[R any](node any, m Mapper[R]) R {
	if node == nil {
		var zero R
		return zero
	}
	switch n := node.(type) {
	case *AddressOfInst:
		return m.MapAddressOfInst(n)
	case *AssignInst:
		return m.MapAssignInst(n)
	case *BinaryOpInst:
		return m.MapBinaryOpInst(n)
	case *BitcastPtrInst:
		return m.MapBitcastPtrInst(n)
	case *BoolConstant:
		return m.MapBoolConstant(n)
	case *BorrowInst:
		return m.MapBorrowInst(n)
	case *BranchTerminator:
		return m.MapBranchTerminator(n)
	case *CallInst:
		return m.MapCallInst(n)
	case *CastInst:
		return m.MapCastInst(n)
	case *CopyInst:
		return m.MapCopyInst(n)
	case *CoroPrologueInst:
		return m.MapCoroPrologueInst(n)
	case *CoroSuspendTerminator:
		return m.MapCoroSuspendTerminator(n)
	case *CoroYieldTerminator:
		return m.MapCoroYieldTerminator(n)
	case *FieldAddrInst:
		return m.MapFieldAddrInst(n)
	case *IndexAddrInst:
		return m.MapIndexAddrInst(n)
	case *IntConstant:
		return m.MapIntConstant(n)
	case *JumpTerminator:
		return m.MapJumpTerminator(n)
	case *KeepAliveInst:
		return m.MapKeepAliveInst(n)
	case *LoadPtrInst:
		return m.MapLoadPtrInst(n)
	case *MoveInst:
		return m.MapMoveInst(n)
	case *Register:
		return m.MapRegister(n)
	case *ReturnTerminator:
		return m.MapReturnTerminator(n)
	case *StoreInst:
		return m.MapStoreInst(n)
	case *StringConstant:
		return m.MapStringConstant(n)
	case *UnaryOpInst:
		return m.MapUnaryOpInst(n)
	case *UnreachableTerminator:
		return m.MapUnreachableTerminator(n)
	default:
		panic("MIR Exporter Error: Unhandled MIR node type in MapNode")
	}
}

// ============================================================================
// Helpers
// ============================================================================
