// Code generated by gen_mir.go. DO NOT EDIT.
package mir

import (
	"github.com/mattcarp12/maml/frontend/types"
)

// ============================================================================
// Core Interfaces
// ============================================================================

type Instruction interface {
	isInstruction()
}

type Terminator interface {
	isTerminator()
}

type Value interface {
	isValue()
}

// ============================================================================
// Nodes (Instructions, Terminators, Values)
// ============================================================================
type ArrayInitInst struct {
	Dst   string
	Index int
	Value Value
}

func (*ArrayInitInst) isInstruction() {}

type AssignInst struct {
	Dst    string
	RValue Value
}

func (*AssignInst) isInstruction() {}

type BinaryOpInst struct {
	Dst      string
	Left     Value
	Operator string
	Right    Value
	Type     types.Type
}

func (*BinaryOpInst) isInstruction() {}

type BoolConstant struct {
	Type  types.Type
	Value bool
}

func (*BoolConstant) isValue() {}

type BranchTerminator struct {
	Condition   Value
	FalseTarget BlockID
	TrueTarget  BlockID
}

func (*BranchTerminator) isTerminator() {}

type CallInst struct {
	Arguments []MIRCallArg
	Dst       string
	Function  Value
	Type      types.Type
}

func (*CallInst) isInstruction() {}

type CastInst struct {
	Dst  string
	Src  Value
	Type types.Type
}

func (*CastInst) isInstruction() {}

type CopyInst struct {
	Dst string
	Src string
}

func (*CopyInst) isInstruction() {}

type CoroPrologueInst struct {
}

func (*CoroPrologueInst) isInstruction() {}

type CoroSuspendTerminator struct {
	CleanupBlock BlockID
	ResumeBlock  BlockID
	SuspendBlock BlockID
}

func (*CoroSuspendTerminator) isTerminator() {}

type CoroYieldTerminator struct {
}

func (*CoroYieldTerminator) isTerminator() {}

type FieldReadInst struct {
	Dst           string
	FieldIndex    int
	FieldName     string
	FieldOffset   int
	Object        Value
	Type          types.Type
	VariantLayout []types.Type
}

func (*FieldReadInst) isInstruction() {}

type FreezeInst struct {
	Dst  string
	Path []string
	Root Value
	Type types.Type
}

func (*FreezeInst) isInstruction() {}

type IndexAssignInst struct {
	Index      Value
	Target     string
	TargetType types.Type
	Value      Value
}

func (*IndexAssignInst) isInstruction() {}

type IndexReadInst struct {
	Dst        string
	Index      Value
	Source     Value
	SourceType types.Type
	Type       types.Type
}

func (*IndexReadInst) isInstruction() {}

type IntConstant struct {
	Type  types.Type
	Value int64
}

func (*IntConstant) isValue() {}

type JumpTerminator struct {
	Target BlockID
}

func (*JumpTerminator) isTerminator() {}

type KeepAliveInst struct {
	Src string
}

func (*KeepAliveInst) isInstruction() {}

type LoadPtrInst struct {
	Dst  string
	Ptr  Value
	Type types.Type
}

func (*LoadPtrInst) isInstruction() {}

type MoveInst struct {
	Dst string
	Src string
}

func (*MoveInst) isInstruction() {}

type MutBorrowInst struct {
	Dst string
	Src string
}

func (*MutBorrowInst) isInstruction() {}

type OwnInst struct {
	Dst  string
	Path []string
	Root Value
	Type types.Type
}

func (*OwnInst) isInstruction() {}

type RefAllocInst struct {
	Dst  string
	Type types.Type
}

func (*RefAllocInst) isInstruction() {}

type RefDecInst struct {
	Src string
}

func (*RefDecInst) isInstruction() {}

type RefIncInst struct {
	Src string
}

func (*RefIncInst) isInstruction() {}

type Register struct {
	Name string
	Type types.Type
}

func (*Register) isValue() {}

type ReturnTerminator struct {
	Value Value
}

func (*ReturnTerminator) isTerminator() {}

type SliceInst struct {
	ContainerType types.Type
	Dst           string
	High          Value
	Left          Value
	Low           Value
	ResultType    types.Type
}

func (*SliceInst) isInstruction() {}

type StoreInst struct {
	DstPtr string
	Type   types.Type
	Value  Value
}

func (*StoreInst) isInstruction() {}

type StringConstant struct {
	Type  types.Type
	Value string
}

func (*StringConstant) isValue() {}

type StructInitInst struct {
	Dst           string
	FieldIndex    int
	FieldName     string
	FieldOffset   int
	Value         Value
	VariantLayout []types.Type
}

func (*StructInitInst) isInstruction() {}

type TempDeclInst struct {
	Name string
	Type types.Type
}

func (*TempDeclInst) isInstruction() {}

type UnaryOpInst struct {
	Dst      string
	Operand  Value
	Operator string
	Type     types.Type
}

func (*UnaryOpInst) isInstruction() {}

type UnreachableTerminator struct {
}

func (*UnreachableTerminator) isTerminator() {}

type VariantDiscriminantInst struct {
	Dst    string
	Object Value
	Type   types.Type
}

func (*VariantDiscriminantInst) isInstruction() {}

type VariantInitInst struct {
	Discriminant int
	Dst          string
	Payloads     []Value
	Type         types.Type
	VariantName  string
}

func (*VariantInitInst) isInstruction() {}

type VariantReadInst struct {
	Dst          string
	Object       Value
	PayloadIndex int
	Type         types.Type
	VariantName  string
}

func (*VariantReadInst) isInstruction() {}

// ============================================================================
// Generic Mapper & Dispatcher
// ============================================================================

type Mapper[R any] interface {
	MapArrayInitInst(n *ArrayInitInst) R
	MapAssignInst(n *AssignInst) R
	MapBinaryOpInst(n *BinaryOpInst) R
	MapBoolConstant(n *BoolConstant) R
	MapBranchTerminator(n *BranchTerminator) R
	MapCallInst(n *CallInst) R
	MapCastInst(n *CastInst) R
	MapCopyInst(n *CopyInst) R
	MapCoroPrologueInst(n *CoroPrologueInst) R
	MapCoroSuspendTerminator(n *CoroSuspendTerminator) R
	MapCoroYieldTerminator(n *CoroYieldTerminator) R
	MapFieldReadInst(n *FieldReadInst) R
	MapFreezeInst(n *FreezeInst) R
	MapIndexAssignInst(n *IndexAssignInst) R
	MapIndexReadInst(n *IndexReadInst) R
	MapIntConstant(n *IntConstant) R
	MapJumpTerminator(n *JumpTerminator) R
	MapKeepAliveInst(n *KeepAliveInst) R
	MapLoadPtrInst(n *LoadPtrInst) R
	MapMoveInst(n *MoveInst) R
	MapMutBorrowInst(n *MutBorrowInst) R
	MapOwnInst(n *OwnInst) R
	MapRefAllocInst(n *RefAllocInst) R
	MapRefDecInst(n *RefDecInst) R
	MapRefIncInst(n *RefIncInst) R
	MapRegister(n *Register) R
	MapReturnTerminator(n *ReturnTerminator) R
	MapSliceInst(n *SliceInst) R
	MapStoreInst(n *StoreInst) R
	MapStringConstant(n *StringConstant) R
	MapStructInitInst(n *StructInitInst) R
	MapTempDeclInst(n *TempDeclInst) R
	MapUnaryOpInst(n *UnaryOpInst) R
	MapUnreachableTerminator(n *UnreachableTerminator) R
	MapVariantDiscriminantInst(n *VariantDiscriminantInst) R
	MapVariantInitInst(n *VariantInitInst) R
	MapVariantReadInst(n *VariantReadInst) R
}

func MapNode[R any](node any, m Mapper[R]) R {
	if node == nil {
		var zero R
		return zero
	}
	switch n := node.(type) {
	case *ArrayInitInst:
		return m.MapArrayInitInst(n)
	case *AssignInst:
		return m.MapAssignInst(n)
	case *BinaryOpInst:
		return m.MapBinaryOpInst(n)
	case *BoolConstant:
		return m.MapBoolConstant(n)
	case *BranchTerminator:
		return m.MapBranchTerminator(n)
	case *CallInst:
		return m.MapCallInst(n)
	case *CastInst:
		return m.MapCastInst(n)
	case *CopyInst:
		return m.MapCopyInst(n)
	case *CoroPrologueInst:
		return m.MapCoroPrologueInst(n)
	case *CoroSuspendTerminator:
		return m.MapCoroSuspendTerminator(n)
	case *CoroYieldTerminator:
		return m.MapCoroYieldTerminator(n)
	case *FieldReadInst:
		return m.MapFieldReadInst(n)
	case *FreezeInst:
		return m.MapFreezeInst(n)
	case *IndexAssignInst:
		return m.MapIndexAssignInst(n)
	case *IndexReadInst:
		return m.MapIndexReadInst(n)
	case *IntConstant:
		return m.MapIntConstant(n)
	case *JumpTerminator:
		return m.MapJumpTerminator(n)
	case *KeepAliveInst:
		return m.MapKeepAliveInst(n)
	case *LoadPtrInst:
		return m.MapLoadPtrInst(n)
	case *MoveInst:
		return m.MapMoveInst(n)
	case *MutBorrowInst:
		return m.MapMutBorrowInst(n)
	case *OwnInst:
		return m.MapOwnInst(n)
	case *RefAllocInst:
		return m.MapRefAllocInst(n)
	case *RefDecInst:
		return m.MapRefDecInst(n)
	case *RefIncInst:
		return m.MapRefIncInst(n)
	case *Register:
		return m.MapRegister(n)
	case *ReturnTerminator:
		return m.MapReturnTerminator(n)
	case *SliceInst:
		return m.MapSliceInst(n)
	case *StoreInst:
		return m.MapStoreInst(n)
	case *StringConstant:
		return m.MapStringConstant(n)
	case *StructInitInst:
		return m.MapStructInitInst(n)
	case *TempDeclInst:
		return m.MapTempDeclInst(n)
	case *UnaryOpInst:
		return m.MapUnaryOpInst(n)
	case *UnreachableTerminator:
		return m.MapUnreachableTerminator(n)
	case *VariantDiscriminantInst:
		return m.MapVariantDiscriminantInst(n)
	case *VariantInitInst:
		return m.MapVariantInitInst(n)
	case *VariantReadInst:
		return m.MapVariantReadInst(n)
	default:
		panic("MIR Exporter Error: Unhandled MIR node type in MapNode")
	}
}

// ============================================================================
// Helpers
// ============================================================================
type MIRCallArg struct {
	Argument Value
	Mut      bool
}
