// Code generated by tools/gen_runtime.go. DO NOT EDIT.
package mir

import (
	"github.com/mattcarp12/maml/frontend/types"
)

// EmitMamlRuntimeInit constructs a MIR call to the runtime function maml_runtime_init.
func (b *Builder) EmitMamlRuntimeInit(current *BasicBlock) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:       dst,
		Function:  &Register{Name: types.SYM_RUNTIME_INIT, Type: types.UnknownType{}},
		Arguments: []Value{},
		Type:      types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlAlloc constructs a MIR call to the runtime function maml_alloc.
func (b *Builder) EmitMamlAlloc(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_ALLOC, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlFree constructs a MIR call to the runtime function maml_free.
func (b *Builder) EmitMamlFree(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_FREE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlVecCreate constructs a MIR call to the runtime function maml_vec_create.
func (b *Builder) EmitMamlVecCreate(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_VEC_CREATE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlVecPush constructs a MIR call to the runtime function maml_vec_push.
func (b *Builder) EmitMamlVecPush(current *BasicBlock, arg0 Value, arg1 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_VEC_PUSH, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlVecSet constructs a MIR call to the runtime function maml_vec_set.
func (b *Builder) EmitMamlVecSet(current *BasicBlock, arg0 Value, arg1 Value, arg2 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_VEC_SET, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
			arg2,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlVecGet constructs a MIR call to the runtime function maml_vec_get.
func (b *Builder) EmitMamlVecGet(current *BasicBlock, arg0 Value, arg1 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_VEC_GET, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlVecLen constructs a MIR call to the runtime function maml_vec_len.
func (b *Builder) EmitMamlVecLen(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.U32Type{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_VEC_LEN, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.U32Type{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.U32Type{}}, current
}

// EmitMamlVecClone constructs a MIR call to the runtime function maml_vec_clone.
func (b *Builder) EmitMamlVecClone(current *BasicBlock, arg0 Value, arg1 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_VEC_CLONE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlMapCreate constructs a MIR call to the runtime function maml_map_create.
func (b *Builder) EmitMamlMapCreate(current *BasicBlock, arg0 Value, arg1 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_MAP_CREATE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlMapPut constructs a MIR call to the runtime function maml_map_put.
func (b *Builder) EmitMamlMapPut(current *BasicBlock, arg0 Value, arg1 Value, arg2 Value, arg3 Value, arg4 Value, arg5 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_MAP_PUT, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlMapGet constructs a MIR call to the runtime function maml_map_get.
func (b *Builder) EmitMamlMapGet(current *BasicBlock, arg0 Value, arg1 Value, arg2 Value, arg3 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_MAP_GET, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
			arg2,
			arg3,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlMapDelete constructs a MIR call to the runtime function maml_map_delete.
func (b *Builder) EmitMamlMapDelete(current *BasicBlock, arg0 Value, arg1 Value, arg2 Value, arg3 Value, arg4 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_MAP_DELETE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlMapLen constructs a MIR call to the runtime function maml_map_len.
func (b *Builder) EmitMamlMapLen(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.U32Type{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_MAP_LEN, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.U32Type{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.U32Type{}}, current
}

// EmitMamlMapClone constructs a MIR call to the runtime function maml_map_clone.
func (b *Builder) EmitMamlMapClone(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_MAP_CLONE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlMapNextActive constructs a MIR call to the runtime function maml_map_next_active.
func (b *Builder) EmitMamlMapNextActive(current *BasicBlock, arg0 Value, arg1 Value, arg2 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_MAP_NEXT_ACTIVE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
			arg2,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlStrHash constructs a MIR call to the runtime function maml_str_hash.
func (b *Builder) EmitMamlStrHash(current *BasicBlock, arg0 Value, arg1 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.U32Type{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_STR_HASH, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
		},
		Type: types.U32Type{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.U32Type{}}, current
}

// EmitMamlStrEq constructs a MIR call to the runtime function maml_str_eq.
func (b *Builder) EmitMamlStrEq(current *BasicBlock, arg0 Value, arg1 Value, arg2 Value, arg3 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.I32Type{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_STR_EQ, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
			arg2,
			arg3,
		},
		Type: types.I32Type{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.I32Type{}}, current
}

// EmitMamlStrClone constructs a MIR call to the runtime function maml_str_clone.
func (b *Builder) EmitMamlStrClone(current *BasicBlock, arg0 Value, arg1 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_STR_CLONE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlCoroResumeHelper constructs a MIR call to the runtime function maml_coro_resume_helper.
func (b *Builder) EmitMamlCoroResumeHelper(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_CORO_RESUME_HELPER, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlCoroDoneHelper constructs a MIR call to the runtime function maml_coro_done_helper.
func (b *Builder) EmitMamlCoroDoneHelper(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.BoolType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_CORO_DONE_HELPER, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.BoolType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.BoolType{}}, current
}

// EmitMamlCoroDestroyHelper constructs a MIR call to the runtime function maml_coro_destroy_helper.
func (b *Builder) EmitMamlCoroDestroyHelper(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_CORO_DESTROY_HELPER, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlSpawnTask constructs a MIR call to the runtime function maml_spawn_task.
func (b *Builder) EmitMamlSpawnTask(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_SPAWN_TASK, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlRunExecutor constructs a MIR call to the runtime function maml_run_executor.
func (b *Builder) EmitMamlRunExecutor(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	// Create destination temp for return value
	dst := b.newTemp()
	current.Statements = append(current.Statements, &TempDeclInst{
		Name: dst,
		Type: types.PtrType{},
	})
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_RUN_EXECUTOR, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.PtrType{},
	}
	current.Statements = append(current.Statements, call)
	return &Register{Name: dst, Type: types.PtrType{}}, current
}

// EmitMamlTaskAwait constructs a MIR call to the runtime function maml_task_await.
func (b *Builder) EmitMamlTaskAwait(current *BasicBlock, arg0 Value, arg1 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_TASK_AWAIT, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlTaskRelease constructs a MIR call to the runtime function maml_task_release.
func (b *Builder) EmitMamlTaskRelease(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_TASK_RELEASE, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlTaskGetResult constructs a MIR call to the runtime function maml_task_get_result.
func (b *Builder) EmitMamlTaskGetResult(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_TASK_GET_RESULT, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlYieldNow constructs a MIR call to the runtime function maml_yield_now.
func (b *Builder) EmitMamlYieldNow(current *BasicBlock, arg0 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_YIELD_NOW, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}

// EmitMamlPrint constructs a MIR call to the runtime function maml_print.
func (b *Builder) EmitMamlPrint(current *BasicBlock, arg0 Value, arg1 Value) (Value, *BasicBlock) {
	dst := ""
	call := &CallInst{
		Dst:      dst,
		Function: &Register{Name: types.SYM_PRINT, Type: types.UnknownType{}},
		Arguments: []Value{
			arg0,
			arg1,
		},
		Type: types.UnitType{},
	}
	current.Statements = append(current.Statements, call)
	return nil, current
}
