// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[NEWLINE-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[BOOL-7]
	_ = x[DECLARE-8]
	_ = x[ASSIGN-9]
	_ = x[YIELD-10]
	_ = x[SEPARATOR-11]
	_ = x[PIPE-12]
	_ = x[DOT-13]
	_ = x[COLON-14]
	_ = x[PLUS-15]
	_ = x[MINUS-16]
	_ = x[MULTIPLY-17]
	_ = x[DIVIDE-18]
	_ = x[MODULO-19]
	_ = x[AND-20]
	_ = x[OR-21]
	_ = x[NOT-22]
	_ = x[EQ-23]
	_ = x[NOT_EQ-24]
	_ = x[LT-25]
	_ = x[GT-26]
	_ = x[LTE-27]
	_ = x[GTE-28]
	_ = x[COMMA-29]
	_ = x[LPAREN-30]
	_ = x[RPAREN-31]
	_ = x[LBRACE-32]
	_ = x[RBRACE-33]
	_ = x[LBRACKET-34]
	_ = x[RBRACKET-35]
	_ = x[SEMICOLON-36]
	_ = x[FN-37]
	_ = x[MATCH-38]
	_ = x[CASE-39]
	_ = x[TYPE-40]
	_ = x[STRUCT-41]
	_ = x[ASYNC-42]
	_ = x[AWAIT-43]
	_ = x[IF-44]
	_ = x[ELSE-45]
	_ = x[MUT-46]
	_ = x[RETURN-47]
}

const _TokenType_name = "ILLEGALEOFNEWLINEIDENTINTFLOATSTRINGBOOLDECLAREASSIGNYIELDSEPARATORPIPEDOTCOLONPLUSMINUSMULTIPLYDIVIDEMODULOANDORNOTEQNOT_EQLTGTLTEGTECOMMALPARENRPARENLBRACERBRACELBRACKETRBRACKETSEMICOLONFNMATCHCASETYPESTRUCTASYNCAWAITIFELSEMUTRETURN"

var _TokenType_index = [...]uint8{0, 7, 10, 17, 22, 25, 30, 36, 40, 47, 53, 58, 67, 71, 74, 79, 83, 88, 96, 102, 108, 111, 113, 116, 118, 124, 126, 128, 131, 134, 139, 145, 151, 157, 163, 171, 179, 188, 190, 195, 199, 203, 209, 214, 219, 221, 225, 228, 234}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
