// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[NEWLINE-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[BOOL-7]
	_ = x[DECLARE_IMMUTABLE-8]
	_ = x[DECLARE_MUTABLE-9]
	_ = x[UPDATE-10]
	_ = x[YIELD-11]
	_ = x[SEPARATOR-12]
	_ = x[PIPE-13]
	_ = x[DOT-14]
	_ = x[COLON-15]
	_ = x[PLUS-16]
	_ = x[MINUS-17]
	_ = x[MULTIPLY-18]
	_ = x[DIVIDE-19]
	_ = x[MODULO-20]
	_ = x[AND-21]
	_ = x[OR-22]
	_ = x[NOT-23]
	_ = x[EQ-24]
	_ = x[NOT_EQ-25]
	_ = x[LT-26]
	_ = x[GT-27]
	_ = x[LTE-28]
	_ = x[GTE-29]
	_ = x[COMMA-30]
	_ = x[LPAREN-31]
	_ = x[RPAREN-32]
	_ = x[LBRACE-33]
	_ = x[RBRACE-34]
	_ = x[LBRACKET-35]
	_ = x[RBRACKET-36]
	_ = x[FN-37]
	_ = x[MATCH-38]
	_ = x[CASE-39]
	_ = x[TYPE-40]
	_ = x[STRUCT-41]
	_ = x[ASYNC-42]
	_ = x[AWAIT-43]
	_ = x[IF-44]
	_ = x[ELSE-45]
}

const _TokenType_name = "ILLEGALEOFNEWLINEIDENTINTFLOATSTRINGBOOLDECLARE_IMMUTABLEDECLARE_MUTABLEUPDATEYIELDSEPARATORPIPEDOTCOLONPLUSMINUSMULTIPLYDIVIDEMODULOANDORNOTEQNOT_EQLTGTLTEGTECOMMALPARENRPARENLBRACERBRACELBRACKETRBRACKETFNMATCHCASETYPESTRUCTASYNCAWAITIFELSE"

var _TokenType_index = [...]uint8{0, 7, 10, 17, 22, 25, 30, 36, 40, 57, 72, 78, 83, 92, 96, 99, 104, 108, 113, 121, 127, 133, 136, 138, 141, 143, 149, 151, 153, 156, 159, 164, 170, 176, 182, 188, 196, 204, 206, 211, 215, 219, 225, 230, 235, 237, 241}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
