// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[NEWLINE-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[BOOL-7]
	_ = x[DECLARE-8]
	_ = x[ASSIGN-9]
	_ = x[PLUS_EQ-10]
	_ = x[MINUS_EQ-11]
	_ = x[MUL_EQ-12]
	_ = x[DIV_EQ-13]
	_ = x[YIELD-14]
	_ = x[SEPARATOR-15]
	_ = x[PIPE-16]
	_ = x[DOT-17]
	_ = x[COLON-18]
	_ = x[PLUS-19]
	_ = x[MINUS-20]
	_ = x[MULTIPLY-21]
	_ = x[DIVIDE-22]
	_ = x[MODULO-23]
	_ = x[AND-24]
	_ = x[OR-25]
	_ = x[NOT-26]
	_ = x[EQ-27]
	_ = x[NOT_EQ-28]
	_ = x[LT-29]
	_ = x[GT-30]
	_ = x[LTE-31]
	_ = x[GTE-32]
	_ = x[PUSH-33]
	_ = x[COMMA-34]
	_ = x[LPAREN-35]
	_ = x[RPAREN-36]
	_ = x[LBRACE-37]
	_ = x[RBRACE-38]
	_ = x[LBRACKET-39]
	_ = x[RBRACKET-40]
	_ = x[SEMICOLON-41]
	_ = x[FN-42]
	_ = x[MATCH-43]
	_ = x[CASE-44]
	_ = x[TYPE-45]
	_ = x[STRUCT-46]
	_ = x[ASYNC-47]
	_ = x[AWAIT-48]
	_ = x[SPAWN-49]
	_ = x[IF-50]
	_ = x[ELSE-51]
	_ = x[MUT-52]
	_ = x[RETURN-53]
	_ = x[FOR-54]
	_ = x[OWN-55]
	_ = x[FREEZE-56]
	_ = x[BREAK-57]
	_ = x[CONTINUE-58]
	_ = x[EXTERN-59]
}

const _TokenType_name = "ILLEGALEOFNEWLINEIDENTINTFLOATSTRINGBOOLDECLAREASSIGNPLUS_EQMINUS_EQMUL_EQDIV_EQYIELDSEPARATORPIPEDOTCOLONPLUSMINUSMULTIPLYDIVIDEMODULOANDORNOTEQNOT_EQLTGTLTEGTEPUSHCOMMALPARENRPARENLBRACERBRACELBRACKETRBRACKETSEMICOLONFNMATCHCASETYPESTRUCTASYNCAWAITSPAWNIFELSEMUTRETURNFOROWNFREEZEBREAKCONTINUEEXTERN"

var _TokenType_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 36, 40, 47, 53, 60, 68, 74, 80, 85, 94, 98, 101, 106, 110, 115, 123, 129, 135, 138, 140, 143, 145, 151, 153, 155, 158, 161, 165, 170, 176, 182, 188, 194, 202, 210, 219, 221, 226, 230, 234, 240, 245, 250, 255, 257, 261, 264, 270, 273, 276, 282, 287, 295, 301}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
