// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[NEWLINE-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[BOOL-7]
	_ = x[DECLARE-8]
	_ = x[ASSIGN-9]
	_ = x[YIELD-10]
	_ = x[SEPARATOR-11]
	_ = x[PIPE-12]
	_ = x[DOT-13]
	_ = x[COLON-14]
	_ = x[PLUS-15]
	_ = x[MINUS-16]
	_ = x[MULTIPLY-17]
	_ = x[DIVIDE-18]
	_ = x[MODULO-19]
	_ = x[AND-20]
	_ = x[OR-21]
	_ = x[NOT-22]
	_ = x[EQ-23]
	_ = x[NOT_EQ-24]
	_ = x[LT-25]
	_ = x[GT-26]
	_ = x[LTE-27]
	_ = x[GTE-28]
	_ = x[PUSH-29]
	_ = x[COMMA-30]
	_ = x[LPAREN-31]
	_ = x[RPAREN-32]
	_ = x[LBRACE-33]
	_ = x[RBRACE-34]
	_ = x[LBRACKET-35]
	_ = x[RBRACKET-36]
	_ = x[SEMICOLON-37]
	_ = x[FN-38]
	_ = x[MATCH-39]
	_ = x[CASE-40]
	_ = x[TYPE-41]
	_ = x[STRUCT-42]
	_ = x[ASYNC-43]
	_ = x[AWAIT-44]
	_ = x[IF-45]
	_ = x[ELSE-46]
	_ = x[MUT-47]
	_ = x[RETURN-48]
	_ = x[FOR-49]
	_ = x[OWN-50]
	_ = x[FREEZE-51]
	_ = x[BREAK-52]
	_ = x[CONTINUE-53]
}

const _TokenType_name = "ILLEGALEOFNEWLINEIDENTINTFLOATSTRINGBOOLDECLAREASSIGNYIELDSEPARATORPIPEDOTCOLONPLUSMINUSMULTIPLYDIVIDEMODULOANDORNOTEQNOT_EQLTGTLTEGTEPUSHCOMMALPARENRPARENLBRACERBRACELBRACKETRBRACKETSEMICOLONFNMATCHCASETYPESTRUCTASYNCAWAITIFELSEMUTRETURNFOROWNFREEZEBREAKCONTINUE"

var _TokenType_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 36, 40, 47, 53, 58, 67, 71, 74, 79, 83, 88, 96, 102, 108, 111, 113, 116, 118, 124, 126, 128, 131, 134, 138, 143, 149, 155, 161, 167, 175, 183, 192, 194, 199, 203, 207, 213, 218, 223, 225, 229, 232, 238, 241, 244, 250, 255, 263}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
