#!/usr/bin/env python3
import yaml
from pathlib import Path

SCHEMA_FILE = "tast.schema.yaml"
METHODS_OUT_FILE = "methods.generated.go"
TAST_OUT_FILE = "tast.go"
SCRIPT_DIR = Path(__file__).resolve().parent


def generate_tast(schema_path, tast_out_path, methods_out_path):
    with open(schema_path, "r") as f:
        schema = yaml.safe_load(f)

    interfaces = schema.get("interfaces", {})
    nodes = schema.get("nodes", {})

    interface_markers = {
        "Decl": "declNode",
        "Stmt": "stmtNode",
        "Expr": "exprNode",
        "Pattern": "patternNode",
    }

    node_to_marker = {}
    for itface, concrete_list in interfaces.items():
        marker = interface_markers.get(itface)
        if marker:
            for node_name in concrete_list:
                node_to_marker.setdefault(node_name, []).append(marker)

    expr_nodes = set(interfaces.get("Expr", []))

    # =========================================================================
    # 1. GENERATE TAST.GO (Structs & Interfaces & TypeOf)
    # =========================================================================
    with open(tast_out_path, "w") as f:
        f.write("// Code generated by generate_tast.py; DO NOT EDIT.\n")
        f.write("package tast\n\n")
        f.write(
            'import (\n\t"github.com/mattcarp12/maml/frontend/types"\n\t"github.com/mattcarp12/maml/frontend/ast"\n)\n\n'
        )
        f.write("type Position = ast.Position\n\n")

        # Generate structural taxonomy interfaces
        f.write("// Core AST interface taxonomy\n")
        f.write("type Node interface {\n\tPos() Position\n\tEnd() Position\n\tString() string\n}\n\n")
        for itface, marker in interface_markers.items():
            f.write(f"type {itface} interface {{\n\tNode\n\t{marker}()\n}}\n\n")

        # Generate node definitions
        for node_name, node_data in nodes.items():
            f.write(f"type {node_name} struct {{\n")
            f.write('\tPos_ Position `json:"-"`\n')
            f.write('\tEnd_ Position `json:"-"`\n')

            fields = (node_data or {}).get("fields", {})
            for field_name, field_type in fields.items():
                f.write(f"\t{field_name} {field_type}\n")

            f.write("}\n\n")

        # Generate fully automated and exhaustive TypeOf function
        f.write("// TypeOf extracts the resolved type from any TAST expression node.\n")
        f.write("func TypeOf(expr Expr) types.Type {\n")
        f.write("\tif expr == nil {\n\t\treturn types.UnknownType{}\n\t}\n")
        f.write("\tswitch e := expr.(type) {\n")
        for node_name in sorted(list(expr_nodes)):
            if node_name == "BlockStmt":
                continue
            f.write(f"\tcase *{node_name}:\n\t\treturn e.Type\n")
        f.write("\tcase *BlockStmt:\n\t\treturn TypeOfBlock(e)\n")
        f.write("\t}\n")
        f.write("\treturn types.UnknownType{}\n")
        f.write("}\n")

    # =========================================================================
    # 2. GENERATE METHODS.GENERATED.GO (Getters & Markers)
    # =========================================================================
    with open(methods_out_path, "w") as f:
        f.write("// Code generated by generate_tast.py; DO NOT EDIT.\n")
        f.write("package tast\n\n")

        # Generate markers and positioning methods
        for node_name in nodes.keys():
            # Structural markers
            markers = node_to_marker.get(node_name, [])
            for marker in markers:
                f.write(f"func (n *{node_name}) {marker}() {{}}\n")

            # Positioning methods
            f.write(f"func (n *{node_name}) Pos() Position {{ return n.Pos_ }}\n")
            f.write(f"func (n *{node_name}) End() Position {{ return n.End_ }}\n\n")

    print(f"Successfully generated {tast_out_path} and {methods_out_path}")


if __name__ == "__main__":
    schema_path = SCRIPT_DIR / SCHEMA_FILE
    tast_out_path = SCRIPT_DIR / TAST_OUT_FILE
    methods_out_path = SCRIPT_DIR / METHODS_OUT_FILE

    generate_tast(schema_path, tast_out_path, methods_out_path)
