// Code generated by generate_tast.py; DO NOT EDIT.
package tast

func (n *Program) declNode() {}
func (n *Program) Pos() Position { return n.Pos_ }
func (n *Program) End() Position { return n.End_ }

func (n *FnDecl) declNode() {}
func (n *FnDecl) Pos() Position { return n.Pos_ }
func (n *FnDecl) End() Position { return n.End_ }

func (n *TypeDecl) declNode() {}
func (n *TypeDecl) Pos() Position { return n.Pos_ }
func (n *TypeDecl) End() Position { return n.End_ }

func (n *BlockStmt) stmtNode() {}
func (n *BlockStmt) exprNode() {}
func (n *BlockStmt) Pos() Position { return n.Pos_ }
func (n *BlockStmt) End() Position { return n.End_ }

func (n *DeclareStmt) stmtNode() {}
func (n *DeclareStmt) Pos() Position { return n.Pos_ }
func (n *DeclareStmt) End() Position { return n.End_ }

func (n *AssignStmt) stmtNode() {}
func (n *AssignStmt) Pos() Position { return n.Pos_ }
func (n *AssignStmt) End() Position { return n.End_ }

func (n *ReturnStmt) stmtNode() {}
func (n *ReturnStmt) Pos() Position { return n.Pos_ }
func (n *ReturnStmt) End() Position { return n.End_ }

func (n *YieldStmt) stmtNode() {}
func (n *YieldStmt) Pos() Position { return n.Pos_ }
func (n *YieldStmt) End() Position { return n.End_ }

func (n *ExprStmt) stmtNode() {}
func (n *ExprStmt) Pos() Position { return n.Pos_ }
func (n *ExprStmt) End() Position { return n.End_ }

func (n *ForStmt) stmtNode() {}
func (n *ForStmt) Pos() Position { return n.Pos_ }
func (n *ForStmt) End() Position { return n.End_ }

func (n *BreakStmt) stmtNode() {}
func (n *BreakStmt) Pos() Position { return n.Pos_ }
func (n *BreakStmt) End() Position { return n.End_ }

func (n *ContinueStmt) stmtNode() {}
func (n *ContinueStmt) Pos() Position { return n.Pos_ }
func (n *ContinueStmt) End() Position { return n.End_ }

func (n *VecPushStmt) stmtNode() {}
func (n *VecPushStmt) Pos() Position { return n.Pos_ }
func (n *VecPushStmt) End() Position { return n.End_ }

func (n *Identifier) exprNode() {}
func (n *Identifier) Pos() Position { return n.Pos_ }
func (n *Identifier) End() Position { return n.End_ }

func (n *IntLiteral) exprNode() {}
func (n *IntLiteral) Pos() Position { return n.Pos_ }
func (n *IntLiteral) End() Position { return n.End_ }

func (n *BoolLiteral) exprNode() {}
func (n *BoolLiteral) Pos() Position { return n.Pos_ }
func (n *BoolLiteral) End() Position { return n.End_ }

func (n *StringLiteral) exprNode() {}
func (n *StringLiteral) Pos() Position { return n.Pos_ }
func (n *StringLiteral) End() Position { return n.End_ }

func (n *InfixExpr) exprNode() {}
func (n *InfixExpr) Pos() Position { return n.Pos_ }
func (n *InfixExpr) End() Position { return n.End_ }

func (n *PrefixExpr) exprNode() {}
func (n *PrefixExpr) Pos() Position { return n.Pos_ }
func (n *PrefixExpr) End() Position { return n.End_ }

func (n *IfExpr) exprNode() {}
func (n *IfExpr) Pos() Position { return n.Pos_ }
func (n *IfExpr) End() Position { return n.End_ }

func (n *CallExpr) exprNode() {}
func (n *CallExpr) Pos() Position { return n.Pos_ }
func (n *CallExpr) End() Position { return n.End_ }

func (n *FieldAccess) exprNode() {}
func (n *FieldAccess) Pos() Position { return n.Pos_ }
func (n *FieldAccess) End() Position { return n.End_ }

func (n *IndexExpr) exprNode() {}
func (n *IndexExpr) Pos() Position { return n.Pos_ }
func (n *IndexExpr) End() Position { return n.End_ }

func (n *SliceExpr) exprNode() {}
func (n *SliceExpr) Pos() Position { return n.Pos_ }
func (n *SliceExpr) End() Position { return n.End_ }

func (n *StructLiteral) exprNode() {}
func (n *StructLiteral) Pos() Position { return n.Pos_ }
func (n *StructLiteral) End() Position { return n.End_ }

func (n *ArrayLiteral) exprNode() {}
func (n *ArrayLiteral) Pos() Position { return n.Pos_ }
func (n *ArrayLiteral) End() Position { return n.End_ }

func (n *VariantLiteral) exprNode() {}
func (n *VariantLiteral) Pos() Position { return n.Pos_ }
func (n *VariantLiteral) End() Position { return n.End_ }

func (n *AwaitExpr) exprNode() {}
func (n *AwaitExpr) Pos() Position { return n.Pos_ }
func (n *AwaitExpr) End() Position { return n.End_ }

func (n *MatchExpr) exprNode() {}
func (n *MatchExpr) Pos() Position { return n.Pos_ }
func (n *MatchExpr) End() Position { return n.End_ }

func (n *MapLiteral) exprNode() {}
func (n *MapLiteral) Pos() Position { return n.Pos_ }
func (n *MapLiteral) End() Position { return n.End_ }

func (n *VecLiteral) exprNode() {}
func (n *VecLiteral) Pos() Position { return n.Pos_ }
func (n *VecLiteral) End() Position { return n.End_ }

func (n *WildcardPattern) patternNode() {}
func (n *WildcardPattern) Pos() Position { return n.Pos_ }
func (n *WildcardPattern) End() Position { return n.End_ }

func (n *IdentifierPattern) patternNode() {}
func (n *IdentifierPattern) Pos() Position { return n.Pos_ }
func (n *IdentifierPattern) End() Position { return n.End_ }

func (n *LiteralPattern) patternNode() {}
func (n *LiteralPattern) Pos() Position { return n.Pos_ }
func (n *LiteralPattern) End() Position { return n.End_ }

func (n *CompositePattern) patternNode() {}
func (n *CompositePattern) Pos() Position { return n.Pos_ }
func (n *CompositePattern) End() Position { return n.End_ }

func (n *VariantPattern) patternNode() {}
func (n *VariantPattern) Pos() Position { return n.Pos_ }
func (n *VariantPattern) End() Position { return n.End_ }

