// Code generated by generate_tast.py; DO NOT EDIT.
package tast

import (
	"github.com/mattcarp12/maml/frontend/types"
	"github.com/mattcarp12/maml/frontend/ast"
)

type Position = ast.Position

// Core AST interface taxonomy
type Node interface {
	Pos() Position
	End() Position
	String() string
}

type Decl interface {
	Node
	declNode()
}

type Stmt interface {
	Node
	stmtNode()
}

type Expr interface {
	Node
	exprNode()
}

type Pattern interface {
	Node
	patternNode()
}

type Program struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Decls []Decl
}

type FnDecl struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string
	Params []*Param
	ReturnType types.Type
	Body *BlockStmt
	IsAsync bool
	Symbol *types.Symbol
}

type TypeDecl struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name *Identifier
	Type types.Type
	Symbol *types.Symbol
}

type BlockStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Statements []Stmt
}

type DeclareStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Symbol *types.Symbol
	Value Expr
}

type AssignStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	LValue Expr
	RValue Expr
}

type ReturnStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr
}

type YieldStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr
}

type ExprStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr
}

type ForStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Init Stmt
	Condition Expr
	Post Stmt
	Body *BlockStmt
}

type BreakStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
}

type ContinueStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
}

type VecPushStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	LValue Expr
	RValue Expr
}

type Identifier struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value string
	Symbol *types.Symbol
	Type types.Type
}

type IntLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value int64
	Type types.Type
}

type BoolLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value bool
	Type types.Type
}

type StringLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value string
	Type types.Type
}

type InfixExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Operator string
	Left Expr
	Right Expr
	Type types.Type
}

type PrefixExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Operator string
	Right Expr
	Type types.Type
}

type IfExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Condition Expr
	Consequence *BlockStmt
	Alternative *BlockStmt
	Type types.Type
}

type CallExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Function Expr
	Arguments []CallArg
	Type types.Type
}

type FieldAccess struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Object Expr
	Field *Identifier
	Type types.Type
}

type IndexExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Left Expr
	Index Expr
	Type types.Type
}

type SliceExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Left Expr
	Low Expr
	High Expr
	Type types.Type
}

type StructLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Fields []StructField
	Type types.Type
}

type ArrayLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Elements []Expr
	Type types.Type
}

type VariantLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Variant *types.SumVariant
	Arguments []Expr
	Fields []VariantField
	Type types.Type
}

type AwaitExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr
	Type types.Type
}

type MatchExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Subject Expr
	Arms []MatchArm
	Type types.Type
}

type MapLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Elements []MapElement
	Type types.MapType
}

type VecLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Elements []Expr
	Type types.VectorType
}

type WildcardPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
}

type IdentifierPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string
	Symbol *types.Symbol
}

type LiteralPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr
}

type CompositePattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	StructType types.Type
	Elements []CompositePatternElement
}

type VariantPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Variant *Identifier
	TupleBindings []*Identifier
	Fields []VariantPatternField
	Type types.Type
	Symbol *types.Symbol
}

// TypeOf extracts the resolved type from any TAST expression node.
func TypeOf(expr Expr) types.Type {
	if expr == nil {
		return types.UnknownType{}
	}
	switch e := expr.(type) {
	case *ArrayLiteral:
		return e.Type
	case *AwaitExpr:
		return e.Type
	case *BoolLiteral:
		return e.Type
	case *CallExpr:
		return e.Type
	case *FieldAccess:
		return e.Type
	case *Identifier:
		return e.Type
	case *IfExpr:
		return e.Type
	case *IndexExpr:
		return e.Type
	case *InfixExpr:
		return e.Type
	case *IntLiteral:
		return e.Type
	case *MapLiteral:
		return e.Type
	case *MatchExpr:
		return e.Type
	case *PrefixExpr:
		return e.Type
	case *SliceExpr:
		return e.Type
	case *StringLiteral:
		return e.Type
	case *StructLiteral:
		return e.Type
	case *VariantLiteral:
		return e.Type
	case *VecLiteral:
		return e.Type
	case *BlockStmt:
		return TypeOfBlock(e)
	}
	return types.UnknownType{}
}
