// Code generated by gen_tast.go; DO NOT EDIT.
package tast

import (
	"github.com/mattcarp12/maml/frontend/ast"
	"github.com/mattcarp12/maml/frontend/types"
)

type Position = ast.Position

type Node interface {
	Pos() Position
	End() Position
	String() string
	Accept(v Visitor)
}

// Top-level TAST interfaces with marker methods
type Decl interface {
	Node
	declNode()
}

type Stmt interface {
	Node
	stmtNode()
}

type Expr interface {
	Node
	exprNode()
}

type Pattern interface {
	Node
	patternNode()
}

// =============================================================================
// TAST Node Structs
// =============================================================================
type ArrayLiteral struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Elements []Expr
	Type     types.Type
}

func (n *ArrayLiteral) Pos() Position    { return n.Pos_ }
func (n *ArrayLiteral) End() Position    { return n.End_ }
func (n *ArrayLiteral) Accept(v Visitor) { v.VisitArrayLiteral(n) }
func (n *ArrayLiteral) exprNode()        {}

type AssignStmt struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	LValue Expr
	RValue Expr
}

func (n *AssignStmt) Pos() Position    { return n.Pos_ }
func (n *AssignStmt) End() Position    { return n.End_ }
func (n *AssignStmt) Accept(v Visitor) { v.VisitAssignStmt(n) }
func (n *AssignStmt) stmtNode()        {}

type AwaitExpr struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Type  types.Type
	Value Expr
}

func (n *AwaitExpr) Pos() Position    { return n.Pos_ }
func (n *AwaitExpr) End() Position    { return n.End_ }
func (n *AwaitExpr) Accept(v Visitor) { v.VisitAwaitExpr(n) }
func (n *AwaitExpr) exprNode()        {}

type BlockStmt struct {
	Pos_       Position `json:"-"`
	End_       Position `json:"-"`
	Statements []Stmt
}

func (n *BlockStmt) Pos() Position    { return n.Pos_ }
func (n *BlockStmt) End() Position    { return n.End_ }
func (n *BlockStmt) Accept(v Visitor) { v.VisitBlockStmt(n) }
func (n *BlockStmt) stmtNode()        {}
func (n *BlockStmt) exprNode()        {}

type BoolLiteral struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Type  types.Type
	Value bool
}

func (n *BoolLiteral) Pos() Position    { return n.Pos_ }
func (n *BoolLiteral) End() Position    { return n.End_ }
func (n *BoolLiteral) Accept(v Visitor) { v.VisitBoolLiteral(n) }
func (n *BoolLiteral) exprNode()        {}

type BreakStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
}

func (n *BreakStmt) Pos() Position    { return n.Pos_ }
func (n *BreakStmt) End() Position    { return n.End_ }
func (n *BreakStmt) Accept(v Visitor) { v.VisitBreakStmt(n) }
func (n *BreakStmt) stmtNode()        {}

type CallExpr struct {
	Pos_      Position `json:"-"`
	End_      Position `json:"-"`
	Arguments []CallArg
	Function  Expr
	Type      types.Type
}

func (n *CallExpr) Pos() Position    { return n.Pos_ }
func (n *CallExpr) End() Position    { return n.End_ }
func (n *CallExpr) Accept(v Visitor) { v.VisitCallExpr(n) }
func (n *CallExpr) exprNode()        {}

type CompositePattern struct {
	Pos_       Position `json:"-"`
	End_       Position `json:"-"`
	Elements   []CompositePatternElement
	StructType types.Type
}

func (n *CompositePattern) Pos() Position    { return n.Pos_ }
func (n *CompositePattern) End() Position    { return n.End_ }
func (n *CompositePattern) Accept(v Visitor) { v.VisitCompositePattern(n) }
func (n *CompositePattern) patternNode()     {}

type ContinueStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
}

func (n *ContinueStmt) Pos() Position    { return n.Pos_ }
func (n *ContinueStmt) End() Position    { return n.End_ }
func (n *ContinueStmt) Accept(v Visitor) { v.VisitContinueStmt(n) }
func (n *ContinueStmt) stmtNode()        {}

type DeclareStmt struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Symbol *types.Symbol
	Value  Expr
}

func (n *DeclareStmt) Pos() Position    { return n.Pos_ }
func (n *DeclareStmt) End() Position    { return n.End_ }
func (n *DeclareStmt) Accept(v Visitor) { v.VisitDeclareStmt(n) }
func (n *DeclareStmt) stmtNode()        {}

type ExprStmt struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}

func (n *ExprStmt) Pos() Position    { return n.Pos_ }
func (n *ExprStmt) End() Position    { return n.End_ }
func (n *ExprStmt) Accept(v Visitor) { v.VisitExprStmt(n) }
func (n *ExprStmt) stmtNode()        {}

type FieldAccess struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Field  *Identifier
	Object Expr
	Type   types.Type
}

func (n *FieldAccess) Pos() Position    { return n.Pos_ }
func (n *FieldAccess) End() Position    { return n.End_ }
func (n *FieldAccess) Accept(v Visitor) { v.VisitFieldAccess(n) }
func (n *FieldAccess) exprNode()        {}

type FnDecl struct {
	Pos_       Position `json:"-"`
	End_       Position `json:"-"`
	Body       *BlockStmt
	IsAsync    bool
	Name       string
	Params     []*Param
	ReturnType types.Type
	Symbol     *types.Symbol
}

func (n *FnDecl) Pos() Position    { return n.Pos_ }
func (n *FnDecl) End() Position    { return n.End_ }
func (n *FnDecl) Accept(v Visitor) { v.VisitFnDecl(n) }
func (n *FnDecl) declNode()        {}

type ForStmt struct {
	Pos_      Position `json:"-"`
	End_      Position `json:"-"`
	Body      *BlockStmt
	Condition Expr
	Init      Stmt
	Post      Stmt
}

func (n *ForStmt) Pos() Position    { return n.Pos_ }
func (n *ForStmt) End() Position    { return n.End_ }
func (n *ForStmt) Accept(v Visitor) { v.VisitForStmt(n) }
func (n *ForStmt) stmtNode()        {}

type Identifier struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Symbol *types.Symbol
	Type   types.Type
	Value  string
}

func (n *Identifier) Pos() Position    { return n.Pos_ }
func (n *Identifier) End() Position    { return n.End_ }
func (n *Identifier) Accept(v Visitor) { v.VisitIdentifier(n) }
func (n *Identifier) exprNode()        {}

type IdentifierPattern struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Name   string
	Symbol *types.Symbol
}

func (n *IdentifierPattern) Pos() Position    { return n.Pos_ }
func (n *IdentifierPattern) End() Position    { return n.End_ }
func (n *IdentifierPattern) Accept(v Visitor) { v.VisitIdentifierPattern(n) }
func (n *IdentifierPattern) patternNode()     {}

type IfExpr struct {
	Pos_        Position `json:"-"`
	End_        Position `json:"-"`
	Alternative *BlockStmt
	Condition   Expr
	Consequence *BlockStmt
	Type        types.Type
}

func (n *IfExpr) Pos() Position    { return n.Pos_ }
func (n *IfExpr) End() Position    { return n.End_ }
func (n *IfExpr) Accept(v Visitor) { v.VisitIfExpr(n) }
func (n *IfExpr) exprNode()        {}

type IndexExpr struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Index Expr
	Left  Expr
	Type  types.Type
}

func (n *IndexExpr) Pos() Position    { return n.Pos_ }
func (n *IndexExpr) End() Position    { return n.End_ }
func (n *IndexExpr) Accept(v Visitor) { v.VisitIndexExpr(n) }
func (n *IndexExpr) exprNode()        {}

type InfixExpr struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Left     Expr
	Operator string
	Right    Expr
	Type     types.Type
}

func (n *InfixExpr) Pos() Position    { return n.Pos_ }
func (n *InfixExpr) End() Position    { return n.End_ }
func (n *InfixExpr) Accept(v Visitor) { v.VisitInfixExpr(n) }
func (n *InfixExpr) exprNode()        {}

type IntLiteral struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Type  types.Type
	Value int64
}

func (n *IntLiteral) Pos() Position    { return n.Pos_ }
func (n *IntLiteral) End() Position    { return n.End_ }
func (n *IntLiteral) Accept(v Visitor) { v.VisitIntLiteral(n) }
func (n *IntLiteral) exprNode()        {}

type LiteralPattern struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}

func (n *LiteralPattern) Pos() Position    { return n.Pos_ }
func (n *LiteralPattern) End() Position    { return n.End_ }
func (n *LiteralPattern) Accept(v Visitor) { v.VisitLiteralPattern(n) }
func (n *LiteralPattern) patternNode()     {}

type MapLiteral struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Elements []MapElement
	Type     *types.MapType
}

func (n *MapLiteral) Pos() Position    { return n.Pos_ }
func (n *MapLiteral) End() Position    { return n.End_ }
func (n *MapLiteral) Accept(v Visitor) { v.VisitMapLiteral(n) }
func (n *MapLiteral) exprNode()        {}

type MatchExpr struct {
	Pos_    Position `json:"-"`
	End_    Position `json:"-"`
	Arms    []MatchArm
	Subject Expr
	Type    types.Type
}

func (n *MatchExpr) Pos() Position    { return n.Pos_ }
func (n *MatchExpr) End() Position    { return n.End_ }
func (n *MatchExpr) Accept(v Visitor) { v.VisitMatchExpr(n) }
func (n *MatchExpr) exprNode()        {}

type PrefixExpr struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Operator string
	Right    Expr
	Type     types.Type
}

func (n *PrefixExpr) Pos() Position    { return n.Pos_ }
func (n *PrefixExpr) End() Position    { return n.End_ }
func (n *PrefixExpr) Accept(v Visitor) { v.VisitPrefixExpr(n) }
func (n *PrefixExpr) exprNode()        {}

type Program struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Decls []Decl
}

func (n *Program) Pos() Position    { return n.Pos_ }
func (n *Program) End() Position    { return n.End_ }
func (n *Program) Accept(v Visitor) { v.VisitProgram(n) }
func (n *Program) declNode()        {}

type ReturnStmt struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}

func (n *ReturnStmt) Pos() Position    { return n.Pos_ }
func (n *ReturnStmt) End() Position    { return n.End_ }
func (n *ReturnStmt) Accept(v Visitor) { v.VisitReturnStmt(n) }
func (n *ReturnStmt) stmtNode()        {}

type SliceExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	High Expr
	Left Expr
	Low  Expr
	Type types.Type
}

func (n *SliceExpr) Pos() Position    { return n.Pos_ }
func (n *SliceExpr) End() Position    { return n.End_ }
func (n *SliceExpr) Accept(v Visitor) { v.VisitSliceExpr(n) }
func (n *SliceExpr) exprNode()        {}

type StringLiteral struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Type  types.Type
	Value string
}

func (n *StringLiteral) Pos() Position    { return n.Pos_ }
func (n *StringLiteral) End() Position    { return n.End_ }
func (n *StringLiteral) Accept(v Visitor) { v.VisitStringLiteral(n) }
func (n *StringLiteral) exprNode()        {}

type StructLiteral struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Fields []StructField
	Type   types.Type
}

func (n *StructLiteral) Pos() Position    { return n.Pos_ }
func (n *StructLiteral) End() Position    { return n.End_ }
func (n *StructLiteral) Accept(v Visitor) { v.VisitStructLiteral(n) }
func (n *StructLiteral) exprNode()        {}

type TypeDecl struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Name   *Identifier
	Symbol *types.Symbol
	Type   types.Type
}

func (n *TypeDecl) Pos() Position    { return n.Pos_ }
func (n *TypeDecl) End() Position    { return n.End_ }
func (n *TypeDecl) Accept(v Visitor) { v.VisitTypeDecl(n) }
func (n *TypeDecl) declNode()        {}

type VariantLiteral struct {
	Pos_      Position `json:"-"`
	End_      Position `json:"-"`
	Arguments []Expr
	Fields    []VariantField
	Type      types.Type
	Variant   *types.SumVariant
}

func (n *VariantLiteral) Pos() Position    { return n.Pos_ }
func (n *VariantLiteral) End() Position    { return n.End_ }
func (n *VariantLiteral) Accept(v Visitor) { v.VisitVariantLiteral(n) }
func (n *VariantLiteral) exprNode()        {}

type VariantPattern struct {
	Pos_          Position `json:"-"`
	End_          Position `json:"-"`
	Fields        []VariantPatternField
	Symbol        *types.Symbol
	TupleBindings []*Identifier
	Type          types.Type
	Variant       *Identifier
}

func (n *VariantPattern) Pos() Position    { return n.Pos_ }
func (n *VariantPattern) End() Position    { return n.End_ }
func (n *VariantPattern) Accept(v Visitor) { v.VisitVariantPattern(n) }
func (n *VariantPattern) patternNode()     {}

type VecLiteral struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Elements []Expr
	Type     *types.VectorType
}

func (n *VecLiteral) Pos() Position    { return n.Pos_ }
func (n *VecLiteral) End() Position    { return n.End_ }
func (n *VecLiteral) Accept(v Visitor) { v.VisitVecLiteral(n) }
func (n *VecLiteral) exprNode()        {}

type VecPushStmt struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	LValue Expr
	RValue Expr
}

func (n *VecPushStmt) Pos() Position    { return n.Pos_ }
func (n *VecPushStmt) End() Position    { return n.End_ }
func (n *VecPushStmt) Accept(v Visitor) { v.VisitVecPushStmt(n) }
func (n *VecPushStmt) stmtNode()        {}

type WildcardPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
}

func (n *WildcardPattern) Pos() Position    { return n.Pos_ }
func (n *WildcardPattern) End() Position    { return n.End_ }
func (n *WildcardPattern) Accept(v Visitor) { v.VisitWildcardPattern(n) }
func (n *WildcardPattern) patternNode()     {}

type YieldStmt struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}

func (n *YieldStmt) Pos() Position    { return n.Pos_ }
func (n *YieldStmt) End() Position    { return n.End_ }
func (n *YieldStmt) Accept(v Visitor) { v.VisitYieldStmt(n) }
func (n *YieldStmt) stmtNode()        {}

// =============================================================================
// Helper Structs
// =============================================================================
type CallArg struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Argument Expr
	Mut      bool
}

func (h *CallArg) Pos() Position { return h.Pos_ }
func (h *CallArg) End() Position { return h.End_ }

type CompositePatternElement struct {
	Pos_    Position `json:"-"`
	End_    Position `json:"-"`
	Key     string
	Pattern Pattern
}

func (h *CompositePatternElement) Pos() Position { return h.Pos_ }
func (h *CompositePatternElement) End() Position { return h.End_ }

type MapElement struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Key   Expr
	Value Expr
}

func (h *MapElement) Pos() Position { return h.Pos_ }
func (h *MapElement) End() Position { return h.End_ }

type MatchArm struct {
	Pos_    Position `json:"-"`
	End_    Position `json:"-"`
	Body    Expr
	Pattern Pattern
}

func (h *MatchArm) Pos() Position { return h.Pos_ }
func (h *MatchArm) End() Position { return h.End_ }

type Param struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Name   string
	Symbol *types.Symbol
	Type   types.Type
}

func (h *Param) Pos() Position { return h.Pos_ }
func (h *Param) End() Position { return h.End_ }

type StructField struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Key   Expr
	Value Expr
}

func (h *StructField) Pos() Position { return h.Pos_ }
func (h *StructField) End() Position { return h.End_ }

type VariantField struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Name  string
	Value Expr
}

func (h *VariantField) Pos() Position { return h.Pos_ }
func (h *VariantField) End() Position { return h.End_ }

type VariantPatternField struct {
	Pos_    Position `json:"-"`
	End_    Position `json:"-"`
	Binding *Identifier
	Field   string
}

func (h *VariantPatternField) Pos() Position { return h.Pos_ }
func (h *VariantPatternField) End() Position { return h.End_ }

// =============================================================================
// Visitor Interface
// =============================================================================

type Visitor interface {
	VisitArrayLiteral(n *ArrayLiteral)
	VisitAssignStmt(n *AssignStmt)
	VisitAwaitExpr(n *AwaitExpr)
	VisitBlockStmt(n *BlockStmt)
	VisitBoolLiteral(n *BoolLiteral)
	VisitBreakStmt(n *BreakStmt)
	VisitCallExpr(n *CallExpr)
	VisitCompositePattern(n *CompositePattern)
	VisitContinueStmt(n *ContinueStmt)
	VisitDeclareStmt(n *DeclareStmt)
	VisitExprStmt(n *ExprStmt)
	VisitFieldAccess(n *FieldAccess)
	VisitFnDecl(n *FnDecl)
	VisitForStmt(n *ForStmt)
	VisitIdentifier(n *Identifier)
	VisitIdentifierPattern(n *IdentifierPattern)
	VisitIfExpr(n *IfExpr)
	VisitIndexExpr(n *IndexExpr)
	VisitInfixExpr(n *InfixExpr)
	VisitIntLiteral(n *IntLiteral)
	VisitLiteralPattern(n *LiteralPattern)
	VisitMapLiteral(n *MapLiteral)
	VisitMatchExpr(n *MatchExpr)
	VisitPrefixExpr(n *PrefixExpr)
	VisitProgram(n *Program)
	VisitReturnStmt(n *ReturnStmt)
	VisitSliceExpr(n *SliceExpr)
	VisitStringLiteral(n *StringLiteral)
	VisitStructLiteral(n *StructLiteral)
	VisitTypeDecl(n *TypeDecl)
	VisitVariantLiteral(n *VariantLiteral)
	VisitVariantPattern(n *VariantPattern)
	VisitVecLiteral(n *VecLiteral)
	VisitVecPushStmt(n *VecPushStmt)
	VisitWildcardPattern(n *WildcardPattern)
	VisitYieldStmt(n *YieldStmt)
}

// =============================================================================
// TypeOf Helpers
// =============================================================================

// TypeOf extracts the resolved type from any TAST expression node.
func TypeOf(expr Expr) types.Type {
	if expr == nil {
		return types.UnknownType{}
	}
	switch e := expr.(type) {
	case *ArrayLiteral:
		return e.Type
	case *AwaitExpr:
		return e.Type
	case *BoolLiteral:
		return e.Type
	case *CallExpr:
		return e.Type
	case *FieldAccess:
		return e.Type
	case *Identifier:
		return e.Type
	case *IfExpr:
		return e.Type
	case *IndexExpr:
		return e.Type
	case *InfixExpr:
		return e.Type
	case *IntLiteral:
		return e.Type
	case *MapLiteral:
		return e.Type
	case *MatchExpr:
		return e.Type
	case *PrefixExpr:
		return e.Type
	case *SliceExpr:
		return e.Type
	case *StringLiteral:
		return e.Type
	case *StructLiteral:
		return e.Type
	case *VariantLiteral:
		return e.Type
	case *VecLiteral:
		return e.Type
	case *BlockStmt:
		return TypeOfBlock(e)
	}
	return types.UnknownType{}
}

// TypeOfBlock evaluates the unified return type of a block by checking its final Yield statement.
func TypeOfBlock(block *BlockStmt) types.Type {
	if block == nil || len(block.Statements) == 0 {
		return types.UnitType{}
	}
	last := block.Statements[len(block.Statements)-1]
	if yield, ok := last.(*YieldStmt); ok {
		return TypeOf(yield.Value)
	}
	return types.UnitType{}
}
