// Code generated by tools/gen_spec.go. DO NOT EDIT.
const std = @import("std");
const rt = @import("runtime.zig"); // Assuming your manual function bodies live here

// ============================================================================
// Data Layouts (C-ABI Compatible)
// ============================================================================

pub const String = extern struct {
    ptr: *anyopaque,
    len: u32,
    is_owned: bool,
};

pub const Vector = extern struct {
    buffer: *anyopaque,
    cap: u32,
    len: u32,
    elem_size: u32,
};

pub const View = extern struct {
    data_ptr: *anyopaque,
    len: u32,
};

pub const Map = extern struct {
    entries: *anyopaque,
    count: u32,
    tombstone_count: u32,
    cap: u32,
    val_size: u32,
    is_string_key: bool,
};

pub const Future = extern struct {
    state: *anyopaque,
    ready: bool,
};

pub const Ref = extern struct {
    ptr: *anyopaque,
    refcount: *anyopaque,
};


// ============================================================================
// Layout Constants
// ============================================================================

// String constants
pub const STRING_SIZE: usize = 16;
pub const STRING_ALIGN: usize = 8;
pub const STRING_PTR_OFFSET: usize = 0;
pub const STRING_LEN_OFFSET: usize = 8;
pub const STRING_IS_OWNED_OFFSET: usize = 12;

// Vector constants
pub const VECTOR_SIZE: usize = 24;
pub const VECTOR_ALIGN: usize = 8;
pub const VECTOR_BUFFER_OFFSET: usize = 0;
pub const VECTOR_CAP_OFFSET: usize = 8;
pub const VECTOR_LEN_OFFSET: usize = 12;
pub const VECTOR_ELEM_SIZE_OFFSET: usize = 16;

// View constants
pub const VIEW_SIZE: usize = 16;
pub const VIEW_ALIGN: usize = 8;
pub const VIEW_DATA_PTR_OFFSET: usize = 0;
pub const VIEW_LEN_OFFSET: usize = 8;

// Map constants
pub const MAP_SIZE: usize = 32;
pub const MAP_ALIGN: usize = 8;
pub const MAP_ENTRIES_OFFSET: usize = 0;
pub const MAP_COUNT_OFFSET: usize = 8;
pub const MAP_TOMBSTONE_COUNT_OFFSET: usize = 12;
pub const MAP_CAP_OFFSET: usize = 16;
pub const MAP_VAL_SIZE_OFFSET: usize = 20;
pub const MAP_IS_STRING_KEY_OFFSET: usize = 24;

// Future constants
pub const FUTURE_SIZE: usize = 16;
pub const FUTURE_ALIGN: usize = 8;
pub const FUTURE_STATE_OFFSET: usize = 0;
pub const FUTURE_READY_OFFSET: usize = 8;

// Ref constants
pub const REF_SIZE: usize = 16;
pub const REF_ALIGN: usize = 8;
pub const REF_PTR_OFFSET: usize = 0;
pub const REF_REFCOUNT_OFFSET: usize = 8;


// ============================================================================
// Compile-Time ABI Safety Assertions
// ============================================================================
comptime {
    // 1. Verify Struct Sizes and Offsets
    if (@sizeOf(String) != 16) {
        @compileError("ABI Mismatch: String must be 16 bytes");
    }
    if (@alignOf(String) != 8) {
        @compileError("ABI Mismatch: String align must be 8");
    }
    if (@offsetOf(String, "ptr") != 0) {
        @compileError("ABI Mismatch: String.ptr offset must be 0");
    }
    if (@offsetOf(String, "len") != 8) {
        @compileError("ABI Mismatch: String.len offset must be 8");
    }
    if (@offsetOf(String, "is_owned") != 12) {
        @compileError("ABI Mismatch: String.is_owned offset must be 12");
    }
    if (@sizeOf(Vector) != 24) {
        @compileError("ABI Mismatch: Vector must be 24 bytes");
    }
    if (@alignOf(Vector) != 8) {
        @compileError("ABI Mismatch: Vector align must be 8");
    }
    if (@offsetOf(Vector, "buffer") != 0) {
        @compileError("ABI Mismatch: Vector.buffer offset must be 0");
    }
    if (@offsetOf(Vector, "cap") != 8) {
        @compileError("ABI Mismatch: Vector.cap offset must be 8");
    }
    if (@offsetOf(Vector, "len") != 12) {
        @compileError("ABI Mismatch: Vector.len offset must be 12");
    }
    if (@offsetOf(Vector, "elem_size") != 16) {
        @compileError("ABI Mismatch: Vector.elem_size offset must be 16");
    }
    if (@sizeOf(View) != 16) {
        @compileError("ABI Mismatch: View must be 16 bytes");
    }
    if (@alignOf(View) != 8) {
        @compileError("ABI Mismatch: View align must be 8");
    }
    if (@offsetOf(View, "data_ptr") != 0) {
        @compileError("ABI Mismatch: View.data_ptr offset must be 0");
    }
    if (@offsetOf(View, "len") != 8) {
        @compileError("ABI Mismatch: View.len offset must be 8");
    }
    if (@sizeOf(Map) != 32) {
        @compileError("ABI Mismatch: Map must be 32 bytes");
    }
    if (@alignOf(Map) != 8) {
        @compileError("ABI Mismatch: Map align must be 8");
    }
    if (@offsetOf(Map, "entries") != 0) {
        @compileError("ABI Mismatch: Map.entries offset must be 0");
    }
    if (@offsetOf(Map, "count") != 8) {
        @compileError("ABI Mismatch: Map.count offset must be 8");
    }
    if (@offsetOf(Map, "tombstone_count") != 12) {
        @compileError("ABI Mismatch: Map.tombstone_count offset must be 12");
    }
    if (@offsetOf(Map, "cap") != 16) {
        @compileError("ABI Mismatch: Map.cap offset must be 16");
    }
    if (@offsetOf(Map, "val_size") != 20) {
        @compileError("ABI Mismatch: Map.val_size offset must be 20");
    }
    if (@offsetOf(Map, "is_string_key") != 24) {
        @compileError("ABI Mismatch: Map.is_string_key offset must be 24");
    }
    if (@sizeOf(Future) != 16) {
        @compileError("ABI Mismatch: Future must be 16 bytes");
    }
    if (@alignOf(Future) != 8) {
        @compileError("ABI Mismatch: Future align must be 8");
    }
    if (@offsetOf(Future, "state") != 0) {
        @compileError("ABI Mismatch: Future.state offset must be 0");
    }
    if (@offsetOf(Future, "ready") != 8) {
        @compileError("ABI Mismatch: Future.ready offset must be 8");
    }
    if (@sizeOf(Ref) != 16) {
        @compileError("ABI Mismatch: Ref must be 16 bytes");
    }
    if (@alignOf(Ref) != 8) {
        @compileError("ABI Mismatch: Ref align must be 8");
    }
    if (@offsetOf(Ref, "ptr") != 0) {
        @compileError("ABI Mismatch: Ref.ptr offset must be 0");
    }
    if (@offsetOf(Ref, "refcount") != 8) {
        @compileError("ABI Mismatch: Ref.refcount offset must be 8");
    }

    // 2. Verify External Function Signatures
    if (@TypeOf(rt.alloc.maml_alloc) != fn (usize) callconv(.c) ?*anyopaque) {
        @compileError("ABI Mismatch: maml_alloc signature is incorrect.");
    }
    if (@TypeOf(rt.alloc.maml_free) != fn (?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_free signature is incorrect.");
    }
    if (@TypeOf(rt.vec.maml_vec_grow) != fn (*anyopaque, *u32, u32) callconv(.c) *anyopaque) {
        @compileError("ABI Mismatch: maml_vec_grow signature is incorrect.");
    }
    if (@TypeOf(rt.vec.maml_vec_create) != fn (u32) callconv(.c) *Vector) {
        @compileError("ABI Mismatch: maml_vec_create signature is incorrect.");
    }
    if (@TypeOf(rt.vec.maml_vec_push) != fn (*Vector, *anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_vec_push signature is incorrect.");
    }
    if (@TypeOf(rt.vec.maml_vec_get) != fn (*Vector, u32) callconv(.c) *anyopaque) {
        @compileError("ABI Mismatch: maml_vec_get signature is incorrect.");
    }
    if (@TypeOf(rt.vec.maml_vec_set) != fn (*Vector, u32, *anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_vec_set signature is incorrect.");
    }
    if (@TypeOf(rt.vec.maml_vec_len) != fn (*Vector) callconv(.c) u32) {
        @compileError("ABI Mismatch: maml_vec_len signature is incorrect.");
    }
    if (@TypeOf(rt.vec.maml_vec_clone) != fn (*Vector, usize) callconv(.c) *Vector) {
        @compileError("ABI Mismatch: maml_vec_clone signature is incorrect.");
    }
    if (@TypeOf(rt.vec.maml_vec_free) != fn (*Vector) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_vec_free signature is incorrect.");
    }
    if (@TypeOf(rt.map.maml_map_create) != fn (u32, bool) callconv(.c) *Map) {
        @compileError("ABI Mismatch: maml_map_create signature is incorrect.");
    }
    if (@TypeOf(rt.map.maml_map_put) != fn (*Map, u32, *anyopaque, u32, *anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_map_put signature is incorrect.");
    }
    if (@TypeOf(rt.map.maml_map_get) != fn (*Map, u32, *anyopaque, u32) callconv(.c) ?*anyopaque) {
        @compileError("ABI Mismatch: maml_map_get signature is incorrect.");
    }
    if (@TypeOf(rt.map.maml_map_delete) != fn (*Map, u32, *anyopaque, u32) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_map_delete signature is incorrect.");
    }
    if (@TypeOf(rt.map.maml_map_len) != fn (*Map) callconv(.c) u32) {
        @compileError("ABI Mismatch: maml_map_len signature is incorrect.");
    }
    if (@TypeOf(rt.map.maml_map_clone) != fn (*Map) callconv(.c) *Map) {
        @compileError("ABI Mismatch: maml_map_clone signature is incorrect.");
    }
    if (@TypeOf(rt.map.maml_map_free) != fn (*Map) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_map_free signature is incorrect.");
    }
    if (@TypeOf(rt.string.maml_str_hash) != fn ([*]const u8, u32) callconv(.c) u32) {
        @compileError("ABI Mismatch: maml_str_hash signature is incorrect.");
    }
    if (@TypeOf(rt.string.maml_str_eq) != fn ([*]const u8, u32, [*]const u8, u32) callconv(.c) i32) {
        @compileError("ABI Mismatch: maml_str_eq signature is incorrect.");
    }
    if (@TypeOf(rt.string.maml_str_clone) != fn ([*]const u8, u32) callconv(.c) *anyopaque) {
        @compileError("ABI Mismatch: maml_str_clone signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_coro_runtime_init) != fn () callconv(.c) void) {
        @compileError("ABI Mismatch: maml_coro_runtime_init signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_coro_resume_helper) != fn (*Future) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_coro_resume_helper signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_coro_done_helper) != fn (*Future) callconv(.c) bool) {
        @compileError("ABI Mismatch: maml_coro_done_helper signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_coro_destroy_helper) != fn (*Future) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_coro_destroy_helper signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_spawn_task) != fn (*Future) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_spawn_task signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_run_executor) != fn (*Future) callconv(.c) *Future) {
        @compileError("ABI Mismatch: maml_run_executor signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_task_await) != fn (*Future, *Future) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_task_await signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_task_release) != fn (*Future) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_task_release signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_task_get_result) != fn (*Future) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_task_get_result signature is incorrect.");
    }
    if (@TypeOf(rt.coro.maml_yield_now) != fn (*Future) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_yield_now signature is incorrect.");
    }
    if (@TypeOf(rt.io.maml_print) != fn (*anyopaque, i32) callconv(.c) void) {
        @compileError("ABI Mismatch: maml_print signature is incorrect.");
    }
}