// Code generated by tools/gen_runtime.go. DO NOT EDIT.
const std = @import("std");
const rt = @import("runtime.zig");

comptime {
    if (@TypeOf(rt.maml_alloc) != fn (usize) callconv(.c) ?*anyopaque) {
        @compileError("ABI Mismatch: rt.maml_alloc must have signature fn (usize) callconv(.c) ?*anyopaque");
    }
    if (@TypeOf(rt.maml_free) != fn (?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_free must have signature fn (?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_retain) != fn (?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_retain must have signature fn (?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_release) != fn (?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_release must have signature fn (?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_vec_create) != fn (u32, ?*const fn (?*anyopaque) callconv(.c) void, ?*const fn (?*anyopaque) callconv(.c) void) callconv(.c) ?*anyopaque) {
        @compileError("ABI Mismatch: rt.maml_vec_create must have signature fn (u32, ?*const fn (?*anyopaque) callconv(.c) void, ?*const fn (?*anyopaque) callconv(.c) void) callconv(.c) ?*anyopaque");
    }
    if (@TypeOf(rt.maml_vec_push) != fn (?*anyopaque, ?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_vec_push must have signature fn (?*anyopaque, ?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_vec_set) != fn (?*anyopaque, u32, ?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_vec_set must have signature fn (?*anyopaque, u32, ?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_vec_get) != fn (?*anyopaque, u32) callconv(.c) ?*anyopaque) {
        @compileError("ABI Mismatch: rt.maml_vec_get must have signature fn (?*anyopaque, u32) callconv(.c) ?*anyopaque");
    }
    if (@TypeOf(rt.maml_vec_len) != fn (?*anyopaque) callconv(.c) u32) {
        @compileError("ABI Mismatch: rt.maml_vec_len must have signature fn (?*anyopaque) callconv(.c) u32");
    }
    if (@TypeOf(rt.maml_map_create) != fn (u32, u8, ?*const fn (?*anyopaque) callconv(.c) void, ?*const fn (?*anyopaque) callconv(.c) void, ?*const fn (?*anyopaque) callconv(.c) void, ?*const fn (?*anyopaque) callconv(.c) void) callconv(.c) ?*anyopaque) {
        @compileError("ABI Mismatch: rt.maml_map_create must have signature fn (u32, u8, ?*const fn (?*anyopaque) callconv(.c) void, ?*const fn (?*anyopaque) callconv(.c) void, ?*const fn (?*anyopaque) callconv(.c) void, ?*const fn (?*anyopaque) callconv(.c) void) callconv(.c) ?*anyopaque");
    }
    if (@TypeOf(rt.maml_map_put) != fn (?*anyopaque, u32, ?*anyopaque, u32, i32, ?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_map_put must have signature fn (?*anyopaque, u32, ?*anyopaque, u32, i32, ?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_map_get) != fn (?*anyopaque, u32, ?*anyopaque, u32) callconv(.c) ?*anyopaque) {
        @compileError("ABI Mismatch: rt.maml_map_get must have signature fn (?*anyopaque, u32, ?*anyopaque, u32) callconv(.c) ?*anyopaque");
    }
    if (@TypeOf(rt.maml_map_delete) != fn (?*anyopaque, u32, ?*anyopaque, u32, i32) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_map_delete must have signature fn (?*anyopaque, u32, ?*anyopaque, u32, i32) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_map_len) != fn (?*anyopaque) callconv(.c) u32) {
        @compileError("ABI Mismatch: rt.maml_map_len must have signature fn (?*anyopaque) callconv(.c) u32");
    }
    if (@TypeOf(rt.maml_str_hash) != fn (?*anyopaque, u32) callconv(.c) u32) {
        @compileError("ABI Mismatch: rt.maml_str_hash must have signature fn (?*anyopaque, u32) callconv(.c) u32");
    }
    if (@TypeOf(rt.maml_str_eq) != fn (?*anyopaque, u32, ?*anyopaque, u32) callconv(.c) i32) {
        @compileError("ABI Mismatch: rt.maml_str_eq must have signature fn (?*anyopaque, u32, ?*anyopaque, u32) callconv(.c) i32");
    }
    if (@TypeOf(rt.maml_coro_resume_helper) != fn (?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_coro_resume_helper must have signature fn (?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_coro_done_helper) != fn (?*anyopaque) callconv(.c) bool) {
        @compileError("ABI Mismatch: rt.maml_coro_done_helper must have signature fn (?*anyopaque) callconv(.c) bool");
    }
    if (@TypeOf(rt.maml_coro_destroy_helper) != fn (?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_coro_destroy_helper must have signature fn (?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_spawn_task) != fn (?*anyopaque) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_spawn_task must have signature fn (?*anyopaque) callconv(.c) void");
    }
    if (@TypeOf(rt.maml_run_executor) != fn () callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_run_executor must have signature fn () callconv(.c) void");
    }
    if (@TypeOf(rt.maml_print) != fn (?*anyopaque, i32) callconv(.c) void) {
        @compileError("ABI Mismatch: rt.maml_print must have signature fn (?*anyopaque, i32) callconv(.c) void");
    }
}