#include "ProgramGenerator.hpp"

#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Intrinsics.h>
#include <llvm/IR/Verifier.h>

#include "RuntimeConstants.h"
#include "StmtGenerator.hpp"
#include "TypeLowering.hpp"
#include "autogen_runtime.inc"

namespace maml {

void defineCoroHelperStubs(CodegenContext &ctx) {
  auto &Module = ctx.Module;
  auto &Context = ctx.Context;
  llvm::Type *voidTy = llvm::Type::getVoidTy(Context);
  llvm::Type *ptrTy = llvm::PointerType::getUnqual(Context);
  llvm::Type *i1Ty = llvm::Type::getInt1Ty(Context);

  // Define BEFORE any declarations to prevent LLVM suffixing
  auto defineIfMissing = [&](const char *name, llvm::FunctionType *FT, auto body) {
    if (Module->getFunction(name)) return;  // already exists

    llvm::Function *F = llvm::Function::Create(FT, llvm::Function::ExternalLinkage, name, *Module);

    llvm::BasicBlock *BB = llvm::BasicBlock::Create(Context, "entry", F);
    ctx.Builder->SetInsertPoint(BB);
    body(F);
  };

  // maml_coro_resume_helper (UPDATED: Now uses native llvm.coro.resume)
  defineIfMissing(rt::CORO_RESUME_HELPER, llvm::FunctionType::get(voidTy, {ptrTy}, false), [&](llvm::Function *F) {
    llvm::Value *hdl = F->getArg(0);
    llvm::Function *resumeFn = llvm::Intrinsic::getDeclaration(Module.get(), llvm::Intrinsic::coro_resume);
    ctx.Builder->CreateCall(resumeFn, {hdl});
    ctx.Builder->CreateRetVoid();
  });

  // maml_coro_done_helper (UPDATED: Now uses native llvm.coro.done)
  defineIfMissing(rt::CORO_DONE_HELPER, llvm::FunctionType::get(i1Ty, {ptrTy}, false), [&](llvm::Function *F) {
    llvm::Value *hdl = F->getArg(0);
    llvm::Function *doneFn = llvm::Intrinsic::getDeclaration(Module.get(), llvm::Intrinsic::coro_done);
    llvm::Value *isDone = ctx.Builder->CreateCall(doneFn, {hdl});
    ctx.Builder->CreateRet(isDone);
  });

  // maml_coro_destroy_helper (UPDATED: Now uses native llvm.coro.destroy)
  defineIfMissing(rt::CORO_DESTROY_HELPER, llvm::FunctionType::get(voidTy, {ptrTy}, false), [&](llvm::Function *F) {
    llvm::Value *hdl = F->getArg(0);
    llvm::Function *destroyFn = llvm::Intrinsic::getDeclaration(Module.get(), llvm::Intrinsic::coro_destroy);
    ctx.Builder->CreateCall(destroyFn, {hdl});
    ctx.Builder->CreateRetVoid();
  });
}

void declareRuntimeFunctions(CodegenContext &ctx) { declareAutogeneratedFunctions(ctx); }

void compileFunction(CodegenContext &ctx, const mir::Function &fn) {
  // --- Observability: Track Current Function ---
  ctx.CurrentFunctionName = fn.name;

  auto &Builder = ctx.Builder;
  auto &Context = ctx.Context;

  llvm::Type *retType = llvm::Type::getVoidTy(Context);
  if (fn.return_type) {
    retType = llvmTypeFor(ctx, fn.return_type);
  }
  if (fn.name == "main") {
    retType = llvm::Type::getInt32Ty(Context);
  }

  std::vector<llvm::Type *> paramTypes;
  for (const auto &p : fn.params) {
    paramTypes.push_back(llvmTypeFor(ctx, p.type));
  }

  llvm::FunctionType *FT = llvm::FunctionType::get(retType, paramTypes, false);
  llvm::Function *F = llvm::Function::Create(FT, llvm::Function::ExternalLinkage, fn.name, *ctx.Module);
  if (fn.is_async) F->addFnAttr(llvm::Attribute::PresplitCoroutine);

  if (fn.is_extern) {
    return;
  }

  ctx.pushScope();

  llvm::BasicBlock *allocBB = llvm::BasicBlock::Create(Context, "entry_allocs", F);

  if (fn.is_async) {
    ctx.CoroSuspendBlock = llvm::BasicBlock::Create(Context, "coro.suspend.ret", F);
    ctx.CoroCleanupBlock = llvm::BasicBlock::Create(Context, "coro.cleanup", F);
    if (!fn.entry_block.empty()) {
      ctx.CoroEntryBlockId = std::stoi(fn.entry_block);
    }
  }

  Builder->SetInsertPoint(allocBB);

  if (fn.name == "main") {
    llvm::Function *initFn = ctx.Module->getFunction("maml_runtime_init");
    if (initFn) {
      Builder->CreateCall(initFn, {});
    }
  }

  ctx.HeapVars.clear();
  for (const auto &block : fn.blocks) {
    for (const auto &inst : block.instructions) {
      if (std::holds_alternative<mir::RefAllocInst>(inst.inner)) {
        auto &refAlloc = std::get<mir::RefAllocInst>(inst.inner);
        ctx.HeapVars.insert(refAlloc.dst);
      }
    }
  }

  unsigned idx = 0;
  for (auto &arg : F->args()) {
    std::string paramName = fn.params[idx].name;
    arg.setName(paramName);
    llvm::AllocaInst *alloca = Builder->CreateAlloca(arg.getType(), nullptr, paramName);
    Builder->CreateStore(&arg, alloca);
    ctx.SymbolEnv.back()[paramName] = alloca;
    ctx.SymbolTypes[paramName] = arg.getType();
    idx++;
  }

  try {
    if (!fn.blocks.empty()) {
      for (const auto &block : fn.blocks) {
        if (block.id.empty()) ctx.Error.fatal("Encountered block with missing ID!");
        int blockId = std::stoi(block.id);
        llvm::BasicBlock *BB = llvm::BasicBlock::Create(Context, "bb" + block.id, F);
        ctx.Blocks[blockId] = BB;
      }

      for (const auto &block : fn.blocks) {
        for (const auto &inst : block.instructions) {
          if (std::holds_alternative<mir::TempDeclInst>(inst.inner) ||
              std::holds_alternative<mir::CoroPrologueInst>(inst.inner)) {
            compileInstruction(ctx, inst);
          }
        }
      }

      // if (!fn.entry_block.empty()) {
      //   int entryId = std::stoi(fn.entry_block);
      //   Builder->CreateBr(ctx.Blocks[entryId]);
      // }

      // Only emit the entry branch now for non-async functions.
      // For async functions, CoroPrologueInst will close allocBB itself.
      if (!fn.entry_block.empty()) {
        int entryId = std::stoi(fn.entry_block);
        if (!fn.is_async) {
          Builder->CreateBr(ctx.Blocks[entryId]);
        }
      }

      for (const auto &block : fn.blocks) {
        int id = std::stoi(block.id);
        ctx.Builder->SetInsertPoint(ctx.Blocks[id]);

        ctx.CurrentInstructionName = "Instructions (Block " + block.id + ")";
        for (const auto &inst : block.instructions) {
          if (!std::holds_alternative<mir::TempDeclInst>(inst.inner) &&
              !std::holds_alternative<mir::CoroPrologueInst>(inst.inner)) {
            compileInstruction(ctx, inst);
          }
        }

        ctx.CurrentInstructionName = "Terminator (Block " + block.id + ")";
        compileTerminator(ctx, block.terminator);
      }
    } else {
      Builder->CreateRetVoid();
    }
  } catch (const std::exception &e) {
    ctx.Error.fatal(std::string("Exception during block layout: ") + e.what() +
                    "\n(Likely an empty string passed to std::stoi)");
  }

  if (fn.is_async) {
    Builder->SetInsertPoint(ctx.CoroSuspendBlock);
    llvm::Function *endFn = llvm::Intrinsic::getDeclaration(ctx.Module.get(), llvm::Intrinsic::coro_end);
    llvm::Value *isUnwind = llvm::ConstantInt::get(llvm::Type::getInt1Ty(Context), 0);
    llvm::Value *noneToken = llvm::ConstantTokenNone::get(Context);
    Builder->CreateCall(endFn, {ctx.CurrentCoroHandle, isUnwind, noneToken});
    Builder->CreateRet(ctx.CurrentCoroHandle);
    Builder->SetInsertPoint(ctx.CoroCleanupBlock);
    llvm::Function *freeFn = llvm::Intrinsic::getDeclaration(ctx.Module.get(), llvm::Intrinsic::coro_free);
    llvm::Value *memToFree = Builder->CreateCall(freeFn, {ctx.CoroId, ctx.CurrentCoroHandle});
    llvm::Function *mamlFreeFn = ctx.Module->getFunction("maml_free");
    Builder->CreateCall(mamlFreeFn, {memToFree});
    Builder->CreateBr(ctx.CoroSuspendBlock);
  }

  ctx.popScope();
  ctx.Blocks.clear();

  // --- Strict LLVM Verification ---
  // If we emitted bad LLVM IR (e.g. missing terminator), fail beautifully here instead of segfaulting later!
  if (llvm::verifyFunction(*F, &llvm::errs())) {
    ctx.Error.fatal("LLVM Verification failed for function: " + fn.name);
  }
}

void compileProgram(CodegenContext &ctx, const mir::Program &prog) {
  defineCoroHelperStubs(ctx);
  declareRuntimeFunctions(ctx);
  for (const auto &fn : prog.functions) compileFunction(ctx, fn);

  // --- Final Module Verification ---
  if (llvm::verifyModule(*ctx.Module, &llvm::errs())) {
    ctx.Error.fatal("LLVM Module Verification failed! Check the console output above for details.");
  }
}

}  // namespace maml