#include "ProgramGenerator.h"

#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Intrinsics.h>

#include "RuntimeConstants.h"
#include "StmtGenerator.h"
#include "TypeLowering.h"
#include "autogen_runtime.inc"

namespace maml {

void defineCoroHelperStubs(CodegenContext &ctx) {
  auto &Module = ctx.Module;
  auto &Context = ctx.Context;
  llvm::Type *voidTy = llvm::Type::getVoidTy(Context);
  llvm::Type *ptrTy = llvm::PointerType::getUnqual(Context);
  llvm::Type *i1Ty = llvm::Type::getInt1Ty(Context);

  // Define BEFORE any declarations to prevent LLVM suffixing
  auto defineIfMissing = [&](const char *name, llvm::FunctionType *FT, auto body) {
    if (Module->getFunction(name)) return;  // already exists

    llvm::Function *F = llvm::Function::Create(FT, llvm::Function::ExternalLinkage, name, *Module);

    llvm::BasicBlock *BB = llvm::BasicBlock::Create(Context, "entry", F);
    ctx.Builder->SetInsertPoint(BB);
    body(F);
  };

  // maml_coro_resume_helper
  defineIfMissing(rt::CORO_RESUME_HELPER, llvm::FunctionType::get(voidTy, {ptrTy}, false),
                  [&](llvm::Function *) { ctx.Builder->CreateRetVoid(); });

  // maml_coro_done_helper
  defineIfMissing(rt::CORO_DONE_HELPER, llvm::FunctionType::get(i1Ty, {ptrTy}, false),
                  [&](llvm::Function *) { ctx.Builder->CreateRet(llvm::ConstantInt::get(i1Ty, 0)); });

  // maml_coro_destroy_helper
  defineIfMissing(rt::CORO_DESTROY_HELPER, llvm::FunctionType::get(voidTy, {ptrTy}, false),
                  [&](llvm::Function *) { ctx.Builder->CreateRetVoid(); });
}
void declareRuntimeFunctions(CodegenContext &ctx) { declareAutogeneratedFunctions(ctx); }

void compileFunction(CodegenContext &ctx, const mir::Function &fn) {
  auto &Builder = ctx.Builder;
  auto &Context = ctx.Context;

  llvm::Type *retType = llvm::Type::getVoidTy(Context);
  if (!fn.return_type.is_null()) {
    retType = llvmTypeFor(ctx, fn.return_type);
  }
  if (fn.name == "main") retType = llvm::Type::getInt32Ty(Context);

  std::vector<llvm::Type *> paramTypes;
  for (const auto &p : fn.params) {
    paramTypes.push_back(llvmTypeFor(ctx, p.type));
  }

  llvm::FunctionType *FT = llvm::FunctionType::get(retType, paramTypes, false);
  llvm::Function *F = llvm::Function::Create(FT, llvm::Function::ExternalLinkage, fn.name, *ctx.Module);
  if (fn.is_async) F->addFnAttr(llvm::Attribute::PresplitCoroutine);

  ctx.pushScope();
  llvm::BasicBlock *allocBB = llvm::BasicBlock::Create(Context, "entry_allocs", F);
  Builder->SetInsertPoint(allocBB);

  unsigned idx = 0;
  for (auto &arg : F->args()) {
    std::string paramName = fn.params[idx].name;
    arg.setName(paramName);
    llvm::AllocaInst *alloca = Builder->CreateAlloca(arg.getType(), nullptr, paramName);
    Builder->CreateStore(&arg, alloca);
    ctx.SymbolEnv.back()[paramName] = alloca;
    idx++;
  }

  if (!fn.blocks.empty()) {
    for (const auto &block : fn.blocks) {
      int blockId = std::stoi(block.id);
      llvm::BasicBlock *BB = llvm::BasicBlock::Create(Context, "bb" + block.id, F);
      ctx.Blocks[blockId] = BB;
    }

    Builder->SetInsertPoint(allocBB);
    for (const auto &block : fn.blocks) {
      for (const auto &inst : block.instructions) {
        if (std::holds_alternative<mir::TempDeclInst>(inst.inner)) {
          compileInstruction(ctx, inst);
        }
      }
    }

    if (!fn.entry_block.empty()) {
      int entryId = std::stoi(fn.entry_block);
      Builder->CreateBr(ctx.Blocks[entryId]);
    }

    for (const auto &block : fn.blocks) {
      int id = std::stoi(block.id);
      ctx.Builder->SetInsertPoint(ctx.Blocks[id]);
      for (const auto &inst : block.instructions) {
        if (!std::holds_alternative<mir::TempDeclInst>(inst.inner)) {
          compileInstruction(ctx, inst);
        }
      }
      compileTerminator(ctx, block.terminator);
    }
  } else {
    Builder->CreateRetVoid();
  }

  ctx.popScope();
  ctx.Blocks.clear();
}

void compileProgram(CodegenContext &ctx, const mir::Program &prog) {
  defineCoroHelperStubs(ctx);
  declareRuntimeFunctions(ctx);
  for (const auto &fn : prog.functions) compileFunction(ctx, fn);
}
}  // namespace maml