// Code generated by generate_ast.py; DO NOT EDIT.
package ast

import "github.com/mattcarp12/maml/frontend/token"

// Core AST interface taxonomy
type Node interface {
	Pos() Position
	End() Position
	String() string
	Accept(v Visitor)
}

type Decl interface {
	Node
	declNode()
}

type Stmt interface {
	Node
	stmtNode()
}

type Expr interface {
	Node
	exprNode()
}

type TypeExpr interface {
	Node
	typeNode()
}

type Pattern interface {
	Node
	patternNode()
}

type Program struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Decls []Decl `json:"decls"`
}

type FnDecl struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string `json:"name"`
	IsAsync bool `json:"is_async"`
	Params []*Param `json:"params"`
	ReturnType TypeExpr `json:"return_type"`
	Body *BlockStmt `json:"body"`
}

type TypeDecl struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name *Identifier `json:"name"`
	Rhs TypeExpr `json:"rhs"`
}

type BlockStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Statements []Stmt `json:"statements"`
}

type DeclareStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string `json:"name"`
	Mutable bool `json:"mutable"`
	Value Expr `json:"value"`
}

type AssignStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	LValue Expr `json:"l_value"`
	RValue Expr `json:"r_value"`
}

type ReturnStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr `json:"value"`
}

type YieldStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr `json:"value"`
}

type ExprStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr `json:"value"`
}

type ForStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Init Stmt `json:"init"`
	Condition Expr `json:"condition"`
	Post Stmt `json:"post"`
	Body *BlockStmt `json:"body"`
}

type BreakStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Token token.Token `json:"token"`
}

type ContinueStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Token token.Token `json:"token"`
}

type VecPushStmt struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	LValue Expr `json:"l_value"`
	RValue Expr `json:"r_value"`
}

type Identifier struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value string `json:"value"`
}

type IntLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value int64 `json:"value"`
}

type BoolLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value bool `json:"value"`
}

type StringLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value string `json:"value"`
}

type CompositeLiteral struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	TypeExpr TypeExpr `json:"type_expr"`
	Elements []CompositeElement `json:"elements"`
}

type CallExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Function Expr `json:"function"`
	Arguments []CallArg `json:"arguments"`
}

type InfixExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Left Expr `json:"left"`
	Operator string `json:"operator"`
	Right Expr `json:"right"`
}

type PrefixExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Operator string `json:"operator"`
	Right Expr `json:"right"`
}

type FieldAccess struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Object Expr `json:"object"`
	Field *Identifier `json:"field"`
}

type IndexExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Left Expr `json:"left"`
	Index Expr `json:"index"`
}

type SliceExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Left Expr `json:"left"`
	Low Expr `json:"low"`
	High Expr `json:"high"`
}

type IfExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Condition Expr `json:"condition"`
	Consequence *BlockStmt `json:"consequence"`
	Alternative *BlockStmt `json:"alternative"`
}

type MatchExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Subject Expr `json:"subject"`
	Arms []MatchArm `json:"arms"`
}

type WildcardPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
}

type IdentifierPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string `json:"name"`
}

type LiteralPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr `json:"value"`
}

type CompositePattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	TypeExpr TypeExpr `json:"type_expr"`
	Elements []CompositePatternElement `json:"elements"`
}

type TypeExprWrapper struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	TypeExpr TypeExpr `json:"type_expr"`
}

type NamedTypeExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name *Identifier `json:"name"`
}

type ArrayTypeExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Size int `json:"size"`
	Base TypeExpr `json:"base"`
}

type StructTypeExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string `json:"name"`
	Fields []StructTypeField `json:"fields"`
}

type SumTypeExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string `json:"name"`
	TypeArgs []TypeExpr `json:"type_args"`
	Variants []VariantTypeExpr `json:"variants"`
}

type GenericTypeExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name *Identifier `json:"name"`
	Args []TypeExpr `json:"args"`
}

type AwaitExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Value Expr `json:"value"`
}

