// Code generated by gen_ast.go; DO NOT EDIT.
package ast

import (
	"fmt"
	"github.com/mattcarp12/maml/frontend/token"
)

// =============================================================================
// Core Node Interfaces
// =============================================================================

type Node interface {
	Pos() Position
	End() Position
	String() string
	Accept(v Visitor)
	AcceptMapper(v ASTMapper[any]) any
}

// Top-level AST interfaces with marker methods
type Decl interface {
	Node
	declNode()
}

type Stmt interface {
	Node
	stmtNode()
}

type Expr interface {
	Node
	exprNode()
}

type TypeExpr interface {
	Node
	typeNode()
}

type Pattern interface {
	Node
	patternNode()
}

// =============================================================================
// AST Node Structs
// =============================================================================
type AliasDecl struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Cap   string
	Name  string
	Value Expr
}
type ArrayTypeExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Base TypeExpr
	Size int
}
type AssignStmt struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	LValue   Expr
	Operator string
	RValue   Expr
}
type AwaitExpr struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}
type BlockStmt struct {
	Pos_       Position `json:"-"`
	End_       Position `json:"-"`
	Statements []Stmt
}
type BoolLiteral struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value bool
}
type BreakStmt struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Token token.Token
}
type CallExpr struct {
	Pos_      Position `json:"-"`
	End_      Position `json:"-"`
	Arguments []CallArg
	Function  Expr
}
type CompositeLiteral struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Elements []CompositeElement
	TypeExpr TypeExpr
}
type CompositePattern struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Elements []CompositePatternElement
	TypeExpr TypeExpr
}
type ContinueStmt struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Token token.Token
}
type DeclareStmt struct {
	Pos_    Position `json:"-"`
	End_    Position `json:"-"`
	Mutable bool
	Name    string
	Value   Expr
}
type ExprStmt struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}
type FieldAccess struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Field  *Identifier
	Object Expr
}
type FnDecl struct {
	Pos_       Position `json:"-"`
	End_       Position `json:"-"`
	Body       *BlockStmt
	IsAsync    bool
	IsExtern   bool
	Name       string
	Params     []*Param
	ReturnType TypeExpr
}
type ForStmt struct {
	Pos_      Position `json:"-"`
	End_      Position `json:"-"`
	Body      *BlockStmt
	Condition Expr
	Init      Stmt
	Post      Stmt
}
type GenericTypeExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Args []TypeExpr
	Name *Identifier
}
type Identifier struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value string
}
type IdentifierPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string
}
type IfExpr struct {
	Pos_        Position `json:"-"`
	End_        Position `json:"-"`
	Alternative *BlockStmt
	Condition   Expr
	Consequence *BlockStmt
}
type IndexExpr struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Index Expr
	Left  Expr
}
type InfixExpr struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Left     Expr
	Operator string
	Right    Expr
}
type IntLiteral struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value int64
}
type LiteralPattern struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}
type MatchExpr struct {
	Pos_    Position `json:"-"`
	End_    Position `json:"-"`
	Arms    []MatchArm
	Subject Expr
}
type NamedTypeExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name *Identifier
}
type PrefixExpr struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Operator string
	Right    Expr
}
type Program struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Decls []Decl
}
type ReturnStmt struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}
type SliceExpr struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	High Expr
	Left Expr
	Low  Expr
}
type SpawnExpr struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value *CallExpr
}
type StringLiteral struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value string
}
type StructTypeExpr struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	Fields []StructTypeField
	Name   string
}
type SumTypeExpr struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Name     string
	TypeArgs []TypeExpr
	Variants []VariantTypeExpr
}
type TypeDecl struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name *Identifier
	Rhs  TypeExpr
}
type TypeExprWrapper struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	TypeExpr TypeExpr
}
type VecPushStmt struct {
	Pos_   Position `json:"-"`
	End_   Position `json:"-"`
	LValue Expr
	RValue Expr
}
type WildcardPattern struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
}
type YieldStmt struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Value Expr
}

// =============================================================================
// Helper Structs
// =============================================================================
type CallArg struct {
	Pos_     Position `json:"-"`
	End_     Position `json:"-"`
	Argument Expr
	Cap      string
}
type CompositeElement struct {
	Pos_  Position `json:"-"`
	End_  Position `json:"-"`
	Key   Expr
	Value Expr
}
type CompositePatternElement struct {
	Pos_    Position `json:"-"`
	End_    Position `json:"-"`
	Key     Expr
	Pattern Pattern
}
type MatchArm struct {
	Pos_    Position `json:"-"`
	End_    Position `json:"-"`
	Body    Expr
	Pattern Pattern
}
type Param struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Cap  string
	Name string
	Type TypeExpr
}
type StructTypeField struct {
	Pos_ Position `json:"-"`
	End_ Position `json:"-"`
	Name string
	Type TypeExpr
}
type VariantTypeExpr struct {
	Pos_        Position `json:"-"`
	End_        Position `json:"-"`
	Fields      []StructTypeField
	Name        string
	TupleFields []TypeExpr
}

// =============================================================================
// Marker Methods
// =============================================================================
func (n *AliasDecl) stmtNode()            {}
func (n *ArrayTypeExpr) typeNode()        {}
func (n *AssignStmt) stmtNode()           {}
func (n *AwaitExpr) exprNode()            {}
func (n *BlockStmt) stmtNode()            {}
func (n *BlockStmt) exprNode()            {}
func (n *BoolLiteral) exprNode()          {}
func (n *BreakStmt) stmtNode()            {}
func (n *CallExpr) exprNode()             {}
func (n *CompositeLiteral) exprNode()     {}
func (n *CompositePattern) patternNode()  {}
func (n *ContinueStmt) stmtNode()         {}
func (n *DeclareStmt) stmtNode()          {}
func (n *ExprStmt) stmtNode()             {}
func (n *FieldAccess) exprNode()          {}
func (n *FnDecl) declNode()               {}
func (n *ForStmt) stmtNode()              {}
func (n *GenericTypeExpr) typeNode()      {}
func (n *Identifier) exprNode()           {}
func (n *IdentifierPattern) patternNode() {}
func (n *IfExpr) exprNode()               {}
func (n *IndexExpr) exprNode()            {}
func (n *InfixExpr) exprNode()            {}
func (n *IntLiteral) exprNode()           {}
func (n *LiteralPattern) patternNode()    {}
func (n *MatchExpr) exprNode()            {}
func (n *NamedTypeExpr) typeNode()        {}
func (n *PrefixExpr) exprNode()           {}
func (n *Program) declNode()              {}
func (n *ReturnStmt) stmtNode()           {}
func (n *SliceExpr) exprNode()            {}
func (n *SpawnExpr) exprNode()            {}
func (n *StringLiteral) exprNode()        {}
func (n *StructTypeExpr) typeNode()       {}
func (n *SumTypeExpr) typeNode()          {}
func (n *TypeDecl) declNode()             {}
func (n *TypeExprWrapper) exprNode()      {}
func (n *VecPushStmt) stmtNode()          {}
func (n *WildcardPattern) patternNode()   {}
func (n *YieldStmt) stmtNode()            {}

// =============================================================================
// Visitor & Mapper Interfaces
// =============================================================================

type Visitor interface {
	VisitAliasDecl(n *AliasDecl)
	VisitArrayTypeExpr(n *ArrayTypeExpr)
	VisitAssignStmt(n *AssignStmt)
	VisitAwaitExpr(n *AwaitExpr)
	VisitBlockStmt(n *BlockStmt)
	VisitBoolLiteral(n *BoolLiteral)
	VisitBreakStmt(n *BreakStmt)
	VisitCallExpr(n *CallExpr)
	VisitCompositeLiteral(n *CompositeLiteral)
	VisitCompositePattern(n *CompositePattern)
	VisitContinueStmt(n *ContinueStmt)
	VisitDeclareStmt(n *DeclareStmt)
	VisitExprStmt(n *ExprStmt)
	VisitFieldAccess(n *FieldAccess)
	VisitFnDecl(n *FnDecl)
	VisitForStmt(n *ForStmt)
	VisitGenericTypeExpr(n *GenericTypeExpr)
	VisitIdentifier(n *Identifier)
	VisitIdentifierPattern(n *IdentifierPattern)
	VisitIfExpr(n *IfExpr)
	VisitIndexExpr(n *IndexExpr)
	VisitInfixExpr(n *InfixExpr)
	VisitIntLiteral(n *IntLiteral)
	VisitLiteralPattern(n *LiteralPattern)
	VisitMatchExpr(n *MatchExpr)
	VisitNamedTypeExpr(n *NamedTypeExpr)
	VisitPrefixExpr(n *PrefixExpr)
	VisitProgram(n *Program)
	VisitReturnStmt(n *ReturnStmt)
	VisitSliceExpr(n *SliceExpr)
	VisitSpawnExpr(n *SpawnExpr)
	VisitStringLiteral(n *StringLiteral)
	VisitStructTypeExpr(n *StructTypeExpr)
	VisitSumTypeExpr(n *SumTypeExpr)
	VisitTypeDecl(n *TypeDecl)
	VisitTypeExprWrapper(n *TypeExprWrapper)
	VisitVecPushStmt(n *VecPushStmt)
	VisitWildcardPattern(n *WildcardPattern)
	VisitYieldStmt(n *YieldStmt)
}

type ASTMapper[R any] interface {
	MapAliasDecl(n *AliasDecl) R
	MapArrayTypeExpr(n *ArrayTypeExpr) R
	MapAssignStmt(n *AssignStmt) R
	MapAwaitExpr(n *AwaitExpr) R
	MapBlockStmt(n *BlockStmt) R
	MapBoolLiteral(n *BoolLiteral) R
	MapBreakStmt(n *BreakStmt) R
	MapCallExpr(n *CallExpr) R
	MapCompositeLiteral(n *CompositeLiteral) R
	MapCompositePattern(n *CompositePattern) R
	MapContinueStmt(n *ContinueStmt) R
	MapDeclareStmt(n *DeclareStmt) R
	MapExprStmt(n *ExprStmt) R
	MapFieldAccess(n *FieldAccess) R
	MapFnDecl(n *FnDecl) R
	MapForStmt(n *ForStmt) R
	MapGenericTypeExpr(n *GenericTypeExpr) R
	MapIdentifier(n *Identifier) R
	MapIdentifierPattern(n *IdentifierPattern) R
	MapIfExpr(n *IfExpr) R
	MapIndexExpr(n *IndexExpr) R
	MapInfixExpr(n *InfixExpr) R
	MapIntLiteral(n *IntLiteral) R
	MapLiteralPattern(n *LiteralPattern) R
	MapMatchExpr(n *MatchExpr) R
	MapNamedTypeExpr(n *NamedTypeExpr) R
	MapPrefixExpr(n *PrefixExpr) R
	MapProgram(n *Program) R
	MapReturnStmt(n *ReturnStmt) R
	MapSliceExpr(n *SliceExpr) R
	MapSpawnExpr(n *SpawnExpr) R
	MapStringLiteral(n *StringLiteral) R
	MapStructTypeExpr(n *StructTypeExpr) R
	MapSumTypeExpr(n *SumTypeExpr) R
	MapTypeDecl(n *TypeDecl) R
	MapTypeExprWrapper(n *TypeExprWrapper) R
	MapVecPushStmt(n *VecPushStmt) R
	MapWildcardPattern(n *WildcardPattern) R
	MapYieldStmt(n *YieldStmt) R
}

// MapNode is a strongly-typed, auto-generated dispatcher that safely routes
// an AST Node to the correct Map function without manual type assertions.
func MapNode[R any](node Node, m ASTMapper[R]) R {
	if node == nil {
		var zero R
		return zero
	}
	switch n := node.(type) {
	case *AliasDecl:
		return m.MapAliasDecl(n)
	case *ArrayTypeExpr:
		return m.MapArrayTypeExpr(n)
	case *AssignStmt:
		return m.MapAssignStmt(n)
	case *AwaitExpr:
		return m.MapAwaitExpr(n)
	case *BlockStmt:
		return m.MapBlockStmt(n)
	case *BoolLiteral:
		return m.MapBoolLiteral(n)
	case *BreakStmt:
		return m.MapBreakStmt(n)
	case *CallExpr:
		return m.MapCallExpr(n)
	case *CompositeLiteral:
		return m.MapCompositeLiteral(n)
	case *CompositePattern:
		return m.MapCompositePattern(n)
	case *ContinueStmt:
		return m.MapContinueStmt(n)
	case *DeclareStmt:
		return m.MapDeclareStmt(n)
	case *ExprStmt:
		return m.MapExprStmt(n)
	case *FieldAccess:
		return m.MapFieldAccess(n)
	case *FnDecl:
		return m.MapFnDecl(n)
	case *ForStmt:
		return m.MapForStmt(n)
	case *GenericTypeExpr:
		return m.MapGenericTypeExpr(n)
	case *Identifier:
		return m.MapIdentifier(n)
	case *IdentifierPattern:
		return m.MapIdentifierPattern(n)
	case *IfExpr:
		return m.MapIfExpr(n)
	case *IndexExpr:
		return m.MapIndexExpr(n)
	case *InfixExpr:
		return m.MapInfixExpr(n)
	case *IntLiteral:
		return m.MapIntLiteral(n)
	case *LiteralPattern:
		return m.MapLiteralPattern(n)
	case *MatchExpr:
		return m.MapMatchExpr(n)
	case *NamedTypeExpr:
		return m.MapNamedTypeExpr(n)
	case *PrefixExpr:
		return m.MapPrefixExpr(n)
	case *Program:
		return m.MapProgram(n)
	case *ReturnStmt:
		return m.MapReturnStmt(n)
	case *SliceExpr:
		return m.MapSliceExpr(n)
	case *SpawnExpr:
		return m.MapSpawnExpr(n)
	case *StringLiteral:
		return m.MapStringLiteral(n)
	case *StructTypeExpr:
		return m.MapStructTypeExpr(n)
	case *SumTypeExpr:
		return m.MapSumTypeExpr(n)
	case *TypeDecl:
		return m.MapTypeDecl(n)
	case *TypeExprWrapper:
		return m.MapTypeExprWrapper(n)
	case *VecPushStmt:
		return m.MapVecPushStmt(n)
	case *WildcardPattern:
		return m.MapWildcardPattern(n)
	case *YieldStmt:
		return m.MapYieldStmt(n)
	default:
		panic(fmt.Sprintf("unhandled AST node type in MapNode dispatcher: %T", node))
	}
}

// =============================================================================
// Position & Interface Methods
// =============================================================================
func (n *AliasDecl) Pos() Position                             { return n.Pos_ }
func (n *AliasDecl) End() Position                             { return n.End_ }
func (n *AliasDecl) Accept(v Visitor)                          { v.VisitAliasDecl(n) }
func (n *AliasDecl) AcceptMapper(v ASTMapper[any]) any         { return v.MapAliasDecl(n) }
func (n *ArrayTypeExpr) Pos() Position                         { return n.Pos_ }
func (n *ArrayTypeExpr) End() Position                         { return n.End_ }
func (n *ArrayTypeExpr) Accept(v Visitor)                      { v.VisitArrayTypeExpr(n) }
func (n *ArrayTypeExpr) AcceptMapper(v ASTMapper[any]) any     { return v.MapArrayTypeExpr(n) }
func (n *AssignStmt) Pos() Position                            { return n.Pos_ }
func (n *AssignStmt) End() Position                            { return n.End_ }
func (n *AssignStmt) Accept(v Visitor)                         { v.VisitAssignStmt(n) }
func (n *AssignStmt) AcceptMapper(v ASTMapper[any]) any        { return v.MapAssignStmt(n) }
func (n *AwaitExpr) Pos() Position                             { return n.Pos_ }
func (n *AwaitExpr) End() Position                             { return n.End_ }
func (n *AwaitExpr) Accept(v Visitor)                          { v.VisitAwaitExpr(n) }
func (n *AwaitExpr) AcceptMapper(v ASTMapper[any]) any         { return v.MapAwaitExpr(n) }
func (n *BlockStmt) Pos() Position                             { return n.Pos_ }
func (n *BlockStmt) End() Position                             { return n.End_ }
func (n *BlockStmt) Accept(v Visitor)                          { v.VisitBlockStmt(n) }
func (n *BlockStmt) AcceptMapper(v ASTMapper[any]) any         { return v.MapBlockStmt(n) }
func (n *BoolLiteral) Pos() Position                           { return n.Pos_ }
func (n *BoolLiteral) End() Position                           { return n.End_ }
func (n *BoolLiteral) Accept(v Visitor)                        { v.VisitBoolLiteral(n) }
func (n *BoolLiteral) AcceptMapper(v ASTMapper[any]) any       { return v.MapBoolLiteral(n) }
func (n *BreakStmt) Pos() Position                             { return n.Pos_ }
func (n *BreakStmt) End() Position                             { return n.End_ }
func (n *BreakStmt) Accept(v Visitor)                          { v.VisitBreakStmt(n) }
func (n *BreakStmt) AcceptMapper(v ASTMapper[any]) any         { return v.MapBreakStmt(n) }
func (n *CallExpr) Pos() Position                              { return n.Pos_ }
func (n *CallExpr) End() Position                              { return n.End_ }
func (n *CallExpr) Accept(v Visitor)                           { v.VisitCallExpr(n) }
func (n *CallExpr) AcceptMapper(v ASTMapper[any]) any          { return v.MapCallExpr(n) }
func (n *CompositeLiteral) Pos() Position                      { return n.Pos_ }
func (n *CompositeLiteral) End() Position                      { return n.End_ }
func (n *CompositeLiteral) Accept(v Visitor)                   { v.VisitCompositeLiteral(n) }
func (n *CompositeLiteral) AcceptMapper(v ASTMapper[any]) any  { return v.MapCompositeLiteral(n) }
func (n *CompositePattern) Pos() Position                      { return n.Pos_ }
func (n *CompositePattern) End() Position                      { return n.End_ }
func (n *CompositePattern) Accept(v Visitor)                   { v.VisitCompositePattern(n) }
func (n *CompositePattern) AcceptMapper(v ASTMapper[any]) any  { return v.MapCompositePattern(n) }
func (n *ContinueStmt) Pos() Position                          { return n.Pos_ }
func (n *ContinueStmt) End() Position                          { return n.End_ }
func (n *ContinueStmt) Accept(v Visitor)                       { v.VisitContinueStmt(n) }
func (n *ContinueStmt) AcceptMapper(v ASTMapper[any]) any      { return v.MapContinueStmt(n) }
func (n *DeclareStmt) Pos() Position                           { return n.Pos_ }
func (n *DeclareStmt) End() Position                           { return n.End_ }
func (n *DeclareStmt) Accept(v Visitor)                        { v.VisitDeclareStmt(n) }
func (n *DeclareStmt) AcceptMapper(v ASTMapper[any]) any       { return v.MapDeclareStmt(n) }
func (n *ExprStmt) Pos() Position                              { return n.Pos_ }
func (n *ExprStmt) End() Position                              { return n.End_ }
func (n *ExprStmt) Accept(v Visitor)                           { v.VisitExprStmt(n) }
func (n *ExprStmt) AcceptMapper(v ASTMapper[any]) any          { return v.MapExprStmt(n) }
func (n *FieldAccess) Pos() Position                           { return n.Pos_ }
func (n *FieldAccess) End() Position                           { return n.End_ }
func (n *FieldAccess) Accept(v Visitor)                        { v.VisitFieldAccess(n) }
func (n *FieldAccess) AcceptMapper(v ASTMapper[any]) any       { return v.MapFieldAccess(n) }
func (n *FnDecl) Pos() Position                                { return n.Pos_ }
func (n *FnDecl) End() Position                                { return n.End_ }
func (n *FnDecl) Accept(v Visitor)                             { v.VisitFnDecl(n) }
func (n *FnDecl) AcceptMapper(v ASTMapper[any]) any            { return v.MapFnDecl(n) }
func (n *ForStmt) Pos() Position                               { return n.Pos_ }
func (n *ForStmt) End() Position                               { return n.End_ }
func (n *ForStmt) Accept(v Visitor)                            { v.VisitForStmt(n) }
func (n *ForStmt) AcceptMapper(v ASTMapper[any]) any           { return v.MapForStmt(n) }
func (n *GenericTypeExpr) Pos() Position                       { return n.Pos_ }
func (n *GenericTypeExpr) End() Position                       { return n.End_ }
func (n *GenericTypeExpr) Accept(v Visitor)                    { v.VisitGenericTypeExpr(n) }
func (n *GenericTypeExpr) AcceptMapper(v ASTMapper[any]) any   { return v.MapGenericTypeExpr(n) }
func (n *Identifier) Pos() Position                            { return n.Pos_ }
func (n *Identifier) End() Position                            { return n.End_ }
func (n *Identifier) Accept(v Visitor)                         { v.VisitIdentifier(n) }
func (n *Identifier) AcceptMapper(v ASTMapper[any]) any        { return v.MapIdentifier(n) }
func (n *IdentifierPattern) Pos() Position                     { return n.Pos_ }
func (n *IdentifierPattern) End() Position                     { return n.End_ }
func (n *IdentifierPattern) Accept(v Visitor)                  { v.VisitIdentifierPattern(n) }
func (n *IdentifierPattern) AcceptMapper(v ASTMapper[any]) any { return v.MapIdentifierPattern(n) }
func (n *IfExpr) Pos() Position                                { return n.Pos_ }
func (n *IfExpr) End() Position                                { return n.End_ }
func (n *IfExpr) Accept(v Visitor)                             { v.VisitIfExpr(n) }
func (n *IfExpr) AcceptMapper(v ASTMapper[any]) any            { return v.MapIfExpr(n) }
func (n *IndexExpr) Pos() Position                             { return n.Pos_ }
func (n *IndexExpr) End() Position                             { return n.End_ }
func (n *IndexExpr) Accept(v Visitor)                          { v.VisitIndexExpr(n) }
func (n *IndexExpr) AcceptMapper(v ASTMapper[any]) any         { return v.MapIndexExpr(n) }
func (n *InfixExpr) Pos() Position                             { return n.Pos_ }
func (n *InfixExpr) End() Position                             { return n.End_ }
func (n *InfixExpr) Accept(v Visitor)                          { v.VisitInfixExpr(n) }
func (n *InfixExpr) AcceptMapper(v ASTMapper[any]) any         { return v.MapInfixExpr(n) }
func (n *IntLiteral) Pos() Position                            { return n.Pos_ }
func (n *IntLiteral) End() Position                            { return n.End_ }
func (n *IntLiteral) Accept(v Visitor)                         { v.VisitIntLiteral(n) }
func (n *IntLiteral) AcceptMapper(v ASTMapper[any]) any        { return v.MapIntLiteral(n) }
func (n *LiteralPattern) Pos() Position                        { return n.Pos_ }
func (n *LiteralPattern) End() Position                        { return n.End_ }
func (n *LiteralPattern) Accept(v Visitor)                     { v.VisitLiteralPattern(n) }
func (n *LiteralPattern) AcceptMapper(v ASTMapper[any]) any    { return v.MapLiteralPattern(n) }
func (n *MatchExpr) Pos() Position                             { return n.Pos_ }
func (n *MatchExpr) End() Position                             { return n.End_ }
func (n *MatchExpr) Accept(v Visitor)                          { v.VisitMatchExpr(n) }
func (n *MatchExpr) AcceptMapper(v ASTMapper[any]) any         { return v.MapMatchExpr(n) }
func (n *NamedTypeExpr) Pos() Position                         { return n.Pos_ }
func (n *NamedTypeExpr) End() Position                         { return n.End_ }
func (n *NamedTypeExpr) Accept(v Visitor)                      { v.VisitNamedTypeExpr(n) }
func (n *NamedTypeExpr) AcceptMapper(v ASTMapper[any]) any     { return v.MapNamedTypeExpr(n) }
func (n *PrefixExpr) Pos() Position                            { return n.Pos_ }
func (n *PrefixExpr) End() Position                            { return n.End_ }
func (n *PrefixExpr) Accept(v Visitor)                         { v.VisitPrefixExpr(n) }
func (n *PrefixExpr) AcceptMapper(v ASTMapper[any]) any        { return v.MapPrefixExpr(n) }
func (n *Program) Pos() Position                               { return n.Pos_ }
func (n *Program) End() Position                               { return n.End_ }
func (n *Program) Accept(v Visitor)                            { v.VisitProgram(n) }
func (n *Program) AcceptMapper(v ASTMapper[any]) any           { return v.MapProgram(n) }
func (n *ReturnStmt) Pos() Position                            { return n.Pos_ }
func (n *ReturnStmt) End() Position                            { return n.End_ }
func (n *ReturnStmt) Accept(v Visitor)                         { v.VisitReturnStmt(n) }
func (n *ReturnStmt) AcceptMapper(v ASTMapper[any]) any        { return v.MapReturnStmt(n) }
func (n *SliceExpr) Pos() Position                             { return n.Pos_ }
func (n *SliceExpr) End() Position                             { return n.End_ }
func (n *SliceExpr) Accept(v Visitor)                          { v.VisitSliceExpr(n) }
func (n *SliceExpr) AcceptMapper(v ASTMapper[any]) any         { return v.MapSliceExpr(n) }
func (n *SpawnExpr) Pos() Position                             { return n.Pos_ }
func (n *SpawnExpr) End() Position                             { return n.End_ }
func (n *SpawnExpr) Accept(v Visitor)                          { v.VisitSpawnExpr(n) }
func (n *SpawnExpr) AcceptMapper(v ASTMapper[any]) any         { return v.MapSpawnExpr(n) }
func (n *StringLiteral) Pos() Position                         { return n.Pos_ }
func (n *StringLiteral) End() Position                         { return n.End_ }
func (n *StringLiteral) Accept(v Visitor)                      { v.VisitStringLiteral(n) }
func (n *StringLiteral) AcceptMapper(v ASTMapper[any]) any     { return v.MapStringLiteral(n) }
func (n *StructTypeExpr) Pos() Position                        { return n.Pos_ }
func (n *StructTypeExpr) End() Position                        { return n.End_ }
func (n *StructTypeExpr) Accept(v Visitor)                     { v.VisitStructTypeExpr(n) }
func (n *StructTypeExpr) AcceptMapper(v ASTMapper[any]) any    { return v.MapStructTypeExpr(n) }
func (n *SumTypeExpr) Pos() Position                           { return n.Pos_ }
func (n *SumTypeExpr) End() Position                           { return n.End_ }
func (n *SumTypeExpr) Accept(v Visitor)                        { v.VisitSumTypeExpr(n) }
func (n *SumTypeExpr) AcceptMapper(v ASTMapper[any]) any       { return v.MapSumTypeExpr(n) }
func (n *TypeDecl) Pos() Position                              { return n.Pos_ }
func (n *TypeDecl) End() Position                              { return n.End_ }
func (n *TypeDecl) Accept(v Visitor)                           { v.VisitTypeDecl(n) }
func (n *TypeDecl) AcceptMapper(v ASTMapper[any]) any          { return v.MapTypeDecl(n) }
func (n *TypeExprWrapper) Pos() Position                       { return n.Pos_ }
func (n *TypeExprWrapper) End() Position                       { return n.End_ }
func (n *TypeExprWrapper) Accept(v Visitor)                    { v.VisitTypeExprWrapper(n) }
func (n *TypeExprWrapper) AcceptMapper(v ASTMapper[any]) any   { return v.MapTypeExprWrapper(n) }
func (n *VecPushStmt) Pos() Position                           { return n.Pos_ }
func (n *VecPushStmt) End() Position                           { return n.End_ }
func (n *VecPushStmt) Accept(v Visitor)                        { v.VisitVecPushStmt(n) }
func (n *VecPushStmt) AcceptMapper(v ASTMapper[any]) any       { return v.MapVecPushStmt(n) }
func (n *WildcardPattern) Pos() Position                       { return n.Pos_ }
func (n *WildcardPattern) End() Position                       { return n.End_ }
func (n *WildcardPattern) Accept(v Visitor)                    { v.VisitWildcardPattern(n) }
func (n *WildcardPattern) AcceptMapper(v ASTMapper[any]) any   { return v.MapWildcardPattern(n) }
func (n *YieldStmt) Pos() Position                             { return n.Pos_ }
func (n *YieldStmt) End() Position                             { return n.End_ }
func (n *YieldStmt) Accept(v Visitor)                          { v.VisitYieldStmt(n) }
func (n *YieldStmt) AcceptMapper(v ASTMapper[any]) any         { return v.MapYieldStmt(n) }
func (n *CallArg) Pos() Position                               { return n.Pos_ }
func (n *CallArg) End() Position                               { return n.End_ }
func (n *CompositeElement) Pos() Position                      { return n.Pos_ }
func (n *CompositeElement) End() Position                      { return n.End_ }
func (n *CompositePatternElement) Pos() Position               { return n.Pos_ }
func (n *CompositePatternElement) End() Position               { return n.End_ }
func (n *MatchArm) Pos() Position                              { return n.Pos_ }
func (n *MatchArm) End() Position                              { return n.End_ }
func (n *Param) Pos() Position                                 { return n.Pos_ }
func (n *Param) End() Position                                 { return n.End_ }
func (n *StructTypeField) Pos() Position                       { return n.Pos_ }
func (n *StructTypeField) End() Position                       { return n.End_ }
func (n *VariantTypeExpr) Pos() Position                       { return n.Pos_ }
func (n *VariantTypeExpr) End() Position                       { return n.End_ }

// =============================================================================
// Source Position Type
// =============================================================================

type Position struct {
	Line int
	Col  int
}

func (p Position) String() string {
	return fmt.Sprintf("%d:%d", p.Line, p.Col)
}

// =============================================================================
// Compile Error
// =============================================================================

type CompileError struct {
	Stage string
	Pos   Position
	Msg   string
}

func (e CompileError) Error() string {
	return fmt.Sprintf("[%s Error] at %d:%d: %s", e.Stage, e.Pos.Line, e.Pos.Col, e.Msg)
}
