#!/usr/bin/env python3
import yaml
from pathlib import Path

SCHEMA_FILE = "ast.schema.yaml"
METHODS_OUT_FILE = "methods_generated.go"
AST_OUT_FILE = "ast_generated.go"
SCRIPT_DIR = Path(__file__).resolve().parent


def to_json_tag(field_name):
    # Maps field names to clean JSON keys (e.g., "ReturnType" -> "return_type")
    # If it's a positional field, we hide it from JSON output using `json:"-"`
    if field_name in ["Pos_", "End_"]:
        return '"-"'

    # Simple camelCase / snake_case converter helper
    result = [field_name[0].lower()]
    for char in field_name[1:]:
        if char.isupper():
            result.append("_" + char.lower())
        else:
            result.append(char)
    return f'"{"".join(result)}"'


def generate_ast(schema_path, ast_out_path, methods_out_path):
    with open(schema_path, "r") as f:
        schema = yaml.safe_load(f)

    interfaces = schema.get("interfaces", {})
    nodes = schema.get("nodes", {})

    interface_markers = {
        "Decl": "declNode",
        "Stmt": "stmtNode",
        "Expr": "exprNode",
        "TypeExpr": "typeNode",
        "Pattern": "patternNode",
    }

    node_to_marker = {}
    for itface, concrete_list in interfaces.items():
        marker = interface_markers.get(itface)
        if marker:
            for node_name in concrete_list:
                node_to_marker.setdefault(node_name, []).append(marker)

    # =========================================================================
    # 1. GENERATE AST.GO (Struct Definitions & Core Interfaces)
    # =========================================================================
    with open(ast_out_path, "w") as f:
        f.write("// Code generated by generate_ast.py; DO NOT EDIT.\n")
        f.write("package ast\n\n")
        f.write('import "github.com/mattcarp12/maml/frontend/token"\n\n')

        # Core interface contracts
        f.write("// Core AST interface taxonomy\n")
        f.write(
            "type Node interface {\n\tPos() Position\n\tEnd() Position\n\tString() string\n\tAccept(v Visitor)\n}\n\n"
        )
        for itface, marker in interface_markers.items():
            f.write(f"type {itface} interface {{\n\tNode\n\t{marker}()\n}}\n\n")

        # Emit concrete node structs
        for name in nodes.keys():
            f.write(f"type {name} struct {{\n")
            # Every node implicitly receives standardized coordinates
            f.write('\tPos_ Position `json:"-"`\n')
            f.write('\tEnd_ Position `json:"-"`\n')

            # Print user-defined structural fields
            fields = nodes[name].get("fields") or {}
            for field_name, field_type in fields.items():
                json_tag = to_json_tag(field_name)
                f.write(f"\t{field_name} {field_type} `json:{json_tag}`\n")

            f.write("}\n\n")

    # =========================================================================
    # 2. GENERATE METHODS_GENERATED.GO (Visitor Systems & Getters)
    # =========================================================================

    with open(methods_out_path, "w") as f:
        f.write("// Code generated by generate_ast.py; DO NOT EDIT.\n")
        f.write("package ast\n\n")

        # 1. Generate interface structural markers first
        for node_name in nodes.keys():
            markers = node_to_marker.get(node_name, [])
            for marker in markers:
                f.write(f"func (n *{node_name}) {marker}() {{}}\n")

        # 1. Generate the standard Visitor interface
        f.write("// Visitor defines a classic mutating or reading walker contract.\n")
        f.write("type Visitor interface {\n")
        for node_name in nodes.keys():
            f.write(f"\tVisit{node_name}(n *{node_name})\n")
        f.write("}\n\n")

        # 2. Generate a Generic Mapper interface for value-producing passes (like AST -> TAST)
        f.write("// ASTMapper defines a generic transformer contract that returns a typed result.\n")
        f.write("type ASTMapper[R any] interface {\n")
        for node_name in nodes.keys():
            f.write(f"\tMap{node_name}(n *{node_name}) R\n")
        f.write("}\n\n")

        # 2. Generate Pos() and End() methods
        for node_name in nodes.keys():
            # Positioning methods
            f.write(f"func (n *{node_name}) Pos() Position {{ return n.Pos_ }}\n")
            f.write(f"func (n *{node_name}) End() Position {{ return n.End_ }}\n")

            # Visitor Dispatch Methods
            f.write(f"func (n *{node_name}) Accept(v Visitor) {{ v.Visit{node_name}(n) }}\n")
            f.write(f"func (n *{node_name}) AcceptMapper(v ASTMapper[any]) any {{ return v.Map{node_name}(n) }}\n")

    print("✅ Successfully generated AST code.")


if __name__ == "__main__":
    generate_ast(SCRIPT_DIR / SCHEMA_FILE, SCRIPT_DIR / AST_OUT_FILE, SCRIPT_DIR / METHODS_OUT_FILE)
