// Code generated by generate_ast.py; DO NOT EDIT.
package ast

func (n *Program) declNode() {}
func (n *FnDecl) declNode() {}
func (n *TypeDecl) declNode() {}
func (n *BlockStmt) stmtNode() {}
func (n *BlockStmt) exprNode() {}
func (n *DeclareStmt) stmtNode() {}
func (n *AssignStmt) stmtNode() {}
func (n *ReturnStmt) stmtNode() {}
func (n *YieldStmt) stmtNode() {}
func (n *ExprStmt) stmtNode() {}
func (n *ForStmt) stmtNode() {}
func (n *BreakStmt) stmtNode() {}
func (n *ContinueStmt) stmtNode() {}
func (n *VecPushStmt) stmtNode() {}
func (n *Identifier) exprNode() {}
func (n *IntLiteral) exprNode() {}
func (n *BoolLiteral) exprNode() {}
func (n *StringLiteral) exprNode() {}
func (n *CompositeLiteral) exprNode() {}
func (n *CallExpr) exprNode() {}
func (n *InfixExpr) exprNode() {}
func (n *PrefixExpr) exprNode() {}
func (n *FieldAccess) exprNode() {}
func (n *IndexExpr) exprNode() {}
func (n *SliceExpr) exprNode() {}
func (n *IfExpr) exprNode() {}
func (n *MatchExpr) exprNode() {}
func (n *WildcardPattern) patternNode() {}
func (n *IdentifierPattern) patternNode() {}
func (n *LiteralPattern) patternNode() {}
func (n *CompositePattern) patternNode() {}
func (n *TypeExprWrapper) exprNode() {}
func (n *NamedTypeExpr) typeNode() {}
func (n *ArrayTypeExpr) typeNode() {}
func (n *StructTypeExpr) typeNode() {}
func (n *SumTypeExpr) typeNode() {}
func (n *GenericTypeExpr) typeNode() {}
func (n *AwaitExpr) exprNode() {}
// Visitor defines a classic mutating or reading walker contract.
type Visitor interface {
	VisitProgram(n *Program)
	VisitFnDecl(n *FnDecl)
	VisitTypeDecl(n *TypeDecl)
	VisitBlockStmt(n *BlockStmt)
	VisitDeclareStmt(n *DeclareStmt)
	VisitAssignStmt(n *AssignStmt)
	VisitReturnStmt(n *ReturnStmt)
	VisitYieldStmt(n *YieldStmt)
	VisitExprStmt(n *ExprStmt)
	VisitForStmt(n *ForStmt)
	VisitBreakStmt(n *BreakStmt)
	VisitContinueStmt(n *ContinueStmt)
	VisitVecPushStmt(n *VecPushStmt)
	VisitIdentifier(n *Identifier)
	VisitIntLiteral(n *IntLiteral)
	VisitBoolLiteral(n *BoolLiteral)
	VisitStringLiteral(n *StringLiteral)
	VisitCompositeLiteral(n *CompositeLiteral)
	VisitCallExpr(n *CallExpr)
	VisitInfixExpr(n *InfixExpr)
	VisitPrefixExpr(n *PrefixExpr)
	VisitFieldAccess(n *FieldAccess)
	VisitIndexExpr(n *IndexExpr)
	VisitSliceExpr(n *SliceExpr)
	VisitIfExpr(n *IfExpr)
	VisitMatchExpr(n *MatchExpr)
	VisitWildcardPattern(n *WildcardPattern)
	VisitIdentifierPattern(n *IdentifierPattern)
	VisitLiteralPattern(n *LiteralPattern)
	VisitCompositePattern(n *CompositePattern)
	VisitTypeExprWrapper(n *TypeExprWrapper)
	VisitNamedTypeExpr(n *NamedTypeExpr)
	VisitArrayTypeExpr(n *ArrayTypeExpr)
	VisitStructTypeExpr(n *StructTypeExpr)
	VisitSumTypeExpr(n *SumTypeExpr)
	VisitGenericTypeExpr(n *GenericTypeExpr)
	VisitAwaitExpr(n *AwaitExpr)
}

// ASTMapper defines a generic transformer contract that returns a typed result.
type ASTMapper[R any] interface {
	MapProgram(n *Program) R
	MapFnDecl(n *FnDecl) R
	MapTypeDecl(n *TypeDecl) R
	MapBlockStmt(n *BlockStmt) R
	MapDeclareStmt(n *DeclareStmt) R
	MapAssignStmt(n *AssignStmt) R
	MapReturnStmt(n *ReturnStmt) R
	MapYieldStmt(n *YieldStmt) R
	MapExprStmt(n *ExprStmt) R
	MapForStmt(n *ForStmt) R
	MapBreakStmt(n *BreakStmt) R
	MapContinueStmt(n *ContinueStmt) R
	MapVecPushStmt(n *VecPushStmt) R
	MapIdentifier(n *Identifier) R
	MapIntLiteral(n *IntLiteral) R
	MapBoolLiteral(n *BoolLiteral) R
	MapStringLiteral(n *StringLiteral) R
	MapCompositeLiteral(n *CompositeLiteral) R
	MapCallExpr(n *CallExpr) R
	MapInfixExpr(n *InfixExpr) R
	MapPrefixExpr(n *PrefixExpr) R
	MapFieldAccess(n *FieldAccess) R
	MapIndexExpr(n *IndexExpr) R
	MapSliceExpr(n *SliceExpr) R
	MapIfExpr(n *IfExpr) R
	MapMatchExpr(n *MatchExpr) R
	MapWildcardPattern(n *WildcardPattern) R
	MapIdentifierPattern(n *IdentifierPattern) R
	MapLiteralPattern(n *LiteralPattern) R
	MapCompositePattern(n *CompositePattern) R
	MapTypeExprWrapper(n *TypeExprWrapper) R
	MapNamedTypeExpr(n *NamedTypeExpr) R
	MapArrayTypeExpr(n *ArrayTypeExpr) R
	MapStructTypeExpr(n *StructTypeExpr) R
	MapSumTypeExpr(n *SumTypeExpr) R
	MapGenericTypeExpr(n *GenericTypeExpr) R
	MapAwaitExpr(n *AwaitExpr) R
}

func (n *Program) Pos() Position { return n.Pos_ }
func (n *Program) End() Position { return n.End_ }
func (n *Program) Accept(v Visitor) { v.VisitProgram(n) }
func (n *Program) AcceptMapper(v ASTMapper[any]) any { return v.MapProgram(n) }
func (n *FnDecl) Pos() Position { return n.Pos_ }
func (n *FnDecl) End() Position { return n.End_ }
func (n *FnDecl) Accept(v Visitor) { v.VisitFnDecl(n) }
func (n *FnDecl) AcceptMapper(v ASTMapper[any]) any { return v.MapFnDecl(n) }
func (n *TypeDecl) Pos() Position { return n.Pos_ }
func (n *TypeDecl) End() Position { return n.End_ }
func (n *TypeDecl) Accept(v Visitor) { v.VisitTypeDecl(n) }
func (n *TypeDecl) AcceptMapper(v ASTMapper[any]) any { return v.MapTypeDecl(n) }
func (n *BlockStmt) Pos() Position { return n.Pos_ }
func (n *BlockStmt) End() Position { return n.End_ }
func (n *BlockStmt) Accept(v Visitor) { v.VisitBlockStmt(n) }
func (n *BlockStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapBlockStmt(n) }
func (n *DeclareStmt) Pos() Position { return n.Pos_ }
func (n *DeclareStmt) End() Position { return n.End_ }
func (n *DeclareStmt) Accept(v Visitor) { v.VisitDeclareStmt(n) }
func (n *DeclareStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapDeclareStmt(n) }
func (n *AssignStmt) Pos() Position { return n.Pos_ }
func (n *AssignStmt) End() Position { return n.End_ }
func (n *AssignStmt) Accept(v Visitor) { v.VisitAssignStmt(n) }
func (n *AssignStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapAssignStmt(n) }
func (n *ReturnStmt) Pos() Position { return n.Pos_ }
func (n *ReturnStmt) End() Position { return n.End_ }
func (n *ReturnStmt) Accept(v Visitor) { v.VisitReturnStmt(n) }
func (n *ReturnStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapReturnStmt(n) }
func (n *YieldStmt) Pos() Position { return n.Pos_ }
func (n *YieldStmt) End() Position { return n.End_ }
func (n *YieldStmt) Accept(v Visitor) { v.VisitYieldStmt(n) }
func (n *YieldStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapYieldStmt(n) }
func (n *ExprStmt) Pos() Position { return n.Pos_ }
func (n *ExprStmt) End() Position { return n.End_ }
func (n *ExprStmt) Accept(v Visitor) { v.VisitExprStmt(n) }
func (n *ExprStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapExprStmt(n) }
func (n *ForStmt) Pos() Position { return n.Pos_ }
func (n *ForStmt) End() Position { return n.End_ }
func (n *ForStmt) Accept(v Visitor) { v.VisitForStmt(n) }
func (n *ForStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapForStmt(n) }
func (n *BreakStmt) Pos() Position { return n.Pos_ }
func (n *BreakStmt) End() Position { return n.End_ }
func (n *BreakStmt) Accept(v Visitor) { v.VisitBreakStmt(n) }
func (n *BreakStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapBreakStmt(n) }
func (n *ContinueStmt) Pos() Position { return n.Pos_ }
func (n *ContinueStmt) End() Position { return n.End_ }
func (n *ContinueStmt) Accept(v Visitor) { v.VisitContinueStmt(n) }
func (n *ContinueStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapContinueStmt(n) }
func (n *VecPushStmt) Pos() Position { return n.Pos_ }
func (n *VecPushStmt) End() Position { return n.End_ }
func (n *VecPushStmt) Accept(v Visitor) { v.VisitVecPushStmt(n) }
func (n *VecPushStmt) AcceptMapper(v ASTMapper[any]) any { return v.MapVecPushStmt(n) }
func (n *Identifier) Pos() Position { return n.Pos_ }
func (n *Identifier) End() Position { return n.End_ }
func (n *Identifier) Accept(v Visitor) { v.VisitIdentifier(n) }
func (n *Identifier) AcceptMapper(v ASTMapper[any]) any { return v.MapIdentifier(n) }
func (n *IntLiteral) Pos() Position { return n.Pos_ }
func (n *IntLiteral) End() Position { return n.End_ }
func (n *IntLiteral) Accept(v Visitor) { v.VisitIntLiteral(n) }
func (n *IntLiteral) AcceptMapper(v ASTMapper[any]) any { return v.MapIntLiteral(n) }
func (n *BoolLiteral) Pos() Position { return n.Pos_ }
func (n *BoolLiteral) End() Position { return n.End_ }
func (n *BoolLiteral) Accept(v Visitor) { v.VisitBoolLiteral(n) }
func (n *BoolLiteral) AcceptMapper(v ASTMapper[any]) any { return v.MapBoolLiteral(n) }
func (n *StringLiteral) Pos() Position { return n.Pos_ }
func (n *StringLiteral) End() Position { return n.End_ }
func (n *StringLiteral) Accept(v Visitor) { v.VisitStringLiteral(n) }
func (n *StringLiteral) AcceptMapper(v ASTMapper[any]) any { return v.MapStringLiteral(n) }
func (n *CompositeLiteral) Pos() Position { return n.Pos_ }
func (n *CompositeLiteral) End() Position { return n.End_ }
func (n *CompositeLiteral) Accept(v Visitor) { v.VisitCompositeLiteral(n) }
func (n *CompositeLiteral) AcceptMapper(v ASTMapper[any]) any { return v.MapCompositeLiteral(n) }
func (n *CallExpr) Pos() Position { return n.Pos_ }
func (n *CallExpr) End() Position { return n.End_ }
func (n *CallExpr) Accept(v Visitor) { v.VisitCallExpr(n) }
func (n *CallExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapCallExpr(n) }
func (n *InfixExpr) Pos() Position { return n.Pos_ }
func (n *InfixExpr) End() Position { return n.End_ }
func (n *InfixExpr) Accept(v Visitor) { v.VisitInfixExpr(n) }
func (n *InfixExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapInfixExpr(n) }
func (n *PrefixExpr) Pos() Position { return n.Pos_ }
func (n *PrefixExpr) End() Position { return n.End_ }
func (n *PrefixExpr) Accept(v Visitor) { v.VisitPrefixExpr(n) }
func (n *PrefixExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapPrefixExpr(n) }
func (n *FieldAccess) Pos() Position { return n.Pos_ }
func (n *FieldAccess) End() Position { return n.End_ }
func (n *FieldAccess) Accept(v Visitor) { v.VisitFieldAccess(n) }
func (n *FieldAccess) AcceptMapper(v ASTMapper[any]) any { return v.MapFieldAccess(n) }
func (n *IndexExpr) Pos() Position { return n.Pos_ }
func (n *IndexExpr) End() Position { return n.End_ }
func (n *IndexExpr) Accept(v Visitor) { v.VisitIndexExpr(n) }
func (n *IndexExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapIndexExpr(n) }
func (n *SliceExpr) Pos() Position { return n.Pos_ }
func (n *SliceExpr) End() Position { return n.End_ }
func (n *SliceExpr) Accept(v Visitor) { v.VisitSliceExpr(n) }
func (n *SliceExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapSliceExpr(n) }
func (n *IfExpr) Pos() Position { return n.Pos_ }
func (n *IfExpr) End() Position { return n.End_ }
func (n *IfExpr) Accept(v Visitor) { v.VisitIfExpr(n) }
func (n *IfExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapIfExpr(n) }
func (n *MatchExpr) Pos() Position { return n.Pos_ }
func (n *MatchExpr) End() Position { return n.End_ }
func (n *MatchExpr) Accept(v Visitor) { v.VisitMatchExpr(n) }
func (n *MatchExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapMatchExpr(n) }
func (n *WildcardPattern) Pos() Position { return n.Pos_ }
func (n *WildcardPattern) End() Position { return n.End_ }
func (n *WildcardPattern) Accept(v Visitor) { v.VisitWildcardPattern(n) }
func (n *WildcardPattern) AcceptMapper(v ASTMapper[any]) any { return v.MapWildcardPattern(n) }
func (n *IdentifierPattern) Pos() Position { return n.Pos_ }
func (n *IdentifierPattern) End() Position { return n.End_ }
func (n *IdentifierPattern) Accept(v Visitor) { v.VisitIdentifierPattern(n) }
func (n *IdentifierPattern) AcceptMapper(v ASTMapper[any]) any { return v.MapIdentifierPattern(n) }
func (n *LiteralPattern) Pos() Position { return n.Pos_ }
func (n *LiteralPattern) End() Position { return n.End_ }
func (n *LiteralPattern) Accept(v Visitor) { v.VisitLiteralPattern(n) }
func (n *LiteralPattern) AcceptMapper(v ASTMapper[any]) any { return v.MapLiteralPattern(n) }
func (n *CompositePattern) Pos() Position { return n.Pos_ }
func (n *CompositePattern) End() Position { return n.End_ }
func (n *CompositePattern) Accept(v Visitor) { v.VisitCompositePattern(n) }
func (n *CompositePattern) AcceptMapper(v ASTMapper[any]) any { return v.MapCompositePattern(n) }
func (n *TypeExprWrapper) Pos() Position { return n.Pos_ }
func (n *TypeExprWrapper) End() Position { return n.End_ }
func (n *TypeExprWrapper) Accept(v Visitor) { v.VisitTypeExprWrapper(n) }
func (n *TypeExprWrapper) AcceptMapper(v ASTMapper[any]) any { return v.MapTypeExprWrapper(n) }
func (n *NamedTypeExpr) Pos() Position { return n.Pos_ }
func (n *NamedTypeExpr) End() Position { return n.End_ }
func (n *NamedTypeExpr) Accept(v Visitor) { v.VisitNamedTypeExpr(n) }
func (n *NamedTypeExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapNamedTypeExpr(n) }
func (n *ArrayTypeExpr) Pos() Position { return n.Pos_ }
func (n *ArrayTypeExpr) End() Position { return n.End_ }
func (n *ArrayTypeExpr) Accept(v Visitor) { v.VisitArrayTypeExpr(n) }
func (n *ArrayTypeExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapArrayTypeExpr(n) }
func (n *StructTypeExpr) Pos() Position { return n.Pos_ }
func (n *StructTypeExpr) End() Position { return n.End_ }
func (n *StructTypeExpr) Accept(v Visitor) { v.VisitStructTypeExpr(n) }
func (n *StructTypeExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapStructTypeExpr(n) }
func (n *SumTypeExpr) Pos() Position { return n.Pos_ }
func (n *SumTypeExpr) End() Position { return n.End_ }
func (n *SumTypeExpr) Accept(v Visitor) { v.VisitSumTypeExpr(n) }
func (n *SumTypeExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapSumTypeExpr(n) }
func (n *GenericTypeExpr) Pos() Position { return n.Pos_ }
func (n *GenericTypeExpr) End() Position { return n.End_ }
func (n *GenericTypeExpr) Accept(v Visitor) { v.VisitGenericTypeExpr(n) }
func (n *GenericTypeExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapGenericTypeExpr(n) }
func (n *AwaitExpr) Pos() Position { return n.Pos_ }
func (n *AwaitExpr) End() Position { return n.End_ }
func (n *AwaitExpr) Accept(v Visitor) { v.VisitAwaitExpr(n) }
func (n *AwaitExpr) AcceptMapper(v ASTMapper[any]) any { return v.MapAwaitExpr(n) }
