// Code generated by gen_hir.go; DO NOT EDIT.
package hir

import "github.com/mattcarp12/maml/frontend/tast"

// =============================================================================
// Generated node lowering methods
//
// Each method here corresponds to a TAST node that maps 1-to-1 to an HIR node
// of the same name with the same fields. The hand-written lowerExpr/lowerStmt
// dispatchers call these for the straightforward cases.
// =============================================================================
func (l *Lowerer) lowerArrayLiteral(s *tast.ArrayLiteral) *ArrayLiteral {
	if s == nil {
		return nil
	}
	Elements_ := make([]Expr, len(s.Elements))
	for i, el := range s.Elements {
		Elements_[i] = l.lowerExpr(el)
	}
	return &ArrayLiteral{
		Pos_:     s.Pos_,
		End_:     s.End_,
		Elements: Elements_,
		Type:     s.Type,
	}
}
func (l *Lowerer) lowerAwaitExpr(s *tast.AwaitExpr) *AwaitExpr {
	if s == nil {
		return nil
	}
	return &AwaitExpr{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) lowerBoolLiteral(s *tast.BoolLiteral) *BoolLiteral {
	if s == nil {
		return nil
	}
	return &BoolLiteral{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: s.Value,
	}
}
func (l *Lowerer) lowerBreakStmt(s *tast.BreakStmt) *BreakStmt {
	if s == nil {
		return nil
	}
	return &BreakStmt{
		Pos_: s.Pos_,
		End_: s.End_,
	}
}
func (l *Lowerer) lowerContinueStmt(s *tast.ContinueStmt) *ContinueStmt {
	if s == nil {
		return nil
	}
	return &ContinueStmt{
		Pos_: s.Pos_,
		End_: s.End_,
	}
}
func (l *Lowerer) lowerDeclareStmt(s *tast.DeclareStmt) *DeclareStmt {
	if s == nil {
		return nil
	}
	return &DeclareStmt{
		Pos_:   s.Pos_,
		End_:   s.End_,
		Symbol: s.Symbol,
		Value:  l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) lowerIdentifier(s *tast.Identifier) *Identifier {
	if s == nil {
		return nil
	}
	return &Identifier{
		Pos_:   s.Pos_,
		End_:   s.End_,
		Symbol: s.Symbol,
		Type:   s.Type,
		Value:  s.Value,
	}
}
func (l *Lowerer) lowerIfExpr(s *tast.IfExpr) *IfExpr {
	if s == nil {
		return nil
	}
	return &IfExpr{
		Pos_:        s.Pos_,
		End_:        s.End_,
		Alternative: l.lowerBlockStmt(s.Alternative),
		Condition:   l.lowerExpr(s.Condition),
		Consequence: l.lowerBlockStmt(s.Consequence),
		Type:        s.Type,
	}
}
func (l *Lowerer) lowerIntLiteral(s *tast.IntLiteral) *IntLiteral {
	if s == nil {
		return nil
	}
	return &IntLiteral{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: s.Value,
	}
}
func (l *Lowerer) lowerPrefixExpr(s *tast.PrefixExpr) *PrefixExpr {
	if s == nil {
		return nil
	}
	return &PrefixExpr{
		Pos_:     s.Pos_,
		End_:     s.End_,
		Operator: s.Operator,
		Right:    l.lowerExpr(s.Right),
		Type:     s.Type,
	}
}
func (l *Lowerer) lowerReturnStmt(s *tast.ReturnStmt) *ReturnStmt {
	if s == nil {
		return nil
	}
	return &ReturnStmt{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Value: l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) lowerSliceExpr(s *tast.SliceExpr) *SliceExpr {
	if s == nil {
		return nil
	}
	return &SliceExpr{
		Pos_: s.Pos_,
		End_: s.End_,
		High: l.lowerExpr(s.High),
		Left: l.lowerExpr(s.Left),
		Low:  l.lowerExpr(s.Low),
		Type: s.Type,
	}
}
func (l *Lowerer) lowerStringLiteral(s *tast.StringLiteral) *StringLiteral {
	if s == nil {
		return nil
	}
	return &StringLiteral{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: s.Value,
	}
}
func (l *Lowerer) lowerVecLiteral(s *tast.VecLiteral) *VecLiteral {
	if s == nil {
		return nil
	}
	Elements_ := make([]Expr, len(s.Elements))
	for i, el := range s.Elements {
		Elements_[i] = l.lowerExpr(el)
	}
	return &VecLiteral{
		Pos_:     s.Pos_,
		End_:     s.End_,
		Elements: Elements_,
		Type:     s.Type,
	}
}
func (l *Lowerer) lowerYieldStmt(s *tast.YieldStmt) *YieldStmt {
	if s == nil {
		return nil
	}
	return &YieldStmt{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Value: l.lowerExpr(s.Value),
	}
}

// =============================================================================
// Generated helper lowering functions
//
// Each function lowers a TAST helper struct (used in slices by hand-written
// lowerers) that maps 1-to-1 to the corresponding HIR helper struct.
// =============================================================================
func lowerTASTCallArg(l *Lowerer, h tast.CallArg) CallArg {
	return CallArg{
		Pos_:     h.Pos_,
		End_:     h.End_,
		Argument: l.lowerExpr(h.Argument),
		Mut:      h.Mut,
	}
}
func lowerTASTMapElement(l *Lowerer, h tast.MapElement) MapElement {
	return MapElement{
		Pos_:  h.Pos_,
		End_:  h.End_,
		Key:   l.lowerExpr(h.Key),
		Value: l.lowerExpr(h.Value),
	}
}
func lowerTASTParam(l *Lowerer, h tast.Param) Param {
	return Param{
		Pos_:   h.Pos_,
		End_:   h.End_,
		Name:   h.Name,
		Symbol: h.Symbol,
		Type:   h.Type,
	}
}
func lowerTASTVariantField(l *Lowerer, h tast.VariantField) VariantField {
	return VariantField{
		Pos_:  h.Pos_,
		End_:  h.End_,
		Name:  h.Name,
		Value: l.lowerExpr(h.Value),
	}
}
