// Code generated by gen_hir.go; DO NOT EDIT.
package hir

import "github.com/mattcarp12/maml/frontend/tast"

// Ensure Lowerer satisfies the TAST Mapper interface at compile time.
var _ tast.Mapper[Node] = (*Lowerer)(nil)

// =============================================================================
// Generated node lowering methods (Implementing tast.Mapper[hir.Node])
// =============================================================================
func (l *Lowerer) MapArrayLiteral(s *tast.ArrayLiteral) Node {
	if s == nil {
		return nil
	}
	Elements_ := make([]Expr, len(s.Elements))
	for i, el := range s.Elements {
		Elements_[i] = l.lowerExpr(el)
	}
	return &ArrayLiteral{
		Pos_:     s.Pos_,
		End_:     s.End_,
		Elements: Elements_,
		Type:     s.Type,
	}
}
func (l *Lowerer) MapAwaitExpr(s *tast.AwaitExpr) Node {
	if s == nil {
		return nil
	}
	return &AwaitExpr{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) MapBoolLiteral(s *tast.BoolLiteral) Node {
	if s == nil {
		return nil
	}
	return &BoolLiteral{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: s.Value,
	}
}
func (l *Lowerer) MapBreakStmt(s *tast.BreakStmt) Node {
	if s == nil {
		return nil
	}
	return &BreakStmt{
		Pos_: s.Pos_,
		End_: s.End_,
	}
}
func (l *Lowerer) MapContinueStmt(s *tast.ContinueStmt) Node {
	if s == nil {
		return nil
	}
	return &ContinueStmt{
		Pos_: s.Pos_,
		End_: s.End_,
	}
}
func (l *Lowerer) MapDeclareStmt(s *tast.DeclareStmt) Node {
	if s == nil {
		return nil
	}
	return &DeclareStmt{
		Pos_:   s.Pos_,
		End_:   s.End_,
		Symbol: s.Symbol,
		Value:  l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) MapFreezeExpr(s *tast.FreezeExpr) Node {
	if s == nil {
		return nil
	}
	return &FreezeExpr{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) MapIdentifier(s *tast.Identifier) Node {
	if s == nil {
		return nil
	}
	return &Identifier{
		Pos_:   s.Pos_,
		End_:   s.End_,
		Symbol: s.Symbol,
		Type:   s.Type,
		Value:  s.Value,
	}
}
func (l *Lowerer) MapIfExpr(s *tast.IfExpr) Node {
	if s == nil {
		return nil
	}
	return &IfExpr{
		Pos_:        s.Pos_,
		End_:        s.End_,
		Alternative: l.lowerBlockStmt(s.Alternative),
		Condition:   l.lowerExpr(s.Condition),
		Consequence: l.lowerBlockStmt(s.Consequence),
		Type:        s.Type,
	}
}
func (l *Lowerer) MapIntLiteral(s *tast.IntLiteral) Node {
	if s == nil {
		return nil
	}
	return &IntLiteral{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: s.Value,
	}
}
func (l *Lowerer) MapOwnExpr(s *tast.OwnExpr) Node {
	if s == nil {
		return nil
	}
	return &OwnExpr{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) MapPrefixExpr(s *tast.PrefixExpr) Node {
	if s == nil {
		return nil
	}
	return &PrefixExpr{
		Pos_:     s.Pos_,
		End_:     s.End_,
		Operator: s.Operator,
		Right:    l.lowerExpr(s.Right),
		Type:     s.Type,
	}
}
func (l *Lowerer) MapReturnStmt(s *tast.ReturnStmt) Node {
	if s == nil {
		return nil
	}
	return &ReturnStmt{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Value: l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) MapSliceExpr(s *tast.SliceExpr) Node {
	if s == nil {
		return nil
	}
	return &SliceExpr{
		Pos_: s.Pos_,
		End_: s.End_,
		High: l.lowerExpr(s.High),
		Left: l.lowerExpr(s.Left),
		Low:  l.lowerExpr(s.Low),
		Type: s.Type,
	}
}
func (l *Lowerer) MapSpawnExpr(s *tast.SpawnExpr) Node {
	if s == nil {
		return nil
	}
	return &SpawnExpr{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: l.lowerExpr(s.Value),
	}
}
func (l *Lowerer) MapStringLiteral(s *tast.StringLiteral) Node {
	if s == nil {
		return nil
	}
	return &StringLiteral{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Type:  s.Type,
		Value: s.Value,
	}
}
func (l *Lowerer) MapVecLiteral(s *tast.VecLiteral) Node {
	if s == nil {
		return nil
	}
	Elements_ := make([]Expr, len(s.Elements))
	for i, el := range s.Elements {
		Elements_[i] = l.lowerExpr(el)
	}
	return &VecLiteral{
		Pos_:     s.Pos_,
		End_:     s.End_,
		Elements: Elements_,
		Type:     s.Type,
	}
}
func (l *Lowerer) MapYieldStmt(s *tast.YieldStmt) Node {
	if s == nil {
		return nil
	}
	return &YieldStmt{
		Pos_:  s.Pos_,
		End_:  s.End_,
		Value: l.lowerExpr(s.Value),
	}
}

// =============================================================================
// Generated helper lowering functions
// =============================================================================
func lowerTASTCallArg(l *Lowerer, h tast.CallArg) CallArg {
	return CallArg{
		Pos_:     h.Pos_,
		End_:     h.End_,
		Argument: l.lowerExpr(h.Argument),
		Mut:      h.Mut,
	}
}
func lowerTASTMapElement(l *Lowerer, h tast.MapElement) MapElement {
	return MapElement{
		Pos_:  h.Pos_,
		End_:  h.End_,
		Key:   l.lowerExpr(h.Key),
		Value: l.lowerExpr(h.Value),
	}
}
func lowerTASTParam(l *Lowerer, h tast.Param) Param {
	return Param{
		Pos_:   h.Pos_,
		End_:   h.End_,
		Name:   h.Name,
		Symbol: h.Symbol,
		Type:   h.Type,
	}
}
func lowerTASTVariantField(l *Lowerer, h tast.VariantField) VariantField {
	return VariantField{
		Pos_:  h.Pos_,
		End_:  h.End_,
		Name:  h.Name,
		Value: l.lowerExpr(h.Value),
	}
}
