#!/usr/bin/env python3
import json
import os

def main():
    manifest_path = "runtime_manifest.json"
    if not os.path.exists(manifest_path):
        print(f"Error: {manifest_path} not found.")
        return

    with open(manifest_path, "r") as f:
        manifest = json.load(f)

    # Gather all unique runtime symbols and details
    symbols = {}
    
    def add_sym(sym_name, data):
        symbols[sym_name] = data

    for cat in manifest.get("operators", {}).values():
        for variant in cat.values():
            add_sym(variant["runtime_symbol"], variant)
            
    for cat in manifest.get("builtins", {}).values():
        for variant in cat.values():
            add_sym(variant["runtime_symbol"], variant)

    for sym_name, data in manifest.get("global_functions", {}).items():
        add_sym(sym_name, data)

    # 1. Generate Go Frontend File
    generate_go(symbols)

    # 2. Generate C++ Backend File (declarations)
    generate_cpp(symbols)

    # 3. Generate RuntimeConstants.h (Passing the flattened dictionary keys)
    generate_constants_h(symbols.keys())


def generate_go(symbols):
    os.makedirs("frontend", exist_ok=True)
    go_path = "frontend/autogen_symbols.go"
    
    with open(go_path, "w") as f:
        f.write("// Code generated by tools/codegen.py. DO NOT EDIT.\n")
        f.write("package frontend\n\n")
        f.write("const (\n")
        for sym in sorted(symbols.keys()):
            upper_name = sym.upper()
            f.write(f'\tSYM_{upper_name} = "{sym}"\n')
        f.write(")\n")
    print(f"✅ Generated {go_path}")


def generate_cpp(symbols):
    os.makedirs("backend/include", exist_ok=True)
    cpp_path = "backend/include/autogen_runtime.inc"
    
    # Map types directly to LLVM Context builders
    type_map = {
        "void": "llvm::Type::getVoidTy(ctx.Context)",
        "ptr":  "llvm::PointerType::getUnqual(ctx.Context)",
        "i64":  "llvm::Type::getInt64Ty(ctx.Context)",
        "i32":  "llvm::Type::getInt32Ty(ctx.Context)",
        "i8":   "llvm::Type::getInt8Ty(ctx.Context)",
        "bool": "llvm::Type::getInt1Ty(ctx.Context)"  # Fixed syntax error here: context -> ctx.Context
    }

    with open(cpp_path, "w") as f:
        f.write("// Code generated by tools/codegen.py. DO NOT EDIT.\n\n")
        # Ensure LLVM headers are included if parsed stand-alone
        f.write("#include <llvm/IR/DerivedTypes.h>\n")
        f.write("#include <llvm/IR/Type.h>\n")
        f.write("#include \"CodegenContext.h\"\n\n")
        
        f.write("namespace maml {\n\n")
        f.write("inline void declareAutogeneratedFunctions(CodegenContext &ctx) {\n")
        f.write("    auto &Module = ctx.Module;\n\n")
        
        for sym in sorted(symbols.keys()):
            data = symbols[sym]
            ret_ty = type_map[data["return"]]
            args_tys = ", ".join([type_map[a] for a in data["args"]])
            
            f.write(f'    // {sym}\n')
            f.write(f'    Module->getOrInsertFunction("{sym}",\n')
            f.write(f'        llvm::FunctionType::get({ret_ty}, {{{args_tys}}}, false));\n\n')
            
        f.write("}\n\n")
        f.write("} // namespace maml\n")
    print(f"✅ Generated {cpp_path}")


def generate_constants_h(symbol_names):
    """
    Generates RuntimeConstants.h using the already-flattened symbol names list.
    """
    os.makedirs("backend/include", exist_ok=True)
    h_path = "backend/include/RuntimeConstants.h"
    
    with open(h_path, "w") as f:
        f.write("#ifndef MAML_RUNTIME_CONSTANTS_H\n")
        f.write("#define MAML_RUNTIME_CONSTANTS_H\n\n")
        f.write("namespace maml {\n")
        f.write("namespace rt {\n\n")

        # Categorize sorted symbols to keep the output clean
        memory_arc = []
        containers = []
        coroutines = []
        others = []

        for sym in sorted(symbol_names):
            if sym in ["maml_alloc", "maml_free", "maml_retain", "maml_release"]:
                memory_arc.append(sym)
            elif any(sym.startswith(p) for p in ["maml_vec_", "maml_map_", "maml_str_"]):
                containers.append(sym)
            elif "coro" in sym:
                coroutines.append(sym)
            else:
                others.append(sym)

        def write_category(title, sym_list):
            if not sym_list:
                return
            f.write(f"// --- {title} ---\n")
            for sym in sym_list:
                # Format names cleanly: maml_vec_grow -> VEC_GROW, puts -> PUTS
                const_name = sym.upper().replace("MAML_", "")
                f.write(f'constexpr const char* {const_name} = "{sym}";\n')
            f.write("\n")

        write_category("Memory & ARC Constants", memory_arc)
        write_category("Container & String Constants", containers)
        write_category("Coroutine Constants", coroutines)
        write_category("Miscellaneous Constants", others)

        f.write("} // namespace rt\n")
        f.write("} // namespace maml\n\n")
        f.write("#endif // MAML_RUNTIME_CONSTANTS_H\n")
    
    print(f"✅ Generated {h_path}")


if __name__ == "__main__":
    main()
