function(embed_file INPUT_FILE OUTPUT_HEADER VARIABLE_NAME NAMESPACE)
    # Re-run CMake configure if the source .maml file changes
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${INPUT_FILE}")

    if(NOT EXISTS "${INPUT_FILE}")
        message(FATAL_ERROR "embed_file: Source file '${INPUT_FILE}' does not exist.")
    endif()

    file(READ "${INPUT_FILE}" FILE_CONTENTS)

    # Wrap the contents in a C++20 raw string literal R"maml_embed(...)maml_embed"
    set(HEADER_CONTENT "// Auto-generated by CMake. Do not edit.\n#pragma once\n#include <string_view>\n\nnamespace ${NAMESPACE} {\ninline constexpr std::string_view ${VARIABLE_NAME} = R\"maml_embed(\n${FILE_CONTENTS}\n)maml_embed\";\n}\n")

    file(WRITE "${OUTPUT_HEADER}" "${HEADER_CONTENT}")
    message(STATUS "Embedded '${INPUT_FILE}' -> '${OUTPUT_HEADER}'")
endfunction()