package lower

import (
	"github.com/mattcarp12/maml/frontend/ast"
	"github.com/mattcarp12/maml/frontend/escape"
)

// AllocPass uses the results of the Escape Analyzer to explicitly wrap
// data initializations in StackAllocExpr or HeapAllocExpr.
type AllocPass struct {
	escapeMap map[ast.Node]escape.EscapeState
}

// NewAllocPass requires the map generated by escape.Analyzer.Analyze()
func NewAllocPass(escapeMap map[ast.Node]escape.EscapeState) *AllocPass {
	return &AllocPass{escapeMap: escapeMap}
}

func (p *AllocPass) Rewrite(node ast.Node) ast.Node {
	switch expr := node.(type) {
	case *ast.ArrayLiteral, *ast.StructLiteral:
		// If the escape analyzer specifically marked this for the heap, heap allocate it.
		state, exists := p.escapeMap[node]
		if exists && state == escape.StateHeap {
			return &ast.HeapAllocExpr{
				Value: expr.(ast.Expr),
				Pos_:  expr.Pos(),
			}
		}
		// Default: safe stack allocation for all untracked aggregate markers
		return &ast.StackAllocExpr{
			Value: expr.(ast.Expr),
			Pos_:  expr.Pos(),
		}
	}
	return node
}
