package lower

import (
	"github.com/mattcarp12/maml/frontend/ast"
	"github.com/mattcarp12/maml/frontend/sema"
	"github.com/mattcarp12/maml/frontend/token"
)

// Pass implements ast.Mutator to desugar complex AST nodes into primitive ones.
type Pass struct {
	typeMap map[ast.Node]sema.Type
}

// NewPass now requires the TypeMap generated by the Semantic Analyzer
func NewPass(typeMap map[ast.Node]sema.Type) *Pass {
	return &Pass{typeMap: typeMap}
}

func (p *Pass) Rewrite(node ast.Node) ast.Node {
	switch n := node.(type) {
	case *ast.ForStmt:
		return p.lowerForStmt(n)
	case *ast.CallExpr:
		return p.lowerCallExpr(n)
	case *ast.MatchExpr:
		return p.lowerMatchExpr(n) // NEW
	}
	return node
}

func (p *Pass) lowerForStmt(forStmt *ast.ForStmt) ast.Node {
	// 1. Construct the inverse condition: `!Condition`
	// If there is no condition, it defaults to `!true` which evaluates to `false`.
	var condExpr ast.Expr
	if forStmt.Condition != nil {
		condExpr = &ast.PrefixExpr{
			Operator: "!",
			Right:    forStmt.Condition,
			Pos_:     forStmt.Condition.Pos(),
		}
	} else {
		condExpr = &ast.BoolLiteral{
			Value: false, // Infinite loop if no condition
			Pos_:  forStmt.Pos(),
		}
	}

	// 2. Construct the Break statement: `{ break; }`
	breakBlock := &ast.BlockStmt{
		Statements: []ast.Stmt{
			&ast.BreakStmt{
				Token: token.Token{Type: token.BREAK, Literal: "break", Line: forStmt.Pos().Line, Col: forStmt.Pos().Col},
			},
		},
		Pos_: forStmt.Pos(),
		End_: forStmt.Pos(),
	}

	// 3. Construct the If expression: `if (!Condition) { break; }`
	ifBreak := &ast.IfExpr{
		Condition:   condExpr,
		Consequence: breakBlock,
		Alternative: nil,
		Pos_:        forStmt.Pos(),
	}

	// 4. Assemble the body of the infinite loop
	// Order: IfBreak -> original body -> PostStmt
	loopBodyStmts := []ast.Stmt{
		&ast.ExprStmt{Value: ifBreak, Pos_: forStmt.Pos()},
	}

	if forStmt.Body != nil {
		// Inline the original body's statements to avoid nested blocks if possible
		loopBodyStmts = append(loopBodyStmts, forStmt.Body.Statements...)
	}

	if forStmt.Post != nil {
		loopBodyStmts = append(loopBodyStmts, forStmt.Post)
	}

	loopBlock := &ast.BlockStmt{
		Statements: loopBodyStmts,
		Pos_:       forStmt.Pos(),
		End_:       forStmt.End(),
	}

	loopStmt := &ast.LoopStmt{
		Body: loopBlock,
		Pos_: forStmt.Pos(),
		End_: forStmt.End(),
	}

	// 5. Wrap everything in an outer block to preserve the scope of the InitStmt
	var outerStmts []ast.Stmt
	if forStmt.Init != nil {
		outerStmts = append(outerStmts, forStmt.Init)
	}
	outerStmts = append(outerStmts, loopStmt)

	return &ast.BlockStmt{
		Statements: outerStmts,
		Pos_:       forStmt.Pos(),
		End_:       forStmt.End(),
	}
}

func (p *Pass) lowerCallExpr(call *ast.CallExpr) ast.Node {
	// Check if this is a method call (e.g., obj.method())
	fa, isFieldAccess := call.Function.(*ast.FieldAccess)
	if !isFieldAccess {
		return call // It's a standard function call, leave it alone
	}

	// Retrieve the type of the object being accessed
	objType := p.typeMap[fa.Object]

	// 1. Handle Map Built-ins
	if _, isMap := objType.(*sema.MapType); isMap {
		methodName := fa.Field.Value
		if methodName == "put" || methodName == "get" {
			// Rewrite: map.put(k, v) -> maml_map_put(map, k, v)
			funcName := "maml_map_" + methodName

			// The object itself becomes the first argument
			newArgs := []ast.CallArg{
				{Argument: fa.Object, Pos_: fa.Object.Pos()},
			}
			newArgs = append(newArgs, call.Arguments...)

			newFuncIdent := &ast.Identifier{Value: funcName, Pos_: fa.Pos()}
			newCall := &ast.CallExpr{
				Function:  newFuncIdent,
				Arguments: newArgs,
				Pos_:      call.Pos(),
			}

			// Migrate the type mapping so later phases know what this is
			p.typeMap[newFuncIdent] = &sema.FunctionType{} // Dummy signature marker
			p.typeMap[newCall] = p.typeMap[call]

			return newCall
		}
	}

	// 2. Handle Vector Built-ins
	if _, isVec := objType.(*sema.VectorType); isVec {
		methodName := fa.Field.Value
		switch methodName {
		case "push":
			// Rewrite: vec.push(v) -> maml_vec_push(vec, v)
			newArgs := []ast.CallArg{
				{Argument: fa.Object, Pos_: fa.Object.Pos()},
			}
			newArgs = append(newArgs, call.Arguments...)

			newFuncIdent := &ast.Identifier{Value: "maml_vec_push", Pos_: fa.Pos()}
			newCall := &ast.CallExpr{
				Function:  newFuncIdent,
				Arguments: newArgs,
				Pos_:      call.Pos(),
			}

			p.typeMap[newFuncIdent] = &sema.FunctionType{}
			p.typeMap[newCall] = p.typeMap[call]

			return newCall

		case "len":
			// Rewrite: vec.len() -> vec.len
			// We strip the CallExpr wrapper entirely and return the inner FieldAccess.
			p.typeMap[fa] = p.typeMap[call] // Transfer the 'int' return type to the FieldAccess
			return fa
		}
	}

	return call
}

func (p *Pass) lowerMatchExpr(match *ast.MatchExpr) ast.Node {
	subjType := p.typeMap[match.Subject]
	sumTy, isSum := subjType.(*sema.SumType)
	if !isSum {
		return match // Invalid subject type, leave for SEMA to error
	}

	// 1. Declare a hidden variable to evaluate the subject exactly once
	subjIdent := &ast.Identifier{Value: "_match_subj", Pos_: match.Pos()}
	p.typeMap[subjIdent] = subjType

	var currentElse ast.Expr = nil

	// 2. Build the if/else chain from bottom to top
	for i := len(match.Arms) - 1; i >= 0; i-- {
		arm := match.Arms[i]

		// Wildcard arms become the ultimate "else" block
		if _, isWild := arm.Pattern.(*ast.WildcardPattern); isWild {
			currentElse = arm.Body
			continue
		}

		vp, isVariant := arm.Pattern.(*ast.VariantPattern)
		if !isVariant {
			continue
		}

		variantDef := sumTy.GetVariant(vp.Name)
		if variantDef == nil {
			continue
		}

		// Condition: _match_subj.0 == variant_discriminant
		discrimAccess := &ast.FieldAccess{
			Object: subjIdent,
			Field:  &ast.Identifier{Value: "0", Pos_: vp.Pos()},
			Pos_:   vp.Pos(),
		}
		p.typeMap[discrimAccess] = &sema.IntType{}

		cond := &ast.InfixExpr{
			Left:     discrimAccess,
			Operator: "==",
			Right:    &ast.IntLiteral{Value: int64(variantDef.Discriminant), Pos_: vp.Pos()},
			Pos_:     vp.Pos(),
		}
		p.typeMap[cond] = &sema.BoolType{}

		// Consequence Block
		conseq := &ast.BlockStmt{
			Statements: []ast.Stmt{},
			Pos_:       arm.Body.Pos(),
			End_:       arm.Body.End(),
		}

		// Inject Payload Bindings
		if !variantDef.IsUnit() {
			payloadAccess := &ast.FieldAccess{
				Object: subjIdent,
				Field:  &ast.Identifier{Value: "1", Pos_: vp.Pos()},
				Pos_:   vp.Pos(),
			}

			// Define a synthesized StructType for this payload so the backend knows its layout
			payloadStructTy := &sema.StructType{
				Name:   sumTy.BaseName + "_" + vp.Name + "_Payload",
				Fields: variantDef.Fields,
			}
			p.typeMap[payloadAccess] = payloadStructTy

			// Handle single binding: case Circle(r)
			if vp.Binding != nil {
				decl := &ast.DeclareStmt{
					Name:    vp.Binding.Value,
					Value:   payloadAccess,
					Mutable: false,
					Pos_:    vp.Pos(),
				}
				conseq.Statements = append(conseq.Statements, decl)
			} else if len(vp.Fields) > 0 {
				// Handle field bindings: case Rect{width: w}
				for _, fb := range vp.Fields {
					fieldAcc := &ast.FieldAccess{
						Object: payloadAccess,
						Field:  &ast.Identifier{Value: fb.Field, Pos_: vp.Pos()},
						Pos_:   vp.Pos(),
					}

					var fType sema.Type = &sema.UnknownType{}
					for _, fdef := range variantDef.Fields {
						if fdef.Name == fb.Field {
							fType = fdef.Type
							break
						}
					}
					p.typeMap[fieldAcc] = fType

					decl := &ast.DeclareStmt{
						Name:    fb.Binding.Value,
						Value:   fieldAcc,
						Mutable: false,
						Pos_:    vp.Pos(),
					}
					conseq.Statements = append(conseq.Statements, decl)
				}
			}
		}

		// Append the original arm statements AFTER the bindings
		conseq.Statements = append(conseq.Statements, arm.Body.(*ast.BlockStmt).Statements...)

		// Prepare the Alternative (else) block
		var altBlock *ast.BlockStmt
		if currentElse != nil {
			if b, ok := currentElse.(*ast.BlockStmt); ok {
				altBlock = b
			} else {
				altBlock = &ast.BlockStmt{
					Statements: []ast.Stmt{&ast.YieldStmt{Value: currentElse, Pos_: currentElse.Pos()}},
					Pos_:       currentElse.Pos(),
					End_:       currentElse.End(),
				}
			}
		}

		ifExpr := &ast.IfExpr{
			Condition:   cond,
			Consequence: conseq,
			Alternative: altBlock,
			Pos_:        vp.Pos(),
		}
		p.typeMap[ifExpr] = p.typeMap[match]
		currentElse = ifExpr
	}

	// 3. Wrap in an outer block to safely evaluate the subject declaration first
	outerBlock := &ast.BlockStmt{
		Statements: []ast.Stmt{
			&ast.DeclareStmt{
				Name:    "_match_subj",
				Value:   match.Subject,
				Mutable: false,
				Pos_:    match.Pos(),
			},
			&ast.YieldStmt{
				Value: currentElse,
				Pos_:  match.Pos(),
			},
		},
		Pos_: match.Pos(),
		End_: match.End(),
	}
	p.typeMap[outerBlock] = p.typeMap[match]

	return outerBlock
}
